# Generated by Django 5.0.1 on 2025-07-02 16:30

import common.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='favoritestock',
            name='added_at',
            field=common.fields.TimestampField(auto_now_add=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=common.fields.TimestampField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=common.fields.TimestampField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
