# Generated by Django 5.0.1 on 2025-04-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsconst',
            name='stock',
            field=models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='hs_constituents', to='stock_models.stockinfo', verbose_name='股票'),
        ),
    ]
