# Generated by Django 5.0.1 on 2025-04-06 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indexbolldata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indexbolldata',
            name='index',
        ),
        migrations.AlterUniqueTogether(
            name='indexkdjdata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indexkdjdata',
            name='index',
        ),
        migrations.AlterUniqueTogether(
            name='indexmacddata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indexmacddata',
            name='index',
        ),
        migrations.AlterUniqueTogether(
            name='indexmadata',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='indexmadata',
            name='index',
        ),
        migrations.AlterUniqueTogether(
            name='stockmacdfib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockmacdfib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockmacdindicator',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockmacdindicator',
            name='stock',
        ),
        migrations.AlterModelOptions(
            name='indextimeseriesdata',
            options={'verbose_name': '时间序列数据', 'verbose_name_plural': '时间序列数据'},
        ),
        migrations.RemoveIndex(
            model_name='indextimeseriesdata',
            name='index_time__index_i_8f3cae_idx',
        ),
        migrations.RemoveField(
            model_name='indextimeseriesdata',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='indextimeseriesdata',
            name='change_rate',
        ),
        migrations.RemoveField(
            model_name='indextimeseriesdata',
            name='circulating_market_value',
        ),
        migrations.RemoveField(
            model_name='indextimeseriesdata',
            name='total_market_value',
        ),
        migrations.AddField(
            model_name='indextimeseriesdata',
            name='amplitude',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='振幅(%)'),
        ),
        migrations.AddField(
            model_name='indextimeseriesdata',
            name='change_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='涨跌幅(%)'),
        ),
        migrations.AddField(
            model_name='indextimeseriesdata',
            name='turnover',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额(元)'),
        ),
        migrations.AlterField(
            model_name='indexinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indexrealtimedata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='涨跌额(元)'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='high_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最高价'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='stock_models.indexinfo', verbose_name='股票指数'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='low_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最低价'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='time_level',
            field=models.CharField(max_length=10, verbose_name='时间级别'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='trade_time',
            field=models.DateTimeField(verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='turnover_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='换手率(%)'),
        ),
        migrations.AlterField(
            model_name='indextimeseriesdata',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='成交量(手)'),
        ),
        migrations.AlterField(
            model_name='marketoverview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='indextimeseriesdata',
            index=models.Index(fields=['index'], name='index_time__index_i_b887b7_idx'),
        ),
        migrations.AddIndex(
            model_name='indextimeseriesdata',
            index=models.Index(fields=['time_level'], name='index_time__time_le_02f9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='indextimeseriesdata',
            index=models.Index(fields=['trade_time'], name='index_time__trade_t_bae67f_idx'),
        ),
        migrations.DeleteModel(
            name='IndexBOLLData',
        ),
        migrations.DeleteModel(
            name='IndexKDJData',
        ),
        migrations.DeleteModel(
            name='IndexMACDData',
        ),
        migrations.DeleteModel(
            name='IndexMAData',
        ),
        migrations.DeleteModel(
            name='StockMACDFIB',
        ),
        migrations.DeleteModel(
            name='StockMACDIndicator',
        ),
    ]
