# Generated by Django 5.0.1 on 2025-08-04 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='signalplaybookdetail',
        #     name='signal',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_models.tradingsignal'),
        # ),
        migrations.AlterField(
            model_name='signalplaybookdetail',
            name='playbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_models.playbook'),
        ),
        migrations.AlterUniqueTogether(
            name='dailypositionsnapshot',
            unique_together={('position', 'snapshot_date')},
        ),
        migrations.AlterUniqueTogether(
            name='favoritestocktracker',
            unique_together={('user', 'stock', 'entry_signal')},
        ),
        migrations.AlterUniqueTogether(
            name='signalplaybookdetail',
            unique_together={('signal', 'playbook')},
        ),
        migrations.AlterUniqueTogether(
            name='topinst',
            unique_together={('trade_date', 'stock', 'exalter', 'side', 'reason')},
        ),
        migrations.AlterUniqueTogether(
            name='toplist',
            unique_together={('trade_date', 'stock', 'reason')},
        ),
        migrations.AlterUniqueTogether(
            name='tradingsignal',
            unique_together={('stock', 'trade_time', 'timeframe', 'strategy_name')},
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['stock', 'timeframe', 'exit_signal_code', 'trade_time'], name='idx_stock_tf_sell_time'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['entry_signal', 'timeframe', 'stock'], name='idx_entry_tf_stock'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['trade_time', 'entry_score'], name='idx_trade_time_score'),
        ),
        migrations.AddConstraint(
            model_name='thsindexmember',
            constraint=models.UniqueConstraint(fields=('ths_index', 'stock'), name='unique_index_stock'),
        ),
        migrations.AlterModelTable(
            name='positiontracker',
            table=None,
        ),
    ]
