# Generated by Django 5.0.1 on 2025-08-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0002_playbook_signalplaybookdetail_tradingsignal_and_more'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='dailypositionsnapshot',
            name='entry_score',
        ),
        migrations.AddField(
            model_name='dailypositionsnapshot',
            name='offensive_score',
            field=models.IntegerField(default=0, verbose_name='总进攻分'),
        ),
        migrations.AddField(
            model_name='dailypositionsnapshot',
            name='score_details_json',
            field=models.JSONField(default=dict, verbose_name='分数构成详情(JSON)'),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='risk_score',
            field=models.IntegerField(default=0, verbose_name='总风险分'),
        ),
        migrations.CreateModel(
            name='PositionScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(db_index=True, max_length=255, verbose_name='信号名称(代码)')),
                ('signal_cn_name', models.CharField(max_length=255, verbose_name='信号中文名')),
                ('score_type', models.CharField(choices=[('positional', '阵地分'), ('dynamic', '动能分'), ('composite', '战法分'), ('trigger', '触发器分'), ('risk', '风险分')], max_length=20, verbose_name='分数类型')),
                ('score_value', models.IntegerField(verbose_name='贡献分数')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_details', to='stock_models.dailypositionsnapshot', verbose_name='所属快照')),
            ],
            options={
                'verbose_name': '持仓分数详情',
                'verbose_name_plural': '持仓分数详情',
                'db_table': 'strategy_position_score_detail',
                'indexes': [models.Index(fields=['snapshot', 'score_type'], name='strategy_po_snapsho_ee2000_idx')],
            },
        ),
    ]
