# Generated by Django 5.0.1 on 2025-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0002_alter_hsconst_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundflowcntths',
            options={'verbose_name': '同花顺概念板块资金流向', 'verbose_name_plural': '同花顺概念板块资金流向'},
        ),
        migrations.RemoveIndex(
            model_name='fundflowcntths',
            name='fund_flow_c_ths_ind_214af5_idx',
        ),
        migrations.RemoveIndex(
            model_name='fundflowcntths',
            name='fund_flow_c_trade_t_fdd82b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='fundflowcntths',
            unique_together={('trade_time', 'ths_index')},
        ),
        migrations.AddField(
            model_name='fundflowcntths',
            name='close_price',
            field=models.FloatField(blank=True, null=True, verbose_name='最新价'),
        ),
        migrations.AddField(
            model_name='fundflowcntths',
            name='index_close',
            field=models.FloatField(blank=True, null=True, verbose_name='板块指数'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='net_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='净额(亿元)'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='net_buy_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='流入资金(亿元)'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='net_sell_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='流出资金(亿元)'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='pct_change',
            field=models.FloatField(blank=True, null=True, verbose_name='行业涨跌幅'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='pct_change_stock',
            field=models.FloatField(blank=True, null=True, verbose_name='领涨股涨跌幅'),
        ),
        migrations.AlterModelTable(
            name='fundflowcntths',
            table='ths_moneyflow',
        ),
        migrations.RemoveField(
            model_name='fundflowcntths',
            name='industry_index',
        ),
    ]
