# Generated by Django 5.0.1 on 2025-08-05 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0003_remove_dailypositionsnapshot_entry_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailypositionsnapshot',
            unique_together={('tracker', 'snapshot_date')},
        ),
        migrations.AddField(
            model_name='dailypositionsnapshot',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='持仓盈亏'),
        ),
        migrations.AddField(
            model_name='dailypositionsnapshot',
            name='tracker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='stock_models.positiontracker', verbose_name='持仓追踪器'),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当日收盘价'),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='profit_loss_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='持仓盈亏率(%)'),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='snapshot_date',
            field=models.DateField(db_index=True, verbose_name='快照日期'),
        ),
        migrations.AlterModelTable(
            name='dailypositionsnapshot',
            table=None,
        ),
        migrations.CreateModel(
            name='StrategyDailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日期')),
                ('strategy_name', models.CharField(db_index=True, max_length=100, verbose_name='策略名称')),
                ('offensive_score', models.IntegerField(default=0, verbose_name='总进攻分')),
                ('risk_score', models.IntegerField(default=0, verbose_name='总风险分')),
                ('final_score', models.FloatField(default=0.0, verbose_name='最终得分')),
                ('signal_type', models.CharField(max_length=20, verbose_name='信号类型')),
                ('score_details_json', models.JSONField(default=dict, verbose_name='分数构成详情(JSON)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_daily_scores', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '策略每日分数',
                'verbose_name_plural': '策略每日分数',
                'db_table': 'strategy_daily_score',
                'ordering': ['-trade_date'],
                'unique_together': {('stock', 'trade_date', 'strategy_name')},
            },
        ),
        migrations.AddField(
            model_name='dailypositionsnapshot',
            name='daily_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_snapshots', to='stock_models.strategydailyscore', verbose_name='关联的每日分数'),
        ),
        migrations.CreateModel(
            name='StrategyScoreComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(db_index=True, max_length=255, verbose_name='信号名称(代码)')),
                ('signal_cn_name', models.CharField(max_length=255, verbose_name='信号中文名')),
                ('score_type', models.CharField(choices=[('positional', '阵地分'), ('dynamic', '动能分'), ('composite', '战法分'), ('trigger', '触发器分'), ('risk', '风险分'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='分数类型')),
                ('score_value', models.IntegerField(verbose_name='贡献分数')),
                ('daily_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='stock_models.strategydailyscore', verbose_name='所属每日分数')),
            ],
            options={
                'verbose_name': '策略分数构成',
                'verbose_name_plural': '策略分数构成',
                'db_table': 'strategy_score_component',
            },
        ),
        migrations.DeleteModel(
            name='PositionScoreDetail',
        ),
        migrations.RemoveField(
            model_name='dailypositionsnapshot',
            name='days_in_trade',
        ),
        migrations.RemoveField(
            model_name='dailypositionsnapshot',
            name='offensive_score',
        ),
        migrations.RemoveField(
            model_name='dailypositionsnapshot',
            name='position',
        ),
        migrations.RemoveField(
            model_name='dailypositionsnapshot',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='dailypositionsnapshot',
            name='score_details_json',
        ),
        migrations.RemoveField(
            model_name='dailypositionsnapshot',
            name='signal',
        ),
        migrations.AddIndex(
            model_name='strategyscorecomponent',
            index=models.Index(fields=['daily_score', 'score_type'], name='strategy_sc_daily_s_3e0880_idx'),
        ),
    ]
