# Generated by Django 5.0.1 on 2025-04-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0003_alter_fundflowcntths_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundflowcntths',
            options={'verbose_name': '板块资金流向统计', 'verbose_name_plural': '板块资金流向统计'},
        ),
        migrations.AlterUniqueTogether(
            name='fundflowcntths',
            unique_together={('ths_index', 'trade_time')},
        ),
        migrations.AddField(
            model_name='fundflowcntths',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='收盘价'),
        ),
        migrations.AddField(
            model_name='fundflowcntths',
            name='industry_index',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='板块指数'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='净额(亿元)'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='net_buy_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='流入资金(亿元)'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='net_sell_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='流出资金(亿元)'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='pct_change',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='行业涨跌幅(%)'),
        ),
        migrations.AlterField(
            model_name='fundflowcntths',
            name='pct_change_stock',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='领涨股涨跌幅(%)'),
        ),
        migrations.AddIndex(
            model_name='fundflowcntths',
            index=models.Index(fields=['ths_index'], name='fund_flow_c_ths_ind_214af5_idx'),
        ),
        migrations.AddIndex(
            model_name='fundflowcntths',
            index=models.Index(fields=['trade_time'], name='fund_flow_c_trade_t_fdd82b_idx'),
        ),
        migrations.AlterModelTable(
            name='fundflowcntths',
            table='fund_flow_cnt_ths',
        ),
        migrations.RemoveField(
            model_name='fundflowcntths',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='fundflowcntths',
            name='index_close',
        ),
    ]
