# Generated by Django 5.0.1 on 2025-08-05 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0003_remove_dailypositionsnapshot_entry_score_and_more'),
    ]
    operations = [
        migrations.DeleteModel(
            name='PositionScoreDetail',
        ),
    ]
