# Generated by Django 5.0.1 on 2025-04-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0003_northfundtrend_northsouthfundoverview_southfundtrend_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockccifib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockccifib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockcmffib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockcmffib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockdmifib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockdmifib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockichimokufib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockichimokufib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockmfifib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockmfifib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockmomfib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockmomfib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockrocfib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockrocfib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stocksarfib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stocksarfib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockvrocfib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockvrocfib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockvwapfib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockvwapfib',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockwrfib',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockwrfib',
            name='stock',
        ),
        migrations.CreateModel(
            name='IndexAmountMaFIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('time_level', models.CharField(db_index=True, max_length=10, verbose_name='K线周期')),
                ('amt_ma5', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(5)')),
                ('amt_ma8', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(8)')),
                ('amt_ma13', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(13)')),
                ('amt_ma21', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(21)')),
                ('amt_ma34', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(34)')),
                ('amt_ma55', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(55)')),
                ('amt_ma89', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(89)')),
                ('amt_ma144', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(144)')),
                ('amt_ma233', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='成交额MA(233)')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_ma_fib', to='stock_models.indexinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '成交额MA指标(斐波那契)',
                'verbose_name_plural': '成交额MA指标(斐波那契)',
                'db_table': 'index_amount_ma_fib',
            },
        ),
        migrations.CreateModel(
            name='IndexEmaFIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('time_level', models.CharField(db_index=True, max_length=10, verbose_name='K线周期')),
                ('ema5', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(5)')),
                ('ema8', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(8)')),
                ('ema13', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(13)')),
                ('ema21', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(21)')),
                ('ema34', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(34)')),
                ('ema55', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(55)')),
                ('ema89', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(89)')),
                ('ema144', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(144)')),
                ('ema233', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='EMA(233)')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ema_fib', to='stock_models.indexinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': 'EMA指标(斐波那契)',
                'verbose_name_plural': 'EMA指标(斐波那契)',
                'db_table': 'index_ema_fib',
            },
        ),
        migrations.DeleteModel(
            name='StockAmountRocFIB',
        ),
        migrations.DeleteModel(
            name='StockCciFIB',
        ),
        migrations.DeleteModel(
            name='StockCmfFIB',
        ),
        migrations.DeleteModel(
            name='StockDmiFIB',
        ),
        migrations.DeleteModel(
            name='StockIchimokuFIB',
        ),
        migrations.DeleteModel(
            name='StockMfiFIB',
        ),
        migrations.DeleteModel(
            name='StockMomFIB',
        ),
        migrations.DeleteModel(
            name='StockRocFIB',
        ),
        migrations.DeleteModel(
            name='StockSarFIB',
        ),
        migrations.DeleteModel(
            name='StockVrocFIB',
        ),
        migrations.DeleteModel(
            name='StockVwapFIB',
        ),
        migrations.DeleteModel(
            name='StockWrFIB',
        ),
        migrations.AddIndex(
            model_name='indexamountmafib',
            index=models.Index(fields=['index', 'time_level', 'trade_time'], name='index_amoun_index_i_5fb760_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indexamountmafib',
            unique_together={('index', 'trade_time', 'time_level')},
        ),
        migrations.AddIndex(
            model_name='indexemafib',
            index=models.Index(fields=['index', 'time_level', 'trade_time'], name='index_ema_f_index_i_af636f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indexemafib',
            unique_together={('index', 'trade_time', 'time_level')},
        ),
    ]
