# Generated by Django 5.0.1 on 2025-04-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0004_alter_fundflowcntths_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundflowcntths',
            old_name='close',
            new_name='close_price',
        ),
    ]
