# Generated by Django 5.0.1 on 2025-08-05 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0004_remove_positionscoredetail_snapshot_and_more'),
    ]
    operations = [
        migrations.DeleteModel(
            name='Playbook',
        ),
        migrations.DeleteModel(
            name='PositionTracker',
        ),
        migrations.DeleteModel(
            name='SignalPlaybookDetail',
        ),
        migrations.DeleteModel(
            name='TradingSignal',
        ),
        migrations.DeleteModel(
            name='DailyPositionSnapshot',
        ),
    ]
