# Generated by Django 5.0.1 on 2025-08-05 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0005_remove_signalplaybookdetail_playbook_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('name', models.CharField(help_text='战法/规则的唯一英文代码 (例如 TACTIC_LOCK_CHIP_RALLY_S)', max_length=255, primary_key=True, serialize=False)),
                ('cn_name', models.CharField(help_text='战法/规则的中文名称', max_length=255)),
                ('playbook_type', models.CharField(choices=[('OFFENSIVE', '进攻战法'), ('RISK', '风险剧本'), ('EXIT', '离场策略'), ('TRIGGER', '触发事件')], db_index=True, help_text='战法类型 (进攻/风险/离场/触发)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='战法的详细描述', null=True)),
                ('default_score', models.FloatField(default=0.0, help_text='配置文件中定义的默认分数')),
            ],
            options={
                'verbose_name': '策略战法库',
                'verbose_name_plural': '策略战法库',
                'db_table': 'strategy_playbook',
            },
        ),
        migrations.CreateModel(
            name='SignalPlaybookDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contributed_score', models.FloatField(help_text='此战法在当天实际贡献的分数')),
                ('playbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_models.playbook')),
            ],
            options={
                'verbose_name': '信号构成详情',
                'verbose_name_plural': '信号构成详情',
                'db_table': 'strategy_signal_playbook_detail',
            },
        ),
        migrations.CreateModel(
            name='StrategyDailyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日期')),
                ('strategy_name', models.CharField(db_index=True, max_length=100, verbose_name='策略名称')),
                ('offensive_score', models.IntegerField(default=0, verbose_name='总进攻分')),
                ('risk_score', models.IntegerField(default=0, verbose_name='总风险分')),
                ('final_score', models.FloatField(default=0.0, verbose_name='最终得分')),
                ('signal_type', models.CharField(max_length=20, verbose_name='信号类型')),
                ('score_details_json', models.JSONField(default=dict, verbose_name='分数构成详情(JSON)')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_daily_scores', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '策略每日分数',
                'verbose_name_plural': '策略每日分数',
                'db_table': 'strategy_daily_score',
                'ordering': ['-trade_date'],
                'unique_together': {('stock', 'trade_date', 'strategy_name')},
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trade_time', models.DateTimeField(db_index=True, help_text='信号生成时的K线收盘时间 (UTC)')),
                ('timeframe', models.CharField(db_index=True, help_text='信号所在的时间周期', max_length=10)),
                ('strategy_name', models.CharField(db_index=True, help_text='产生信号的策略名称', max_length=100)),
                ('signal_type', models.CharField(choices=[('BUY', '买入信号'), ('SELL', '卖出信号'), ('WARN', '风险预警'), ('HOLD', '无信号')], db_index=True, default='HOLD', help_text='最终信号类型', max_length=10)),
                ('entry_score', models.FloatField(default=0.0, help_text='当日计算出的总进攻分')),
                ('risk_score', models.FloatField(default=0.0, help_text='当日计算出的总风险分')),
                ('veto_votes', models.IntegerField(default=0, help_text='当日收到的总否决票数')),
                ('close_price', models.DecimalField(decimal_places=3, help_text='信号日收盘价', max_digits=10)),
                ('health_change_summary', models.JSONField(blank=True, default=dict, help_text='当日的攻防健康度变化摘要', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playbooks', models.ManyToManyField(help_text='构成此信号的所有战法/规则', related_name='trading_signals', through='stock_models.SignalPlaybookDetail', to='stock_models.playbook')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_signals', to='stock_models.stockinfo')),
            ],
            options={
                'verbose_name': '策略交易信号',
                'verbose_name_plural': '策略交易信号',
                'db_table': 'strategy_trading_signal',
                'ordering': ['-trade_time', 'stock'],
                'unique_together': {('stock', 'trade_time', 'timeframe', 'strategy_name')},
            },
        ),
        migrations.AddField(
            model_name='signalplaybookdetail',
            name='signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_models.tradingsignal'),
        ),
        migrations.CreateModel(
            name='PositionTracker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('WATCHING', '观察中'), ('HOLDING', '持仓中'), ('SOLD', '已平仓')], db_index=True, default='WATCHING', help_text='当前追踪状态', max_length=10)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=3, help_text='建仓或初次观察时的价格', max_digits=10, null=True)),
                ('entry_date', models.DateTimeField(blank=True, help_text='建仓或初次观察时的日期', null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=3, help_text='平仓价格', max_digits=10, null=True)),
                ('exit_date', models.DateTimeField(blank=True, help_text='平仓日期', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间')),
                ('stock', models.ForeignKey(help_text='关联的股票', on_delete=django.db.models.deletion.CASCADE, related_name='position_trackers', to='stock_models.stockinfo')),
                ('user', models.ForeignKey(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='position_trackers', to=settings.AUTH_USER_MODEL)),
                ('entry_signal', models.ForeignKey(blank=True, help_text="关联的建仓交易信号 (对于'观察中'状态可为空)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_positions', to='stock_models.tradingsignal')),
                ('exit_signal', models.ForeignKey(blank=True, help_text='关联的平仓交易信号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_positions', to='stock_models.tradingsignal')),
            ],
            options={
                'verbose_name': '策略持仓追踪器',
                'verbose_name_plural': '策略持仓追踪器',
                'db_table': 'strategy_position_tracker',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='快照日期')),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当日收盘价')),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='持仓盈亏')),
                ('profit_loss_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='持仓盈亏率(%)')),
                ('tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='stock_models.positiontracker', verbose_name='持仓追踪器')),
                ('daily_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_snapshots', to='stock_models.strategydailyscore', verbose_name='关联的每日分数')),
            ],
            options={
                'verbose_name': '每日持仓快照',
                'verbose_name_plural': '每日持仓快照',
                'db_table': 'strategy_daily_position_snapshot',
                'ordering': ['-snapshot_date'],
                'unique_together': {('tracker', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='StrategyScoreComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(db_index=True, max_length=255, verbose_name='信号名称(代码)')),
                ('signal_cn_name', models.CharField(max_length=255, verbose_name='信号中文名')),
                ('score_type', models.CharField(choices=[('positional', '阵地分'), ('dynamic', '动能分'), ('composite', '战法分'), ('trigger', '触发器分'), ('risk', '风险分'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='分数类型')),
                ('score_value', models.IntegerField(verbose_name='贡献分数')),
                ('daily_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='stock_models.strategydailyscore', verbose_name='所属每日分数')),
            ],
            options={
                'verbose_name': '策略分数构成',
                'verbose_name_plural': '策略分数构成',
                'db_table': 'strategy_score_component',
                'indexes': [models.Index(fields=['daily_score', 'score_type'], name='strategy_sc_daily_s_3e0880_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='signalplaybookdetail',
            unique_together={('signal', 'playbook')},
        ),
    ]
