# Generated by Django 5.0.1 on 2025-04-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0005_rename_close_fundflowcntths_close_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexdailybasic',
            old_name='trade_date',
            new_name='trade_time',
        ),
        migrations.AlterUniqueTogether(
            name='indexdailybasic',
            unique_together={('index', 'trade_time')},
        ),
    ]
