# Generated by Django 5.0.1 on 2025-04-28 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0006_rename_trade_date_indexdailybasic_trade_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swindustrydaily',
            unique_together={('index', 'trade_time')},
        ),
        migrations.AddField(
            model_name='swindustrydaily',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='swindustry',
            name='index_code',
            field=models.CharField(db_index=True, max_length=16, unique=True, verbose_name='指数代码'),
        ),
        migrations.RemoveField(
            model_name='swindustrydaily',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='swindustrydaily',
            name='ts_code',
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='index',
            field=models.ForeignKey(blank=True, db_column='ts_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sw_daily', to='stock_models.indexinfo', to_field='index_code', verbose_name='关联指数基础信息'),
        ),
        migrations.AlterField(
            model_name='swindustrymember',
            name='l3_industry',
            field=models.ForeignKey(db_column='l3_code', limit_choices_to={'level': 'L3'}, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='stock_models.swindustry', to_field='index_code', verbose_name='三级行业'),
        ),
        migrations.CreateModel(
            name='TradeCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('SSE', '上交所'), ('SZSE', '深交所'), ('CFFEX', '中金所'), ('SHFE', '上期所'), ('CZCE', '郑商所'), ('DCE', '大商所'), ('INE', '上能源')], default='SSE', max_length=10, verbose_name='交易所')),
                ('cal_date', models.DateField(db_index=True, verbose_name='日历日期')),
                ('is_open', models.BooleanField(verbose_name='是否交易')),
                ('pretrade_date', models.DateField(blank=True, null=True, verbose_name='上一个交易日')),
            ],
            options={
                'verbose_name': '交易日历',
                'verbose_name_plural': '交易日历',
                'db_table': 'trade_calendar',
                'ordering': ['-cal_date'],
                'unique_together': {('exchange', 'cal_date')},
            },
        ),
        
    ]
