# Generated by Django 5.0.1 on 2025-04-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0006_indexadl_indexkcfib_indexpivotpoints_indexsmafib_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='circulating_shares',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='流通股本'),
        ),
    ]
