# Generated by Django 5.0.1 on 2025-08-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0006_playbook_signalplaybookdetail_strategydailyscore_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='strategydailyscore',
            name='composite_score',
            field=models.IntegerField(default=0, verbose_name='战法分'),
        ),
        migrations.AddField(
            model_name='strategydailyscore',
            name='dynamic_score',
            field=models.IntegerField(default=0, verbose_name='动能分'),
        ),
        migrations.AddField(
            model_name='strategydailyscore',
            name='positional_score',
            field=models.IntegerField(default=0, verbose_name='阵地分'),
        ),
    ]
