# Generated by Django 5.0.1 on 2025-08-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0007_strategydailyscore_composite_score_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='positiontracker',
            name='quantity',
            field=models.PositiveIntegerField(default=100, help_text='持仓数量 (股)'),
        ),
    ]
