# Generated by Django 5.0.1 on 2025-04-28 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0007_alter_swindustrydaily_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DcMember',
            new_name='DcIndexMember',
        ),
        migrations.RenameModel(
            old_name='ThsMember',
            new_name='ThsIndexMember',
        ),
        migrations.AlterUniqueTogether(
            name='dcindex',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dcindex',
            name='exchange',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='交易所'),
        ),
        migrations.AddField(
            model_name='dcindex',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='指数类型'),
        ),
        migrations.AlterField(
            model_name='dcindex',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='概念名称'),
        ),
        migrations.AlterModelTable(
            name='dcindexmember',
            table='dc_index_member',
        ),
        migrations.AlterModelTable(
            name='thsindexmember',
            table='ths_index_member',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='down_num',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='leading',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='leading_pct',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='pct_change',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='total_mv',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='trade_time',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='turnover_rate',
        ),
        migrations.RemoveField(
            model_name='dcindex',
            name='up_num',
        ),
        migrations.CreateModel(
            name='DcIndexDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_code', models.CharField(max_length=20, unique=True, verbose_name='概念代码')),
                ('trade_time', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('name', models.CharField(max_length=50, verbose_name='概念名称')),
                ('leading', models.CharField(max_length=50, verbose_name='领涨股票名称')),
                ('pct_change', models.FloatField(verbose_name='涨跌幅')),
                ('leading_pct', models.FloatField(verbose_name='领涨股票涨跌幅')),
                ('total_mv', models.FloatField(verbose_name='总市值(万元)')),
                ('turnover_rate', models.FloatField(verbose_name='换手率')),
                ('up_num', models.IntegerField(verbose_name='上涨家数')),
                ('down_num', models.IntegerField(verbose_name='下降家数')),
                ('stock', models.ForeignKey(db_column='leading_code', on_delete=django.db.models.deletion.CASCADE, related_name='dc_index_daily', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '东方财富板块指数行情',
                'verbose_name_plural': '东方财富板块指数行情',
                'db_table': 'dc_index_daily',
                'unique_together': {('ts_code', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='ThsIndexDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(verbose_name='交易日')),
                ('close', models.FloatField(verbose_name='收盘点位')),
                ('open', models.FloatField(verbose_name='开盘点位')),
                ('high', models.FloatField(verbose_name='最高点位')),
                ('low', models.FloatField(verbose_name='最低点位')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='昨日收盘点')),
                ('avg_price', models.FloatField(blank=True, null=True, verbose_name='平均价')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='涨跌点位')),
                ('pct_change', models.FloatField(verbose_name='涨跌幅')),
                ('vol', models.FloatField(verbose_name='成交量')),
                ('turnover_rate', models.FloatField(blank=True, null=True, verbose_name='换手率')),
                ('total_mv', models.FloatField(blank=True, null=True, verbose_name='总市值')),
                ('float_mv', models.FloatField(blank=True, null=True, verbose_name='流通市值')),
                ('pe_ttm', models.FloatField(blank=True, null=True, verbose_name='市盈率TTM')),
                ('pb_mrq', models.FloatField(blank=True, null=True, verbose_name='市净率MRQ')),
                ('ths_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stock_models.thsindex', verbose_name='所属指数')),
            ],
            options={
                'verbose_name': '同花顺板块指数行情',
                'verbose_name_plural': '同花顺板块指数行情',
                'db_table': 'ths_index_daily',
                'ordering': ['-trade_time'],
                'unique_together': {('ths_index', 'trade_time')},
            },
        ),
    ]
