# Generated by Django 5.0.1 on 2025-04-28 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0008_rename_dcmember_dcindexmember_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dcindexmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dcindexmember',
            name='dc_index',
        ),
        migrations.RemoveField(
            model_name='dcindexmember',
            name='stock',
        ),
        migrations.DeleteModel(
            name='DcIndexDaily',
        ),
        migrations.DeleteModel(
            name='DcIndexMember',
        ),
    ]
