# Generated by Django 5.0.1 on 2025-08-06 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0008_positiontracker_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='dailypositionsnapshot',
            options={'ordering': ['-snapshot_date']},
        ),
        migrations.AlterUniqueTogether(
            name='positiontracker',
            unique_together={('user', 'stock')},
        ),
        migrations.AddField(
            model_name='dailypositionsnapshot',
            name='quantity_at_snapshot',
            field=models.PositiveIntegerField(default=0, help_text='快照当日的持仓数量'),
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='average_cost',
            field=models.DecimalField(decimal_places=3, default=0, help_text='持仓平均成本', max_digits=10),
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0, help_text='当前持仓数量 (股)'),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='daily_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_snapshots', to='stock_models.strategydailyscore'),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='profit_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='profit_loss_pct',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='snapshot_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailypositionsnapshot',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='stock_models.positiontracker'),
        ),
        migrations.AlterField(
            model_name='positiontracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='positiontracker',
            name='status',
            field=models.CharField(choices=[('WATCHING', '观察中'), ('HOLDING', '持仓中')], db_index=True, default='WATCHING', max_length=10),
        ),
        migrations.AlterField(
            model_name='positiontracker',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_trackers', to='stock_models.stockinfo'),
        ),
        migrations.AlterField(
            model_name='positiontracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='positiontracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_trackers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('BUY', '买入'), ('SELL', '卖出')], db_index=True, max_length=4)),
                ('quantity', models.PositiveIntegerField(help_text='本次交易数量 (股)')),
                ('price', models.DecimalField(decimal_places=3, help_text='本次交易价格', max_digits=10)),
                ('transaction_date', models.DateTimeField(help_text='交易日期和时间')),
                ('commission', models.DecimalField(decimal_places=3, default=0, help_text='手续费', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracker', models.ForeignKey(help_text='关联的持仓追踪器', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock_models.positiontracker')),
            ],
            options={
                'verbose_name': '交易流水',
                'verbose_name_plural': '交易流水',
                'db_table': 'strategy_transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.RemoveField(
            model_name='positiontracker',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='positiontracker',
            name='entry_price',
        ),
        migrations.RemoveField(
            model_name='positiontracker',
            name='entry_signal',
        ),
        migrations.RemoveField(
            model_name='positiontracker',
            name='exit_date',
        ),
        migrations.RemoveField(
            model_name='positiontracker',
            name='exit_price',
        ),
        migrations.RemoveField(
            model_name='positiontracker',
            name='exit_signal',
        ),
        migrations.RemoveField(
            model_name='positiontracker',
            name='quantity',
        ),
    ]
