# Generated by Django 5.0.1 on 2025-04-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0009_alter_dcindexmember_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DcIndexDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('name', models.CharField(max_length=50, verbose_name='概念名称')),
                ('leading', models.CharField(max_length=50, verbose_name='领涨股票名称')),
                ('pct_change', models.FloatField(verbose_name='涨跌幅')),
                ('leading_pct', models.FloatField(verbose_name='领涨股票涨跌幅')),
                ('total_mv', models.FloatField(verbose_name='总市值(万元)')),
                ('turnover_rate', models.FloatField(verbose_name='换手率')),
                ('up_num', models.IntegerField(verbose_name='上涨家数')),
                ('down_num', models.IntegerField(verbose_name='下降家数')),
                ('dc_index', models.ForeignKey(blank=True, db_column='ts_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stock_models.dcindex', to_field='ts_code', verbose_name='东方财富概念板块')),
                ('stock', models.ForeignKey(db_column='leading_code', on_delete=django.db.models.deletion.CASCADE, related_name='dc_index_daily', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '东方财富板块指数行情',
                'verbose_name_plural': '东方财富板块指数行情',
                'db_table': 'dc_index_daily',
                'unique_together': {('dc_index', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='DcIndexMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(blank=True, null=True, verbose_name='交易日期')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='股票名称')),
                ('dc_index', models.ForeignKey(blank=True, db_column='ts_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dc_member', to='stock_models.dcindex', verbose_name='指数')),
                ('stock', models.ForeignKey(db_column='con_code', on_delete=django.db.models.deletion.CASCADE, related_name='dc_member', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '东方财富板块成分',
                'verbose_name_plural': '东方财富板块成分',
                'db_table': 'dc_index_member',
                'unique_together': {('trade_time', 'dc_index', 'stock')},
            },
        ),
    ]
