# Generated by Django 5.0.1 on 2025-04-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0010_dcindexdaily_dcindexmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundflowdailydc',
            name='net_d5_amount',
        ),
        migrations.AddField(
            model_name='fundflowdailydc',
            name='buy_elg_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='今日超大单净流入额（万元）'),
        ),
        migrations.AddField(
            model_name='fundflowdailydc',
            name='buy_elg_amount_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='今日超大单净流入占比（%）'),
        ),
        migrations.AddField(
            model_name='fundflowdailydc',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='最新价'),
        ),
        migrations.AddField(
            model_name='fundflowdailydc',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='fundflowdailydc',
            name='buy_lg_amount_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='今日大单净流入占比（%）'),
        ),
        migrations.AlterField(
            model_name='fundflowdailydc',
            name='buy_md_amount_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='今日中单净流入占比（%）'),
        ),
        migrations.AlterField(
            model_name='fundflowdailydc',
            name='buy_sm_amount_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='今日小单净流入占比（%）'),
        ),
        migrations.AlterField(
            model_name='fundflowdailydc',
            name='net_amount_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='今日主力净流入净占比（%）'),
        ),
    ]
