# Generated by Django 5.0.1 on 2025-04-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0011_remove_fundflowdailydc_net_d5_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockscoreanalysis',
            name='div_macd_hist_hidden_bearish',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='MACD隐藏看跌背离'),
        ),
        migrations.AddField(
            model_name='stockscoreanalysis',
            name='div_rsi_regular_bullish',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='RSI常规看涨背离'),
        ),
        migrations.AddField(
            model_name='stockscoreanalysis',
            name='volume_spike',
            field=models.IntegerField(blank=True, null=True, verbose_name='量能放量信号'),
        ),
    ]
