# Generated by Django 5.0.1 on 2025-08-15 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0011_stockdailybasic_bj_stockdailybasic_cy_and_more'),
    ]
    operations = [
        migrations.CreateModel(
            name='AtomicSignalPerformance',
            fields=[
                ('signal_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='信号名称(代码)')),
                ('signal_cn_name', models.CharField(max_length=255, verbose_name='信号中文名')),
                ('signal_type', models.CharField(max_length=20, verbose_name='信号类型')),
                ('total_triggers', models.IntegerField(verbose_name='总触发次数')),
                ('successes', models.IntegerField(verbose_name='成功次数')),
                ('win_rate_pct', models.FloatField(verbose_name='胜率(%)')),
                ('avg_max_profit_pct', models.FloatField(verbose_name='平均最大涨幅(%)')),
                ('avg_max_drawdown_pct', models.FloatField(verbose_name='平均最大回撤(%)')),
                ('avg_exit_days', models.FloatField(verbose_name='平均退出天数')),
                ('last_analyzed', models.DateTimeField(auto_now=True, verbose_name='最后分析时间')),
            ],
            options={
                'verbose_name': '原子信号性能',
                'verbose_name_plural': '原子信号性能',
                'db_table': 'strategy_atomic_signal_performance',
                'ordering': ['-win_rate_pct'],
            },
        ),
        migrations.CreateModel(
            name='StrategyDailyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(db_index=True, max_length=255, verbose_name='信号名称(代码)')),
                ('signal_cn_name', models.CharField(max_length=255, verbose_name='信号中文名')),
                ('signal_type', models.CharField(choices=[('State', '原子状态'), ('Trigger', '触发事件'), ('Unknown', '未知')], default='Unknown', max_length=20, verbose_name='信号类型')),
                ('daily_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atomic_states_and_triggers', to='stock_models.strategydailyscore', verbose_name='所属每日分数')),
            ],
            options={
                'verbose_name': '策略每日状态',
                'verbose_name_plural': '策略每日状态',
                'db_table': 'strategy_daily_state',
                'indexes': [models.Index(fields=['signal_name', 'signal_type'], name='strategy_da_signal__894e9e_idx')],
                'unique_together': {('daily_score', 'signal_name')},
            },
        ),
    ]
