# Generated by Django 5.0.1 on 2025-08-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0012_atomicsignalperformance_strategydailystate'),
    ]
    operations = [
        migrations.AddField(
            model_name='strategydailyscore',
            name='trade_action',
            field=models.CharField(choices=[('INITIAL_ENTRY', '首次建仓'), ('ADD_POSITION', '加仓'), ('REDUCE_POSITION', '减仓'), ('PROFIT_EXIT', '止盈清仓'), ('STOP_LOSS_EXIT', '止损清仓'), ('RISK_EXIT', '风险清仓'), ('TREND_BROKEN_EXIT', '趋势破位清仓'), ('HOLD', '持仓观望'), ('AVOID', '规避'), ('PROCEED_WITH_CAUTION', '谨慎持仓'), ('FORCE_ATTACK', '强力进攻'), ('NO_SIGNAL', '无信号')], default='NO_SIGNAL', help_text='模拟层根据策略规则执行的交易动作 (例如: INITIAL_ENTRY, PROFIT_EXIT, REDUCE_POSITION)', max_length=50, verbose_name='模拟交易动作'),
        ),
        migrations.AlterField(
            model_name='playbook',
            name='playbook_type',
            field=models.CharField(choices=[('OFFENSIVE', '进攻战法'), ('RISK', '风险剧本'), ('EXIT', '离场策略'), ('TRIGGER', '触发事件'), ('CONTEXT', '环境信号'), ('UNKNOWN', '未知类型')], db_index=True, help_text='战法类型 (进攻/风险/离场/触发)', max_length=20),
        ),
    ]
