# Generated by Django 5.0.1 on 2025-04-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0012_stockscoreanalysis_div_macd_hist_hidden_bearish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcyqchips',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='stockcyqperf',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
    ]
