# Generated by Django 5.0.1 on 2025-09-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0013_strategydailyscore_trade_action_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='值越小越集中。', max_digits=12, null=True, verbose_name='70%筹码集中度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='负值表示筹码趋于集中。', max_digits=18, null=True, verbose_name='70%集中度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_90pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='中期趋势。', max_digits=18, null=True, verbose_name='90%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_90pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='长期趋势。', max_digits=18, null=True, verbose_name='90%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='值越小越集中。', max_digits=12, null=True, verbose_name='70%筹码集中度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='负值表示筹码趋于集中。', max_digits=18, null=True, verbose_name='70%集中度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_90pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='中期趋势。', max_digits=18, null=True, verbose_name='90%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_90pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='长期趋势。', max_digits=18, null=True, verbose_name='90%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='值越小越集中。', max_digits=12, null=True, verbose_name='70%筹码集中度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='负值表示筹码趋于集中。', max_digits=18, null=True, verbose_name='70%集中度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_90pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='中期趋势。', max_digits=18, null=True, verbose_name='90%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_90pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='长期趋势。', max_digits=18, null=True, verbose_name='90%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='值越小越集中。', max_digits=12, null=True, verbose_name='70%筹码集中度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='负值表示筹码趋于集中。', max_digits=18, null=True, verbose_name='70%集中度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_90pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='中期趋势。', max_digits=18, null=True, verbose_name='90%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_90pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='长期趋势。', max_digits=18, null=True, verbose_name='90%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='值越小越集中。', max_digits=12, null=True, verbose_name='70%筹码集中度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='负值表示筹码趋于集中。', max_digits=18, null=True, verbose_name='70%集中度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_90pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='中期趋势。', max_digits=18, null=True, verbose_name='90%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_90pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='长期趋势。', max_digits=18, null=True, verbose_name='90%集中度55日斜率'),
        ),
    ]
