# Generated by Django 5.0.1 on 2025-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0013_alter_stockcyqchips_trade_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thsindexdaily',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘点位'),
        ),
        migrations.AlterField(
            model_name='thsindexdaily',
            name='high',
            field=models.FloatField(blank=True, null=True, verbose_name='最高点位'),
        ),
        migrations.AlterField(
            model_name='thsindexdaily',
            name='low',
            field=models.FloatField(blank=True, null=True, verbose_name='最低点位'),
        ),
        migrations.AlterField(
            model_name='thsindexdaily',
            name='open',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘点位'),
        ),
        migrations.AlterField(
            model_name='thsindexdaily',
            name='pct_change',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='thsindexdaily',
            name='vol',
            field=models.FloatField(blank=True, null=True, verbose_name='成交量'),
        ),
    ]
