# Generated by Django 5.0.1 on 2025-09-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0014_advancedchipmetrics_bj_concentration_70pct_and_more'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='advancedchipmetrics_bj',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标-北交(V6.0-衍生固化)', 'verbose_name_plural': '高级筹码指标-北交(V6.0-衍生固化)'},
        ),
        migrations.AlterModelOptions(
            name='advancedchipmetrics_cy',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标-创业(V6.0-衍生固化)', 'verbose_name_plural': '高级筹码指标-创业(V6.0-衍生固化)'},
        ),
        migrations.AlterModelOptions(
            name='advancedchipmetrics_kc',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标-科创(V6.0-衍生固化)', 'verbose_name_plural': '高级筹码指标-科创(V6.0-衍生固化)'},
        ),
        migrations.AlterModelOptions(
            name='advancedchipmetrics_sh',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标-上海(V6.0-衍生固化)', 'verbose_name_plural': '高级筹码指标-上海(V6.0-衍生固化)'},
        ),
        migrations.AlterModelOptions(
            name='advancedchipmetrics_sz',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标-深圳(V6.0-衍生固化)', 'verbose_name_plural': '高级筹码指标-深圳(V6.0-衍生固化)'},
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_bj',
            name='stock_advan_stock_i_3177c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_bj',
            name='stock_advan_trade_t_eddac7_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_cy',
            name='stock_advan_stock_i_6045cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_cy',
            name='stock_advan_trade_t_515b32_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_kc',
            name='stock_advan_stock_i_3942de_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_kc',
            name='stock_advan_trade_t_9f326f_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_sh',
            name='stock_advan_stock_i_8ec5e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_sh',
            name='stock_advan_trade_t_6d1402_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_sz',
            name='stock_advan_stock_i_745648_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics_sz',
            name='stock_advan_trade_t_187558_idx',
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='avg_cost_long_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='长期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='avg_cost_short_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='短期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_90pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_90pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_90pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='loser_rate_long_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='长期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='loser_rate_long_term_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='loser_rate_long_term_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='loser_rate_short_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='短期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_control_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_control_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_control_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_control_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_control_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_stability_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_stability_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_stability_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_strength_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_strength_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='pressure_above_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='pressure_above_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='support_below_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='support_below_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='total_loser_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='总套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_losers_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_losers_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_losers_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_losers_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_winners_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_winners_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_winners_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_winners_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_winners_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_winners_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='winner_profit_margin_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='winner_profit_margin_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='winner_profit_margin_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='winner_profit_margin_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='winner_profit_margin_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='avg_cost_long_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='长期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='avg_cost_short_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='短期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_90pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_90pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_90pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='loser_rate_long_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='长期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='loser_rate_long_term_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='loser_rate_long_term_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='loser_rate_short_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='短期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_control_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_control_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_control_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_control_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_control_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_stability_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_stability_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_stability_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_strength_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_strength_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='pressure_above_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='pressure_above_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='support_below_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='support_below_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='total_loser_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='总套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_losers_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_losers_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_losers_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_losers_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_winners_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_winners_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_winners_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_winners_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_winners_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_winners_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='winner_profit_margin_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='winner_profit_margin_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='winner_profit_margin_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='winner_profit_margin_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='winner_profit_margin_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='avg_cost_long_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='长期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='avg_cost_short_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='短期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_90pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_90pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_90pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='loser_rate_long_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='长期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='loser_rate_long_term_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='loser_rate_long_term_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='loser_rate_short_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='短期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_control_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_control_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_control_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_control_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_control_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_stability_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_stability_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_stability_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_strength_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_strength_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='pressure_above_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='pressure_above_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='support_below_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='support_below_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='total_loser_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='总套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_losers_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_losers_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_losers_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_losers_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_winners_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_winners_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_winners_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_winners_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_winners_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_winners_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='winner_profit_margin_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='winner_profit_margin_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='winner_profit_margin_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='winner_profit_margin_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='winner_profit_margin_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='avg_cost_long_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='长期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='avg_cost_short_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='短期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_90pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_90pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_90pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='loser_rate_long_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='长期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='loser_rate_long_term_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='loser_rate_long_term_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='loser_rate_short_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='短期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_control_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_control_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_control_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_control_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_control_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_stability_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_stability_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_stability_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_strength_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_strength_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='pressure_above_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='pressure_above_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='support_below_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='support_below_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='total_loser_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='总套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_losers_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_losers_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_losers_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_losers_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_winners_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_winners_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_winners_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_winners_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_winners_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_winners_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='winner_profit_margin_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='winner_profit_margin_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='winner_profit_margin_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='winner_profit_margin_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='winner_profit_margin_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='avg_cost_long_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='长期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='avg_cost_short_term',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='短期持仓者平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_90pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_90pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_90pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='loser_rate_long_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='长期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='loser_rate_long_term_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='loser_rate_long_term_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='loser_rate_short_term',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='短期套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_control_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_control_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_control_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_control_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_control_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_stability_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_stability_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_stability_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_strength_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_strength_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='pressure_above_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='pressure_above_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='support_below_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='support_below_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='total_loser_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='总套牢盘(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_losers_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_losers_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_losers_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_losers_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_winners_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_winners_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_winners_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_winners_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_winners_ratio_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_winners_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='winner_profit_margin_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='winner_profit_margin_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='winner_profit_margin_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='winner_profit_margin_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='winner_profit_margin_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫5日斜率'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_bj',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_advan_stock_i_811238_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_cy',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_advan_stock_i_6fb10d_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_kc',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_advan_stock_i_7a49f3_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_sh',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_advan_stock_i_4f0ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_sz',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_advan_stock_i_7d0824_idx'),
        ),
    ]
