# Generated by Django 5.0.1 on 2025-05-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0014_alter_thsindexdaily_close_alter_thsindexdaily_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexdaily',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='成交额(千元)'),
        ),
        migrations.AlterField(
            model_name='indexdaily',
            name='change',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌点'),
        ),
        migrations.AlterField(
            model_name='indexdaily',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘点位'),
        ),
        migrations.AlterField(
            model_name='indexdaily',
            name='high',
            field=models.FloatField(blank=True, null=True, verbose_name='最高点位'),
        ),
        migrations.AlterField(
            model_name='indexdaily',
            name='low',
            field=models.FloatField(blank=True, null=True, verbose_name='最低点位'),
        ),
        migrations.AlterField(
            model_name='indexdaily',
            name='open',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘点位'),
        ),
        migrations.AlterField(
            model_name='indexdaily',
            name='pct_chg',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='indexdaily',
            name='vol',
            field=models.FloatField(blank=True, null=True, verbose_name='成交量(手)'),
        ),
        migrations.DeleteModel(
            name='ThsDaily',
        ),
    ]
