# Generated by Django 5.0.1 on 2025-06-07 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0015_alter_indexdaily_amount_alter_indexdaily_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAnalysisResultTrendFollowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='该分析结果对应的数据时间戳', verbose_name='分析时间戳')),
                ('score', models.FloatField(blank=True, help_text='最终综合信号分数 (combined_signal)', null=True, verbose_name='组合信号分')),
                ('rule_signal', models.FloatField(blank=True, help_text='基于规则的信号分数 (final_rule_signal)', null=True, verbose_name='规则信号分')),
                ('lstm_signal', models.FloatField(blank=True, help_text='Transformer模型生成的信号分数 (transformer_signal)', null=True, verbose_name='Transformer信号分')),
                ('base_score_raw', models.FloatField(blank=True, help_text='未调整前的基础趋势分数 (base_score_raw)', null=True, verbose_name='原始基础分')),
                ('base_score_volume_adjusted', models.FloatField(blank=True, help_text='经过量能调整后的基础趋势分数 (ADJUSTED_SCORE)', null=True, verbose_name='量能调整基础分')),
                ('alignment_signal', models.FloatField(blank=True, help_text='EMA排列状态信号 (alignment_signal)', null=True, verbose_name='EMA排列信号')),
                ('long_term_context', models.CharField(blank=True, help_text='长期趋势的文字描述 (long_term_context)', max_length=50, null=True, verbose_name='长期趋势背景')),
                ('adx_strength_signal', models.FloatField(blank=True, help_text='结合方向的ADX强度信号 (adx_strength_signal)', null=True, verbose_name='ADX强度信号')),
                ('stoch_signal', models.FloatField(blank=True, help_text='随机指标信号 (stoch_signal)', null=True, verbose_name='STOCH信号')),
                ('div_has_bearish_divergence', models.BooleanField(default=False, help_text='是否检测到顶背离 (HAS_BEARISH_DIVERGENCE)', verbose_name='存在顶背离')),
                ('div_has_bullish_divergence', models.BooleanField(default=False, help_text='是否检测到底背离 (HAS_BULLISH_DIVERGENCE)', verbose_name='存在底背离')),
                ('volume_spike_signal', models.FloatField(blank=True, help_text='量能异动信号 (VOL_SPIKE_SIGNAL)', null=True, verbose_name='量能异动信号')),
                ('close_price', models.FloatField(blank=True, help_text='分析时的收盘价格', null=True, verbose_name='收盘价')),
                ('current_trend', models.CharField(blank=True, help_text='当前趋势的文字方向 (如: 看涨, 看跌, 中性)', max_length=20, null=True, verbose_name='当前趋势方向')),
                ('trend_strength', models.CharField(blank=True, help_text='当前趋势的强度 (如: 强劲, 温和, 不明)', max_length=20, null=True, verbose_name='趋势强度')),
                ('trend_duration_bullish', models.IntegerField(blank=True, help_text='看涨趋势持续的周期数', null=True, verbose_name='看涨持续周期')),
                ('trend_duration_bearish', models.IntegerField(blank=True, help_text='看跌趋势持续的周期数', null=True, verbose_name='看跌持续周期')),
                ('trend_duration_text_bullish', models.CharField(blank=True, help_text='看涨趋势持续时间的文字描述', max_length=100, null=True, verbose_name='看涨持续文本')),
                ('trend_duration_text_bearish', models.CharField(blank=True, help_text='看跌趋势持续时间的文字描述', max_length=100, null=True, verbose_name='看跌持续文本')),
                ('trend_duration_status', models.CharField(blank=True, help_text='趋势持续的总体状态 (如: 短, 中, 长)', max_length=20, null=True, verbose_name='趋势持续状态')),
                ('operation_advice', models.TextField(blank=True, help_text='基于分析结果的操作建议', null=True, verbose_name='操作建议')),
                ('risk_warning', models.TextField(blank=True, help_text='基于分析结果的风险提示', null=True, verbose_name='风险提示')),
                ('chinese_interpretation', models.TextField(blank=True, help_text='详细的中文分析解读', null=True, verbose_name='中文解读')),
                ('signal_impact_records_json', models.JSONField(blank=True, help_text='信号影响的详细记录 (JSON 格式)', null=True, verbose_name='信号影响记录')),
                ('signal_contribution_summary_json', models.JSONField(blank=True, help_text='各信号对信心分贡献的汇总 (JSON 格式)', null=True, verbose_name='信号贡献汇总')),
                ('weighted_confidence_score', models.FloatField(blank=True, help_text='加权计算后的综合信心分数', null=True, verbose_name='加权信心分数')),
                ('confidence_score', models.FloatField(blank=True, help_text='未加权计算的综合信心分数', null=True, verbose_name='综合信心分数')),
                ('normalized_confidence', models.FloatField(blank=True, help_text='归一化后的综合信心分数 (范围 -1.0 到 1.0)', null=True, verbose_name='归一化信心分数')),
                ('raw_analysis_data', models.JSONField(blank=True, help_text='完整的原始分析结果字典 (JSON 格式)', null=True, verbose_name='原始分析数据')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_analysis_result_trend_following', to='stock_models.stockinfo', verbose_name='股票代码')),
            ],
            options={
                'verbose_name': '股票趋势分析结果',
                'verbose_name_plural': '股票趋势分析结果',
                'db_table': 'stock_analysis_result_trend_following',
                'ordering': ['stock', '-timestamp'],
                'unique_together': {('stock', 'timestamp')},
            },
        ),
    ]
