# Generated by Django 5.0.1 on 2025-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0016_stockanalysisresulttrendfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockanalysisresulttrendfollowing',
            name='is_bottom_breakout',
            field=models.BooleanField(default=False, help_text='是否出现底部起涨信号', verbose_name='底部起涨信号'),
        ),
        migrations.AddField(
            model_name='stockanalysisresulttrendfollowing',
            name='is_in_bottom',
            field=models.BooleanField(default=False, help_text='当前是否处于底部区间', verbose_name='处于底部区间'),
        ),
    ]
