# Generated by Django 5.0.1 on 2025-09-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0016_advancedfundflowmetrics_bj_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='accel_13d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='accel_21d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='accel_5d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='accel_13d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='accel_21d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='accel_5d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='accel_13d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='accel_21d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='accel_5d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='accel_13d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='accel_21d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='accel_5d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='accel_13d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='accel_21d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='accel_5d_flow_divergence_mf_vs_retail',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度5日加速度'),
        ),
    ]
