# Generated by Django 5.0.1 on 2025-06-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0017_stockanalysisresulttrendfollowing_is_bottom_breakout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockanalysisresulttrendfollowing',
            old_name='is_bottom_breakout',
            new_name='bottom_volume_breakout_signal',
        ),
        migrations.RenameField(
            model_name='stockanalysisresulttrendfollowing',
            old_name='is_in_bottom',
            new_name='volume_breakout_signal',
        ),
    ]
