# Generated by Django 5.0.1 on 2025-09-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0017_advancedfundflowmetrics_bj_accel_13d_flow_divergence_mf_vs_retail_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主力主动买盘 / (主力主动买盘 + 主力主动卖盘)，衡量信念强度', max_digits=10, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='综合多方数据的超大单净流入', max_digits=20, null=True, verbose_name='共识-超大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主力主动买盘 / (主力主动买盘 + 主力主动卖盘)，衡量信念强度', max_digits=10, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='综合多方数据的超大单净流入', max_digits=20, null=True, verbose_name='共识-超大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主力主动买盘 / (主力主动买盘 + 主力主动卖盘)，衡量信念强度', max_digits=10, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='综合多方数据的超大单净流入', max_digits=20, null=True, verbose_name='共识-超大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主力主动买盘 / (主力主动买盘 + 主力主动卖盘)，衡量信念强度', max_digits=10, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='综合多方数据的超大单净流入', max_digits=20, null=True, verbose_name='共识-超大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主力主动买盘 / (主力主动买盘 + 主力主动卖盘)，衡量信念强度', max_digits=10, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='综合多方数据的超大单净流入', max_digits=20, null=True, verbose_name='共识-超大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-超大单净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-超大单净流入89日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_13d_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_144d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入144日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_21d_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_34d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入34日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_55d_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_5d_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=22, null=True, verbose_name='共识-散户净流入5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_sum_89d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-散户净流入89日累计'),
        ),
    ]
