# Generated by Django 5.0.1 on 2025-09-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0018_advancedfundflowmetrics_bj_main_force_flow_intensity_ratio_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率5日斜率'),
        ),
    ]
