# Generated by Django 5.0.1 on 2025-09-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0019_advancedfundflowmetrics_bj_main_force_flow_intensity_ratio_slope_13d_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='cost_divergence_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='cost_divergence_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='cost_divergence_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='cost_divergence_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='cost_divergence_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='cost_divergence_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='cost_divergence_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='cost_divergence_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='cost_divergence_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='cost_divergence_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='cost_divergence_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='cost_divergence_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='cost_divergence_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='cost_divergence_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='cost_divergence_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='cost_divergence_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='cost_divergence_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='cost_divergence_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='cost_divergence_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='cost_divergence_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='cost_divergence_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='cost_divergence_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='cost_divergence_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='cost_divergence_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='cost_divergence_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='cost_divergence_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='cost_divergence_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='cost_divergence_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='cost_divergence_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='cost_divergence_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度5日斜率'),
        ),
    ]
