# Generated by Django 5.0.1 on 2025-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0020_advancedchipmetrics_bj_cost_divergence_accel_21d_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_90pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_90pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='cost_divergence_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='cost_divergence_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='loser_rate_long_term_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='loser_rate_long_term_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_control_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_control_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_cost_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_cost_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_stability_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_stability_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_strength_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_strength_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='pressure_above_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='pressure_above_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='support_below_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='support_below_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_losers_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_losers_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_winners_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='turnover_from_winners_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='winner_profit_margin_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='winner_profit_margin_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_90pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_90pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='cost_divergence_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='cost_divergence_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='loser_rate_long_term_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='loser_rate_long_term_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_control_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_control_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_cost_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_cost_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_stability_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_stability_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_strength_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_strength_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='pressure_above_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='pressure_above_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='support_below_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='support_below_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_losers_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_losers_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_winners_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='turnover_from_winners_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='winner_profit_margin_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='winner_profit_margin_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_90pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_90pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='cost_divergence_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='cost_divergence_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='loser_rate_long_term_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='loser_rate_long_term_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_control_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_control_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_cost_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_cost_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_stability_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_stability_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_strength_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_strength_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='pressure_above_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='pressure_above_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='support_below_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='support_below_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_losers_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_losers_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_winners_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='turnover_from_winners_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='winner_profit_margin_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='winner_profit_margin_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_90pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_90pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='cost_divergence_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='cost_divergence_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='loser_rate_long_term_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='loser_rate_long_term_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_control_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_control_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_cost_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_cost_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_stability_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_stability_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_strength_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_strength_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='pressure_above_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='pressure_above_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='support_below_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='support_below_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_losers_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_losers_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_winners_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='turnover_from_winners_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='winner_profit_margin_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='winner_profit_margin_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_90pct_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_90pct_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='90%集中度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='cost_divergence_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='cost_divergence_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='成本发散度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='loser_rate_long_term_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='loser_rate_long_term_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='长期套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_control_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_control_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_cost_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_cost_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_stability_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_stability_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_strength_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_strength_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='主次峰强度比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='pressure_above_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='pressure_above_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='上方套牢盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='support_below_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='support_below_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='下方支撑盘1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_losers_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_losers_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='套牢盘割肉占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_winners_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='turnover_from_winners_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘抛压占比1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='winner_profit_margin_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='winner_profit_margin_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='获利盘安全垫1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='flow_divergence_mf_vs_retail_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='flow_divergence_mf_vs_retail_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_xl_amount_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='flow_divergence_mf_vs_retail_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='flow_divergence_mf_vs_retail_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_xl_amount_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='flow_divergence_mf_vs_retail_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='flow_divergence_mf_vs_retail_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_xl_amount_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='flow_divergence_mf_vs_retail_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='flow_divergence_mf_vs_retail_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_xl_amount_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='flow_divergence_mf_vs_retail_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='flow_divergence_mf_vs_retail_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='资金分歧度1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='主力资金流强度比率1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-主力净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-资金净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_xl_amount_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-超大单净流入1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_net_flow_consensus_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='共识-散户净流入1日斜率'),
        ),
    ]
