# Generated by Django 5.0.1 on 2025-06-17 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0021_stockdailydata_bj_stockdailydata_cy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTrendStrategySignalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(db_index=True, verbose_name='信号日期')),
                ('signal_pullback_confirmed', models.BooleanField(default=False, verbose_name='回踩确认信号')),
                ('signal_early_volume_spike', models.BooleanField(default=False, verbose_name='早期放量信号')),
                ('close_D', models.FloatField(verbose_name='收盘价')),
                ('EMA_20_D', models.FloatField(verbose_name='20日EMA')),
                ('volume_D', models.FloatField(verbose_name='成交量')),
                ('buy_score', models.IntegerField(verbose_name='买入评分')),
                ('analysis_text', models.TextField(verbose_name='分析报告')),
                ('signal_type', models.CharField(max_length=32, verbose_name='信号类型')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_signal_reports', to='stock_models.stockinfo')),
            ],
            options={
                'verbose_name': '月线趋势信号与报告',
                'verbose_name_plural': '月线趋势信号与报告',
                'ordering': ['trade_time'],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
    ]
