# Generated by Django 5.0.1 on 2025-09-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0021_advancedchipmetrics_bj_concentration_70pct_accel_1d_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='chip_health_score_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='chip_health_score_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='concentration_70pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_control_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_stability_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_stability_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_stability_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='chip_health_score_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='chip_health_score_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='concentration_70pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_control_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_stability_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_stability_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_stability_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='chip_health_score_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='chip_health_score_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='concentration_70pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_control_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_stability_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_stability_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_stability_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='chip_health_score_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='chip_health_score_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='concentration_70pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_control_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_stability_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_stability_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_stability_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='chip_health_score_accel_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='chip_health_score_slope_1d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码健康分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='concentration_70pct_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='70%集中度55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_control_ratio_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰控盘比55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_stability_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_stability_accel_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_stability_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰稳定性5日加速度'),
        ),
    ]
