# Generated by Django 5.0.1 on 2025-06-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0022_monthlytrendstrategysignalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysisresulttrendfollowing',
            name='bottom_volume_breakout_signal',
            field=models.FloatField(blank=True, help_text='是否出现底部起涨信号', null=True, verbose_name='底部起涨信号'),
        ),
        migrations.AlterField(
            model_name='stockanalysisresulttrendfollowing',
            name='volume_breakout_signal',
            field=models.FloatField(blank=True, help_text='当前是否处于底部区间', null=True, verbose_name='处于底部区间'),
        ),
    ]
