# Generated by Django 5.0.1 on 2025-09-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0022_advancedchipmetrics_bj_chip_health_score_accel_1d_and_more'),
    ]
    operations = [
        migrations.RenameField(
            model_name='advancedfundflowmetrics_bj',
            old_name='accel_21d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_21d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_bj',
            old_name='accel_5d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_5d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_cy',
            old_name='accel_13d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_13d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_cy',
            old_name='accel_21d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_21d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_cy',
            old_name='accel_5d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_5d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_kc',
            old_name='accel_13d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_13d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_kc',
            old_name='accel_21d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_21d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_kc',
            old_name='accel_5d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_5d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_sh',
            old_name='accel_13d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_13d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_sh',
            old_name='accel_21d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_21d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_sh',
            old_name='accel_5d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_5d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_sz',
            old_name='accel_13d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_13d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_sz',
            old_name='accel_21d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_21d',
        ),
        migrations.RenameField(
            model_name='advancedfundflowmetrics_sz',
            old_name='accel_5d_flow_divergence_mf_vs_retail',
            new_name='flow_divergence_mf_vs_retail_accel_5d',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_bj',
            name='accel_13d_flow_divergence_mf_vs_retail',
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='flow_divergence_mf_vs_retail_accel_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='主力散户分歧度13日加速度'),
        ),
    ]
