# Generated by Django 5.0.1 on 2025-06-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0023_alter_stockanalysisresulttrendfollowing_bottom_volume_breakout_signal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytrendstrategysignalreport',
            name='trade_time',
            field=models.DateTimeField(db_index=True, verbose_name='信号日期'),
        ),
    ]
