# Generated by Django 5.0.1 on 2025-06-19 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0024_alter_monthlytrendstrategysignalreport_trade_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlytrendstrategysignalreport',
            options={'ordering': ['-trade_time'], 'verbose_name': '月线趋势信号与报告', 'verbose_name_plural': '月线趋势信号与报告'},
        ),
        migrations.RemoveField(
            model_name='monthlytrendstrategysignalreport',
            name='signal_early_volume_spike',
        ),
        migrations.RemoveField(
            model_name='monthlytrendstrategysignalreport',
            name='signal_pullback_confirmed',
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='EMA_10_D',
            field=models.FloatField(blank=True, null=True, verbose_name='10日EMA(回踩支撑)'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='EMA_5_D',
            field=models.FloatField(blank=True, null=True, verbose_name='5日EMA(追击支撑)'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='VOL_MA_20_D',
            field=models.FloatField(blank=True, null=True, verbose_name='20日成交量均线'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='high_D',
            field=models.FloatField(blank=True, null=True, verbose_name='最高价'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='low_D',
            field=models.FloatField(blank=True, null=True, verbose_name='最低价'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='open_D',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘价'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='signal_box_rejection',
            field=models.IntegerField(default=0, verbose_name='箱体拒绝信号'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='signal_breakout_trigger',
            field=models.BooleanField(default=False, verbose_name='突破触发信号'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='signal_continuation_entry',
            field=models.BooleanField(default=False, verbose_name='强势追击信号'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='signal_ma_rejection',
            field=models.IntegerField(default=0, verbose_name='均线拒绝信号'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='signal_pullback_entry',
            field=models.BooleanField(default=False, verbose_name='回踩买入信号'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='signal_take_profit',
            field=models.BooleanField(default=False, verbose_name='止盈信号'),
        ),
        migrations.AddField(
            model_name='monthlytrendstrategysignalreport',
            name='washout_score',
            field=models.IntegerField(default=0, verbose_name='洗盘评分'),
        ),
        migrations.AlterField(
            model_name='monthlytrendstrategysignalreport',
            name='EMA_20_D',
            field=models.FloatField(blank=True, null=True, verbose_name='20日EMA'),
        ),
        migrations.AlterField(
            model_name='monthlytrendstrategysignalreport',
            name='close_D',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘价'),
        ),
        migrations.AlterField(
            model_name='monthlytrendstrategysignalreport',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='信号日期'),
        ),
        migrations.AlterField(
            model_name='monthlytrendstrategysignalreport',
            name='volume_D',
            field=models.FloatField(blank=True, null=True, verbose_name='成交量'),
        ),
        migrations.AlterModelTable(
            name='monthlytrendstrategysignalreport',
            table='monthly_trend_strategy_signal_report',
        ),
        migrations.CreateModel(
            name='MonthlyTrendStrategyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(db_index=True, verbose_name='信号日期')),
                ('signal_breakout_trigger', models.BooleanField(default=False, verbose_name='突破触发信号')),
                ('signal_pullback_entry', models.BooleanField(default=False, verbose_name='回踩买入信号')),
                ('signal_continuation_entry', models.BooleanField(default=False, verbose_name='强势追击信号')),
                ('signal_ma_rejection', models.IntegerField(default=0, verbose_name='均线拒绝信号')),
                ('signal_box_rejection', models.IntegerField(default=0, verbose_name='箱体拒绝信号')),
                ('signal_take_profit', models.BooleanField(default=False, verbose_name='止盈信号')),
                ('open_D', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high_D', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low_D', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('close_D', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('EMA_5_D', models.FloatField(blank=True, null=True, verbose_name='5日EMA(追击支撑)')),
                ('EMA_10_D', models.FloatField(blank=True, null=True, verbose_name='10日EMA(回踩支撑)')),
                ('EMA_20_D', models.FloatField(blank=True, null=True, verbose_name='20日EMA')),
                ('volume_D', models.FloatField(blank=True, null=True, verbose_name='成交量')),
                ('VOL_MA_20_D', models.FloatField(blank=True, null=True, verbose_name='20日成交量均线')),
                ('washout_score', models.IntegerField(default=0, verbose_name='洗盘评分')),
                ('buy_score', models.IntegerField(verbose_name='买入评分')),
                ('analysis_text', models.TextField(verbose_name='分析报告')),
                ('signal_type', models.CharField(max_length=32, verbose_name='信号类型')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_trend_strategy_report', to='stock_models.stockinfo')),
            ],
            options={
                'verbose_name': '月线趋势信号与报告',
                'verbose_name_plural': '月线趋势信号与报告',
                'db_table': 'monthly_trend_strategy_report',
                'ordering': ['-trade_time'],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
    ]
