# Generated by Django 5.0.1 on 2025-06-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0025_alter_monthlytrendstrategysignalreport_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlytrendstrategysignalreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlytrendstrategysignalreport',
            name='stock',
        ),
        migrations.AddIndex(
            model_name='monthlytrendstrategyreport',
            index=models.Index(fields=['stock', '-trade_time'], name='stock_trade_time_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlytrendstrategyreport',
            index=models.Index(fields=['-buy_score', '-trade_time'], name='buy_score_trade_time_idx'),
        ),
        migrations.DeleteModel(
            name='MonthlyTrendStrategySignalReport',
        ),
    ]
