# Generated by Django 5.0.1 on 2025-09-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0026_alter_advancedchipmetrics_bj_chip_fault_strength_accel_13d_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='tradingsignal',
            name='final_score',
            field=models.FloatField(default=0.0, help_text='信号日的最终得分'),
        ),
    ]
