# Generated by Django 5.0.1 on 2025-06-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0026_alter_monthlytrendstrategysignalreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytrendstrategyreport',
            name='signal_take_profit',
            field=models.IntegerField(default=0, verbose_name='止盈信号'),
        ),
    ]
