# Generated by Django 5.0.1 on 2025-09-16 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0027_tradingsignal_final_score'),
    ]
    operations = [
        migrations.CreateModel(
            name='KplLimitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日期')),
                ('name', models.CharField(max_length=64, verbose_name='股票名称')),
                ('tag', models.CharField(db_index=True, help_text='例如: 涨停, 跌停, 炸板', max_length=20, verbose_name='榜单类型')),
                ('lu_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='涨停时间')),
                ('ld_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='跌停时间')),
                ('open_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='开板时间')),
                ('last_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='最后涨停时间')),
                ('lu_desc', models.TextField(blank=True, null=True, verbose_name='涨停原因')),
                ('theme', models.TextField(blank=True, null=True, verbose_name='所属板块/题材')),
                ('status', models.CharField(blank=True, help_text='例如: 首板, 2连板', max_length=50, null=True, verbose_name='连板状态')),
                ('pct_chg', models.FloatField(blank=True, null=True, verbose_name='涨跌幅(%)')),
                ('turnover_rate', models.FloatField(blank=True, null=True, verbose_name='换手率(%)')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='成交额(元)')),
                ('limit_order', models.FloatField(blank=True, null=True, verbose_name='封单额(元)')),
                ('lu_limit_order', models.FloatField(blank=True, null=True, verbose_name='最大封单额(元)')),
                ('free_float', models.FloatField(blank=True, null=True, verbose_name='实际流通盘(元)')),
                ('bid_change', models.FloatField(blank=True, null=True, verbose_name='竞价净额(元)')),
                ('bid_turnover', models.FloatField(blank=True, null=True, verbose_name='竞价换手率(%)')),
                ('bid_pct_chg', models.FloatField(blank=True, null=True, verbose_name='竞价涨幅(%)')),
                ('stock', models.ForeignKey(db_column='ts_code', on_delete=django.db.models.deletion.CASCADE, related_name='kpl_limit_list', to='stock_models.stockinfo', verbose_name='股票代码')),
            ],
            options={
                'verbose_name': '开盘啦榜单数据',
                'verbose_name_plural': '开盘啦榜单数据',
                'db_table': 'kpl_limit_list',
                'ordering': ['-trade_date', 'stock'],
                'unique_together': {('stock', 'trade_date', 'tag')},
            },
        ),
    ]
