# Generated by Django 5.0.1 on 2025-06-23 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0027_alter_monthlytrendstrategyreport_signal_take_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendFollowStrategyReport',
            fields=[
                ('id', models.BigAutoField(help_text='报告ID', primary_key=True, serialize=False)),
                ('trade_time', models.DateTimeField(help_text='交易时间（通常为日线收盘时间）')),
                ('entry_signal', models.BooleanField(default=False, help_text='最终是否产生买入信号')),
                ('exit_signal_code', models.IntegerField(default=0, help_text='最终的卖出信号代码 (0:无, >0:对应不同卖出规则)')),
                ('entry_score', models.FloatField(default=0.0, help_text='当日的综合买入得分')),
                ('is_long_term_bullish', models.BooleanField(default=False, help_text='是否处于长期牛市背景')),
                ('is_mid_term_bullish', models.BooleanField(default=False, help_text='是否处于中期牛市背景（均线+动态箱体）')),
                ('triggered_playbooks', models.JSONField(default=dict, help_text='触发的具体买入剧本列表 (JSON格式)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录更新时间')),
                ('stock', models.ForeignKey(help_text='关联的股票', on_delete=django.db.models.deletion.CASCADE, related_name='trend_follow_reports', to='stock_models.stockinfo')),
            ],
            options={
                'verbose_name': '趋势跟踪策略报告',
                'verbose_name_plural': '趋势跟踪策略报告',
                'db_table': 'trend_follow_strategy_report',
                'ordering': ['-trade_time', 'stock'],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
    ]
