# Generated by Django 5.0.1 on 2025-06-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0028_trendfollowstrategyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategyreport',
            name='close_price',
            field=models.FloatField(blank=True, help_text='报告生成当日的收盘价', null=True),
        ),
    ]
