# Generated by Django 5.0.1 on 2025-09-16 02:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0028_kpllimitlist'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='strategyscorecomponent',
            name='daily_score',
        ),
        migrations.DeleteModel(
            name='StrategyDailyState',
        ),
        migrations.DeleteModel(
            name='StrategyScoreComponent',
        ),
    ]
