# Generated by Django 5.0.1 on 2025-06-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0029_trendfollowstrategyreport_close_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategyreport',
            name='is_pullback_setup',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否回撤预备'),
        ),
        migrations.AddField(
            model_name='trendfollowstrategyreport',
            name='pullback_target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='回撤目标价'),
        ),
    ]
