# Generated by Django 5.0.1 on 2025-09-16 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0029_remove_strategyscorecomponent_daily_score_and_more'),
    ]
    operations = [
        migrations.CreateModel(
            name='StrategyDailyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('State', '原子状态'), ('Trigger', '触发事件'), ('Unknown', '未知')], default='Unknown', max_length=20, verbose_name='信号类型')),
                ('daily_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atomic_states_and_triggers', to='stock_models.strategydailyscore', verbose_name='所属每日分数')),
                ('playbook', models.ForeignKey(help_text='关联到具体的战法/规则定义', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_states', to='stock_models.playbook', verbose_name='关联战法')),
            ],
            options={
                'verbose_name': '策略每日状态',
                'verbose_name_plural': '策略每日状态',
                'db_table': 'strategy_daily_state',
                'indexes': [models.Index(fields=['playbook', 'signal_type'], name='strategy_da_playboo_317f02_idx')],
                'unique_together': {('daily_score', 'playbook')},
            },
        ),
        migrations.CreateModel(
            name='StrategyScoreComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('positional', '阵地分'), ('dynamic', '动能分'), ('composite', '战法分'), ('trigger', '触发器分'), ('risk', '风险分'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='分数类型')),
                ('score_value', models.IntegerField(verbose_name='贡献分数')),
                ('daily_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='stock_models.strategydailyscore', verbose_name='所属每日分数')),
                ('playbook', models.ForeignKey(help_text='关联到具体的战法/规则定义', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_components', to='stock_models.playbook', verbose_name='关联战法')),
            ],
            options={
                'verbose_name': '策略分数构成',
                'verbose_name_plural': '策略分数构成',
                'db_table': 'strategy_score_component',
                'indexes': [models.Index(fields=['daily_score', 'score_type'], name='strategy_sc_daily_s_3e0880_idx'), models.Index(fields=['playbook'], name='strategy_sc_playboo_986033_idx')],
                'unique_together': {('daily_score', 'playbook')},
            },
        ),
    ]
