# Generated by Django 5.0.1 on 2025-09-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0030_strategydailystate_strategyscorecomponent'),
    ]
    operations = [
        migrations.AlterField(
            model_name='swindustry',
            name='is_pub',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='是否发布指数'),
        ),
    ]
