# Generated by Django 5.0.1 on 2025-06-23 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0030_trendfollowstrategyreport_is_pullback_setup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendFollowStrategySignalLog',
            fields=[
                ('id', models.BigAutoField(help_text='信号ID', primary_key=True, serialize=False)),
                ('signal_time', models.DateTimeField(db_index=True, help_text='信号生成时的精确时间戳 (K线收盘时间)')),
                ('timeframe', models.CharField(db_index=True, help_text="信号所在的时间周期 (例如 'D', '60', '30')", max_length=10)),
                ('strategy_name', models.CharField(db_index=True, help_text="产生信号的策略名称 (例如 'TrendFollowV1')", max_length=100)),
                ('close_price', models.FloatField(help_text='信号生成时K线的收盘价')),
                ('entry_signal', models.BooleanField(default=False, help_text='是否为买入信号')),
                ('exit_signal_code', models.IntegerField(default=0, help_text='卖出信号代码 (0:无, >0:对应不同卖出规则)')),
                ('entry_score', models.FloatField(default=0.0, help_text='买入信号的综合得分')),
                ('triggered_playbooks', models.JSONField(default=list, help_text='触发信号的具体剧本/规则列表 (JSON格式的列表)')),
                ('context_snapshot', models.JSONField(default=dict, help_text='信号生成时的部分上下文快照 (例如关键指标值)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间')),
                ('stock', models.ForeignKey(help_text='关联的股票', on_delete=django.db.models.deletion.CASCADE, related_name='trend_follow_strategy_signal_log', to='stock_models.stockinfo')),
            ],
            options={
                'verbose_name': '策略信号日志',
                'verbose_name_plural': '策略信号日志',
                'db_table': 'trend_follow_strategy_signal_log',
                'ordering': ['-signal_time', 'stock'],
                'indexes': [models.Index(fields=['stock', 'signal_time'], name='trend_follo_stock_i_f3766b_idx'), models.Index(fields=['strategy_name', 'timeframe', 'signal_time'], name='trend_follo_strateg_9dc162_idx')],
                'unique_together': {('stock', 'signal_time', 'strategy_name', 'timeframe')},
            },
        ),
    ]
