# Generated by Django 5.0.1 on 2025-09-16 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0031_alter_swindustry_is_pub'),
    ]
    operations = [
        migrations.AlterModelOptions(
            name='dcindexdaily',
            options={'ordering': ['-trade_time'], 'verbose_name': '东方财富板块指数行情', 'verbose_name_plural': '东方财富板块指数行情'},
        ),
        migrations.RemoveField(
            model_name='dcindexdaily',
            name='down_num',
        ),
        migrations.RemoveField(
            model_name='dcindexdaily',
            name='leading',
        ),
        migrations.RemoveField(
            model_name='dcindexdaily',
            name='leading_pct',
        ),
        migrations.RemoveField(
            model_name='dcindexdaily',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dcindexdaily',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='dcindexdaily',
            name='total_mv',
        ),
        migrations.RemoveField(
            model_name='dcindexdaily',
            name='up_num',
        ),
        migrations.AddField(
            model_name='dcindexdaily',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='成交额(千元)'),
        ),
        migrations.AddField(
            model_name='dcindexdaily',
            name='change',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌点位'),
        ),
        migrations.AddField(
            model_name='dcindexdaily',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘点位'),
        ),
        migrations.AddField(
            model_name='dcindexdaily',
            name='high',
            field=models.FloatField(blank=True, null=True, verbose_name='最高点位'),
        ),
        migrations.AddField(
            model_name='dcindexdaily',
            name='low',
            field=models.FloatField(blank=True, null=True, verbose_name='最低点位'),
        ),
        migrations.AddField(
            model_name='dcindexdaily',
            name='open',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘点位'),
        ),
        migrations.AddField(
            model_name='dcindexdaily',
            name='swing',
            field=models.FloatField(blank=True, null=True, verbose_name='振幅(%)'),
        ),
        migrations.AddField(
            model_name='dcindexdaily',
            name='vol',
            field=models.FloatField(blank=True, null=True, verbose_name='成交量(手)'),
        ),
        migrations.AlterField(
            model_name='dcindexdaily',
            name='dc_index',
            field=models.ForeignKey(db_column='ts_code', on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stock_models.dcindex', to_field='ts_code', verbose_name='东方财富概念板块'),
        ),
        migrations.AlterField(
            model_name='dcindexdaily',
            name='pct_change',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌幅(%)'),
        ),
        migrations.AlterField(
            model_name='dcindexdaily',
            name='trade_time',
            field=models.DateField(verbose_name='交易日'),
        ),
        migrations.AlterField(
            model_name='dcindexdaily',
            name='turnover_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='换手率(%)'),
        ),
        migrations.AlterField(
            model_name='dcindexmember',
            name='dc_index',
            field=models.ForeignKey(db_column='ts_code', on_delete=django.db.models.deletion.CASCADE, related_name='dc_member', to='stock_models.dcindex', to_field='ts_code', verbose_name='指数'),
        ),
        migrations.AlterField(
            model_name='dcindexmember',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
    ]
