# Generated by Django 5.0.1 on 2025-06-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0031_trendfollowstrategysignallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='is_breakout_trigger',
            field=models.BooleanField(default=False, help_text='是否为突破观察信号 (非直接买入)'),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='is_continuation_entry',
            field=models.BooleanField(default=False, help_text='是否为追击买入信号'),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='is_pullback_entry',
            field=models.BooleanField(default=False, help_text='是否为回踩买入信号'),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='rejection_code',
            field=models.IntegerField(default=0, help_text='压力位拒绝代码 (0:无, 1:MA拒绝, 2:箱体拒绝, 3:两者皆有)'),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='washout_score',
            field=models.IntegerField(default=0, help_text='洗盘强度得分'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='context_snapshot',
            field=models.JSONField(default=dict, help_text='信号生成时的关键指标快照 (用于调试)'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='entry_signal',
            field=models.BooleanField(default=False, help_text='是否为最终的买入信号 (得分超过阈值)'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='exit_signal_code',
            field=models.IntegerField(default=0, help_text='卖出信号代码 (0:无, 1:压力位, 2:移动止盈, 3:指标)'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='strategy_name',
            field=models.CharField(db_index=True, help_text="产生信号的策略名称 (例如 'MonthlyTrendFollow_V7')", max_length=100),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='triggered_playbooks',
            field=models.JSONField(default=list, help_text='触发信号的所有原子规则列表 (用于详细分析)'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['is_pullback_entry', 'signal_time'], name='trend_follo_is_pull_643b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['entry_signal', 'signal_time'], name='trend_follo_entry_s_704ed8_idx'),
        ),
    ]
