# Generated by Django 5.0.1 on 2025-06-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0032_trendfollowstrategysignallog_is_breakout_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='pullback_target_price',
            field=models.FloatField(blank=True, default=None, help_text='回踩买入剧本的目标价格', null=True),
        ),
    ]
