# Generated by Django 5.0.1 on 2025-09-16 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0032_alter_dcindexdaily_options_and_more'),
    ]
    operations = [
        migrations.CreateModel(
            name='KplConceptInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='题材代码')),
                ('name', models.CharField(max_length=64, verbose_name='题材名称')),
            ],
            options={
                'verbose_name': '开盘啦题材信息',
                'verbose_name_plural': '开盘啦题材信息',
                'db_table': 'kpl_concept_info',
            },
        ),
        migrations.AlterUniqueTogether(
            name='kplconceptconstituent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kplconceptconstituent',
            name='concept_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituents', to='stock_models.kplconceptinfo', to_field='ts_code', verbose_name='所属题材'),
        ),
        migrations.AlterUniqueTogether(
            name='kplconceptconstituent',
            unique_together={('concept_info', 'stock', 'trade_time')},
        ),
        migrations.CreateModel(
            name='KplConceptDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trade_time', models.CharField(db_index=True, max_length=8, verbose_name='交易日期')),
                ('z_t_num', models.IntegerField(blank=True, null=True, verbose_name='涨停数量')),
                ('up_num', models.IntegerField(blank=True, null=True, verbose_name='排名上升位数')),
                ('concept_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='stock_models.kplconceptinfo', to_field='ts_code', verbose_name='关联题材信息')),
            ],
            options={
                'verbose_name': '开盘啦题材每日快照',
                'verbose_name_plural': '开盘啦题材每日快照',
                'db_table': 'kpl_concept_daily',
                'unique_together': {('concept_info', 'trade_time')},
            },
        ),
        migrations.RemoveField(
            model_name='kplconceptconstituent',
            name='con_name',
        ),
        migrations.RemoveField(
            model_name='kplconceptconstituent',
            name='concept',
        ),
        migrations.RemoveField(
            model_name='kplconceptconstituent',
            name='name',
        ),
        migrations.DeleteModel(
            name='KplConcept',
        ),
    ]
