# Generated by Django 5.0.1 on 2025-06-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0033_trendfollowstrategysignallog_pullback_target_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendfollowstrategysignallog',
            options={'ordering': ['-trade_time', 'stock'], 'verbose_name': '策略信号日志', 'verbose_name_plural': '策略信号日志'},
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_stock_i_f3766b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_strateg_9dc162_idx',
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_is_pull_643b2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_entry_s_704ed8_idx',
        ),
        migrations.RenameField(
            model_name='trendfollowstrategysignallog',
            old_name='signal_time',
            new_name='trade_time',
        ),
        migrations.AlterUniqueTogether(
            name='trendfollowstrategysignallog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='is_long_term_bullish',
            field=models.BooleanField(default=False, help_text='[趋势策略]是否处于长期牛市背景'),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='is_mid_term_bullish',
            field=models.BooleanField(default=False, help_text='[趋势策略]是否处于中期上升趋势'),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='is_pullback_setup',
            field=models.BooleanField(default=False, help_text='[趋势策略]是否为回撤预备信号'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='is_breakout_trigger',
            field=models.BooleanField(default=False, help_text='[月线策略]是否为突破观察信号'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='is_continuation_entry',
            field=models.BooleanField(default=False, help_text='[月线策略]是否为追击买入信号'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='is_pullback_entry',
            field=models.BooleanField(default=False, help_text='[月线策略]是否为回踩买入信号'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='pullback_target_price',
            field=models.FloatField(blank=True, default=None, help_text='[趋势/月线]回踩买入剧本的目标价格', null=True),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='rejection_code',
            field=models.IntegerField(default=0, help_text='[月线策略]压力位拒绝代码 (0:无, 1:MA, 2:箱体, 3:两者)'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='strategy_name',
            field=models.CharField(db_index=True, help_text='产生信号的策略名称', max_length=100),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='washout_score',
            field=models.IntegerField(default=0, help_text='[月线策略]洗盘强度得分'),
        ),
        migrations.AlterUniqueTogether(
            name='trendfollowstrategysignallog',
            unique_together={('stock', 'trade_time', 'strategy_name', 'timeframe')},
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['stock', 'trade_time'], name='trend_follo_stock_i_163b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['strategy_name', 'timeframe', 'trade_time'], name='trend_follo_strateg_aa7e64_idx'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['entry_signal', 'trade_time'], name='trend_follo_entry_s_706b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['is_long_term_bullish', 'is_mid_term_bullish', 'trade_time'], name='trend_follo_is_long_462598_idx'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['is_pullback_setup', 'trade_time'], name='trend_follo_is_pull_bd65b2_idx'),
        ),
    ]
