# Generated by Django 5.0.1 on 2025-09-17 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0033_kplconceptinfo_alter_dcindexdaily_dc_index_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='dcindexdaily',
            name='dc_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stock_models.dcindex', to_field='ts_code', verbose_name='东方财富概念板块'),
        ),
        migrations.AlterField(
            model_name='dcindexmember',
            name='dc_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_member', to='stock_models.dcindex', to_field='ts_code', verbose_name='指数'),
        ),
        migrations.AlterField(
            model_name='strategyscorecomponent',
            name='score_type',
            field=models.CharField(choices=[('positional', '阵地分'), ('dynamic', '动能分'), ('composite', '战法分'), ('trigger', '触发器分'), ('risk', '风险分'), ('subtotal', '小计分'), ('penalty', '惩罚项'), ('unknown', '未知')], default='unknown', max_length=20, verbose_name='分数类型'),
        ),
        migrations.DeleteModel(
            name='KplConceptDaily',
        ),
    ]
