# Generated by Django 5.0.1 on 2025-06-24 03:07

import stock_models.stock_analytics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0034_alter_trendfollowstrategysignallog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='context_snapshot',
            field=models.JSONField(default=dict, encoder=stock_models.stock_analytics.DecimalEncoder, help_text='信号生成时的关键指标快照 (用于调试)'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='triggered_playbooks',
            field=models.JSONField(default=list, encoder=stock_models.stock_analytics.DecimalEncoder, help_text='触发信号的所有原子规则列表 (用于详细分析)'),
        ),
    ]
