# Generated by Django 5.0.1 on 2025-09-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0035_kplconceptdaily'),
    ]
    operations = [
        migrations.AlterField(
            model_name='kplconceptconstituent',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='kplconceptdaily',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
    ]
