# Generated by Django 5.0.1 on 2025-06-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0035_alter_trendfollowstrategysignallog_context_snapshot_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_stock_i_163b4c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='trendfollowstrategysignallog',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='close_price',
            field=models.DecimalField(decimal_places=3, help_text='信号生成时K线的收盘价', max_digits=10),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='pullback_target_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, help_text='[趋势/月线]回踩买入剧本的目标价格', max_digits=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='trendfollowstrategysignallog',
            constraint=models.UniqueConstraint(fields=('stock', 'trade_time', 'strategy_name', 'timeframe'), name='unique_signal_log_entry'),
        ),
    ]
