# Generated by Django 5.0.1 on 2025-09-17 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0036_alter_kplconceptconstituent_trade_time_and_more'),
    ]
    operations = [
        # 开始手动SQL操作
        # 在Django执行AlterField之前，我们手动将数据库列名更改为Django历史记录所期望的名称。
        # 这解决了数据库实际状态与Django迁移历史之间的不一致。
        migrations.RunSQL(
            "ALTER TABLE `dc_index_daily` CHANGE `ts_code` `dc_index_id` VARCHAR(20);",
            "ALTER TABLE `dc_index_daily` CHANGE `dc_index_id` `ts_code` VARCHAR(20);"
        ),
        migrations.RunSQL(
            "ALTER TABLE `ths_index_daily` CHANGE `ts_code` `ths_index_id` VARCHAR(20);",
            "ALTER TABLE `ths_index_daily` CHANGE `ths_index_id` `ts_code` VARCHAR(20);"
        ),
        # 结束手动SQL操作
        # Django自动生成的AlterField操作现在可以正常执行了
        migrations.AlterField(
            model_name='dcindexdaily',
            name='dc_index',
            field=models.ForeignKey(db_column='ts_code', on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stock_models.dcindex', to_field='ts_code', verbose_name='东方财富概念板块'),
        ),
        migrations.AlterField(
            model_name='thsindexdaily',
            name='ths_index',
            field=models.ForeignKey(db_column='ts_code', on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stock_models.thsindex', to_field='ts_code', verbose_name='所属指数'),
        ),
    ]
