# Generated by Django 5.0.1 on 2025-06-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0036_remove_trendfollowstrategysignallog_trend_follo_stock_i_163b4c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendFollowStrategyState',
            fields=[
                ('id', models.BigAutoField(help_text='状态ID', primary_key=True, serialize=False)),
                ('strategy_name', models.CharField(db_index=True, help_text='策略名称', max_length=100)),
                ('time_level', models.CharField(db_index=True, help_text="策略运行的时间框架 (例如 'D', '60', '30')", max_length=10)),
                ('latest_score', models.FloatField(default=0.0, help_text='最新的策略综合得分')),
                ('latest_trade_time', models.DateTimeField(blank=True, help_text='最新信号的K线时间', null=True)),
                ('last_buy_time', models.DateTimeField(blank=True, help_text='最近一次有效买入信号的时间', null=True)),
                ('last_sell_time', models.DateTimeField(blank=True, help_text='最近一次有效卖出信号的时间', null=True)),
                ('active_playbooks', models.JSONField(default=list, help_text='最新信号触发的剧本/规则列表')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='状态更新时间')),
                ('stock', models.ForeignKey(help_text='关联的股票', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_states', to='stock_models.stockinfo')),
            ],
            options={
                'verbose_name': '策略状态摘要',
                'verbose_name_plural': '策略状态摘要',
                'db_table': 'trend_follow_strategy_state_summary',
                'ordering': ['-latest_score', 'stock'],
            },
        ),
        migrations.AddConstraint(
            model_name='trendfollowstrategystate',
            constraint=models.UniqueConstraint(fields=('stock', 'strategy_name', 'time_level'), name='unique_stock_strategy_state'),
        ),
    ]
