# Generated by Django 5.0.1 on 2025-06-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0037_trendfollowstrategystate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='time_level',
            field=models.CharField(db_index=True, default='D', help_text="策略运行的时间框架 (例如 'D', '60', '30')", max_length=10),
        ),
    ]
