# Generated by Django 5.0.1 on 2025-09-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0038_alter_kplconceptconstituent_concept_info'),
    ]
    operations = [
        migrations.AlterField(
            model_name='kplconceptinfo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='题材名称'),
        ),
    ]
