# Generated by Django 5.0.1 on 2025-06-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0038_trendfollowstrategysignallog_time_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendfollowstrategysignallog',
            name='time_level',
        ),
    ]
