# Generated by Django 5.0.1 on 2025-06-25 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0039_remove_trendfollowstrategysignallog_time_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendfollowstrategystate',
            name='stock',
            field=models.ForeignKey(db_column='stock_code', help_text='关联的股票', on_delete=django.db.models.deletion.CASCADE, related_name='strategy_states', to='stock_models.stockinfo'),
        ),
    ]
