# Generated by Django 5.0.1 on 2025-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0039_alter_kplconceptinfo_name'),
    ]
    operations = [
        migrations.AlterField(
            model_name='swindustrydaily',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='成交额（万元）'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='change',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌点位'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='close',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘点位'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='float_mv',
            field=models.FloatField(blank=True, null=True, verbose_name='流通市值（万元）'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='high',
            field=models.FloatField(blank=True, null=True, verbose_name='最高点位'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='low',
            field=models.FloatField(blank=True, null=True, verbose_name='最低点位'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='open',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘点位'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='pb',
            field=models.FloatField(blank=True, null=True, verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='pct_change',
            field=models.FloatField(blank=True, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='pe',
            field=models.FloatField(blank=True, null=True, verbose_name='市盈率'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='total_mv',
            field=models.FloatField(blank=True, null=True, verbose_name='总市值（万元）'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='vol',
            field=models.FloatField(blank=True, null=True, verbose_name='成交量（万股）'),
        ),
    ]
