# Generated by Django 5.0.1 on 2025-07-02 16:30

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0040_alter_trendfollowstrategystate_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockanalysisresulttrendfollowing',
            name='timestamp',
            field=common.fields.TimestampField(db_index=True, help_text='该分析结果对应的数据时间戳', verbose_name='分析时间戳'),
        ),
        migrations.AlterField(
            model_name='stocklevel5data',
            name='trade_time',
            field=common.fields.TimestampField(verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_15_bj',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_15_cy',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_15_kc',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_15_sh',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_15_sz',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_30_bj',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_30_cy',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_30_kc',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_30_sh',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_30_sz',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_5_bj',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_5_cy',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_5_kc',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_5_sh',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_5_sz',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_60_bj',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_60_cy',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_60_kc',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_60_sh',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockminutedata_60_sz',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='stockrealtimedata',
            name='trade_time',
            field=common.fields.TimestampField(verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stockscoreanalysis',
            name='created_at',
            field=common.fields.TimestampField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stockscoreanalysis',
            name='timestamp',
            field=common.fields.TimestampField(db_index=True, verbose_name='分析时间戳'),
        ),
        migrations.AlterField(
            model_name='stockscoreanalysis',
            name='updated_at',
            field=common.fields.TimestampField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stocktimetrade',
            name='trade_time',
            field=common.fields.TimestampField(verbose_name='交易时间'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategyreport',
            name='created_at',
            field=common.fields.TimestampField(auto_now_add=True, help_text='记录创建时间'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategyreport',
            name='trade_time',
            field=common.fields.TimestampField(help_text='交易时间（通常为日线收盘时间）'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategyreport',
            name='updated_at',
            field=common.fields.TimestampField(auto_now=True, help_text='记录更新时间'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='created_at',
            field=common.fields.TimestampField(auto_now_add=True, help_text='记录创建时间'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='trade_time',
            field=common.fields.TimestampField(db_index=True, help_text='信号生成时的精确时间戳 (K线收盘时间)'),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategystate',
            name='last_buy_time',
            field=common.fields.TimestampField(blank=True, help_text='最近一次有效买入信号的时间', null=True),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategystate',
            name='last_sell_time',
            field=common.fields.TimestampField(blank=True, help_text='最近一次有效卖出信号的时间', null=True),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategystate',
            name='latest_trade_time',
            field=common.fields.TimestampField(blank=True, help_text='最新信号的K线时间', null=True),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategystate',
            name='updated_at',
            field=common.fields.TimestampField(auto_now=True, help_text='状态更新时间'),
        ),
    ]
