# Generated by Django 5.0.1 on 2025-09-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0040_alter_swindustrydaily_amount_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='ciindexmember',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='成分股票名称'),
        ),
        migrations.AlterField(
            model_name='kpllimitlist',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='swindustrydaily',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='成分股票名称'),
        ),
    ]
