# Generated by Django 5.0.1 on 2025-07-04 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0040_alter_trendfollowstrategystate_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCyqChipsBJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(db_index=True, verbose_name='交易日期')),
                ('price', models.FloatField(verbose_name='成本价格')),
                ('percent', models.FloatField(verbose_name='价格占比(%)')),
            ],
            options={
                'verbose_name': '每日筹码分布BJ',
                'verbose_name_plural': '每日筹码分布BJ',
                'db_table': 'stock_cyq_chips_bj',
            },
        ),
        migrations.CreateModel(
            name='StockCyqChipsCY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(db_index=True, verbose_name='交易日期')),
                ('price', models.FloatField(verbose_name='成本价格')),
                ('percent', models.FloatField(verbose_name='价格占比(%)')),
            ],
            options={
                'verbose_name': '每日筹码分布CY',
                'verbose_name_plural': '每日筹码分布CY',
                'db_table': 'stock_cyq_chips_cy',
            },
        ),
        migrations.CreateModel(
            name='StockCyqChipsSH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(db_index=True, verbose_name='交易日期')),
                ('price', models.FloatField(verbose_name='成本价格')),
                ('percent', models.FloatField(verbose_name='价格占比(%)')),
            ],
            options={
                'verbose_name': '每日筹码分布SH',
                'verbose_name_plural': '每日筹码分布SH',
                'db_table': 'stock_cyq_chips_sh',
            },
        ),
        migrations.CreateModel(
            name='StockCyqChipsSZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(db_index=True, verbose_name='交易日期')),
                ('price', models.FloatField(verbose_name='成本价格')),
                ('percent', models.FloatField(verbose_name='价格占比(%)')),
            ],
            options={
                'verbose_name': '每日筹码分布SZ',
                'verbose_name_plural': '每日筹码分布SZ',
                'db_table': 'stock_cyq_chips_sz',
            },
        ),
        migrations.RenameModel(
            old_name='StockCyqChips',
            new_name='StockCyqChipsKC',
        ),
        migrations.AlterModelOptions(
            name='stockcyqchipskc',
            options={'verbose_name': '每日筹码分布KC', 'verbose_name_plural': '每日筹码分布KC'},
        ),
        migrations.RenameIndex(
            model_name='stockcyqchipskc',
            new_name='stock_cyq_c_stock_i_ac0756_idx',
            old_name='stock_cyq_c_stock_i_692e34_idx',
        ),
        migrations.AlterModelTable(
            name='stockcyqchipskc',
            table='stock_cyq_chips_kc',
        ),
        migrations.AddField(
            model_name='stockcyqchipsbj',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockinfo', verbose_name='stock_cyq_chips_bj'),
        ),
        migrations.AddField(
            model_name='stockcyqchipscy',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockinfo', verbose_name='stock_cyq_chips_cy'),
        ),
        migrations.AddField(
            model_name='stockcyqchipssh',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockinfo', verbose_name='stock_cyq_chips_sh'),
        ),
        migrations.AddField(
            model_name='stockcyqchipssz',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockinfo', verbose_name='stock_cyq_chips_sz'),
        ),
        migrations.AddIndex(
            model_name='stockcyqchipsbj',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_cyq_c_stock_i_f3dc0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcyqchipsbj',
            unique_together={('stock', 'trade_time', 'price')},
        ),
        migrations.AddIndex(
            model_name='stockcyqchipscy',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_cyq_c_stock_i_0075ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcyqchipscy',
            unique_together={('stock', 'trade_time', 'price')},
        ),
        migrations.AddIndex(
            model_name='stockcyqchipssh',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_cyq_c_stock_i_9070cf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcyqchipssh',
            unique_together={('stock', 'trade_time', 'price')},
        ),
        migrations.AddIndex(
            model_name='stockcyqchipssz',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_cyq_c_stock_i_6bb5cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcyqchipssz',
            unique_together={('stock', 'trade_time', 'price')},
        ),
    ]
