# Generated by Django 5.0.1 on 2025-09-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0041_alter_ciindexmember_name_alter_kpllimitlist_name_and_more'),
    ]
    operations = [
        migrations.CreateModel(
            name='IndustryLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日期')),
                ('strength_rank', models.FloatField(null=True, verbose_name='强度排名(0-1)')),
                ('rank_slope', models.FloatField(null=True, verbose_name='排名斜率')),
                ('rank_accel', models.FloatField(null=True, verbose_name='排名加速度')),
                ('lifecycle_stage', models.CharField(blank=True, choices=[('PREHEAT', '预热期'), ('MARKUP', '主升段'), ('STAGNATION', '滞涨期'), ('DOWNTREND', '下跌段'), ('TRANSITION', '过渡期')], max_length=20, null=True, verbose_name='生命周期阶段')),
                ('ths_index', models.ForeignKey(db_column='industry_code', on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_data', to='stock_models.thsindex', to_field='ts_code', verbose_name='同花顺行业')),
            ],
            options={
                'verbose_name': '行业生命周期',
                'verbose_name_plural': '行业生命周期',
                'db_table': 'industry_lifecycle',
                'ordering': ['-trade_date', 'strength_rank'],
                'unique_together': {('ths_index', 'trade_date')},
            },
        ),
    ]
