# Generated by Django 5.0.1 on 2025-07-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0042_fundflowdailybj_fundflowdailycy_fundflowdailykc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='exit_severity_level',
            field=models.IntegerField(default=0, help_text='止盈信号的严重性等级 (0:无, 1:预警, 2:标准, 3:紧急)'),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='exit_signal_reason',
            field=models.CharField(blank=True, help_text='止盈信号的具体原因描述', max_length=255, null=True),
        ),
    ]
