# Generated by Django 5.0.1 on 2025-09-17 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0042_industrylifecycle'),
    ]
    operations = [
        migrations.CreateModel(
            name='ConceptMaster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='板块/概念代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('source', models.CharField(db_index=True, help_text="例如: 'ths', 'sw', 'dc', 'kpl'", max_length=20, verbose_name='来源')),
                ('type', models.CharField(blank=True, help_text="例如: '行业', '概念', '地域'", max_length=20, null=True, verbose_name='类型')),
            ],
            options={
                'verbose_name': '板块/概念主数据',
                'verbose_name_plural': '板块/概念主数据',
                'db_table': 'concept_master',
                'ordering': ['source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConceptDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(db_index=True, verbose_name='交易日期')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘点位')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高点位')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低点位')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘点位')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='昨收点位')),
                ('change', models.FloatField(blank=True, null=True, verbose_name='涨跌点位')),
                ('pct_change', models.FloatField(blank=True, null=True, verbose_name='涨跌幅(%)')),
                ('vol', models.FloatField(blank=True, null=True, verbose_name='成交量(手/万股)')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='成交额(元/万元)')),
                ('turnover_rate', models.FloatField(blank=True, null=True, verbose_name='换手率(%)')),
                ('concept', models.ForeignKey(db_column='concept_code', on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stock_models.conceptmaster', to_field='code', verbose_name='关联板块/概念')),
            ],
            options={
                'verbose_name': '板块/概念日线行情',
                'verbose_name_plural': '板块/概念日线行情',
                'db_table': 'concept_daily',
                'ordering': ['-trade_date'],
                'unique_together': {('concept', 'trade_date')},
            },
        ),
        migrations.CreateModel(
            name='ConceptMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(db_index=True, help_text="例如: 'ths', 'sw', 'dc'", max_length=20, verbose_name='来源')),
                ('in_date', models.DateField(db_index=True, verbose_name='纳入日期')),
                ('out_date', models.DateField(blank=True, null=True, verbose_name='剔除日期')),
                ('concept', models.ForeignKey(db_column='concept_code', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='stock_models.conceptmaster', to_field='code', verbose_name='所属板块/概念')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='concept_memberships', to='stock_models.stockinfo', verbose_name='成分股')),
            ],
            options={
                'verbose_name': '板块/概念成分股',
                'verbose_name_plural': '板块/概念成分股',
                'db_table': 'concept_member',
                'ordering': ['-in_date', 'concept', 'stock'],
                'unique_together': {('concept', 'stock', 'in_date', 'source')},
            },
        ),
        migrations.DeleteModel(
            name='IndustryLifecycle',
        ),
    ]
