# Generated by Django 5.0.1 on 2025-07-10 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0043_trendfollowstrategysignallog_exit_severity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedChipMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(db_index=True, verbose_name='交易日期')),
                ('peak_cost', models.FloatField(blank=True, help_text='当天筹码分布最密集的价格', null=True, verbose_name='主筹码峰成本')),
                ('peak_percent', models.FloatField(blank=True, help_text='主筹码峰位置的筹码比例', null=True, verbose_name='主筹码峰占比(%)')),
                ('peak_cost_slope_5d', models.FloatField(blank=True, help_text='主筹码峰成本的5日线性回归斜率 (短期速度)', null=True, verbose_name='筹码峰成本5日斜率')),
                ('peak_cost_slope_20d', models.FloatField(blank=True, help_text='主筹码峰成本的20日线性回归斜率 (中期趋势)', null=True, verbose_name='筹码峰成本20日斜率')),
                ('peak_cost_accel_5d', models.FloatField(blank=True, help_text='主筹码峰成本5日斜率的斜率 (趋势变化快慢)', null=True, verbose_name='筹码峰成本5日加速度')),
                ('concentration_90pct', models.FloatField(blank=True, help_text='包含90%筹码的最小价格区间宽度 / 平均成本', null=True, verbose_name='90%筹码集中度')),
                ('concentration_90pct_slope_5d', models.FloatField(blank=True, help_text='负值表示筹码趋于集中，正值表示发散', null=True, verbose_name='90%集中度5日斜率')),
                ('peak_stability', models.FloatField(blank=True, help_text='主筹码峰的突出程度(prominence) / 平均占比，值越大越稳定', null=True, verbose_name='筹码峰稳定性')),
                ('winner_rate_short_term', models.FloatField(blank=True, help_text='持仓成本低于收盘价，但高于20日前收盘价的筹码比例', null=True, verbose_name='短期获利盘(%)')),
                ('winner_rate_long_term', models.FloatField(blank=True, help_text='持仓成本低于20日前收盘价的筹码比例', null=True, verbose_name='长期锁定盘(%)')),
                ('is_multi_peak', models.BooleanField(default=False, help_text='当天是否存在多个显著的筹码峰', verbose_name='是否多峰形态')),
                ('secondary_peak_cost', models.FloatField(blank=True, help_text='如果存在，第二大筹码峰的成本价', null=True, verbose_name='次筹码峰成本')),
                ('peak_distance_ratio', models.FloatField(blank=True, help_text='主次峰成本价的距离 / 主峰成本价', null=True, verbose_name='主次峰距离比')),
                ('peak_strength_ratio', models.FloatField(blank=True, help_text='次峰突出度 / 主峰突出度', null=True, verbose_name='主次峰强度比')),
                ('pressure_above', models.FloatField(blank=True, help_text='收盘价上方2%价格区间内的筹码占比，代表直接压力', null=True, verbose_name='上方2%套牢盘(%)')),
                ('support_below', models.FloatField(blank=True, help_text='收盘价下方2%价格区间内的筹码占比，代表直接支撑', null=True, verbose_name='下方2%支撑盘(%)')),
                ('total_chip_volume', models.BigIntegerField(blank=True, help_text='用于计算的筹码总量，通常是流通股本', null=True, verbose_name='总筹码量(股)')),
                ('peak_volume', models.BigIntegerField(blank=True, help_text='主筹码峰位置的绝对成交股数', null=True, verbose_name='主筹码峰成交量(股)')),
                ('pressure_above_volume', models.BigIntegerField(blank=True, help_text='收盘价上方2%价格区间内的绝对筹码股数', null=True, verbose_name='上方套牢盘绝对量(股)')),
                ('support_below_volume', models.BigIntegerField(blank=True, help_text='收盘价下方2%价格区间内的绝对筹码股数', null=True, verbose_name='下方支撑盘绝对量(股)')),
                ('turnover_volume_in_cost_range_70pct', models.BigIntegerField(blank=True, help_text='当天成交量中，在70%核心成本区内完成的绝对股数', null=True, verbose_name='70%成本区换手量(股)')),
                ('is_on_dragon_tiger_list', models.BooleanField(default=False, help_text='当天是否登上龙虎榜', verbose_name='当日是否上榜')),
                ('d_t_list_institutional_net_buy', models.FloatField(blank=True, help_text='龙虎榜“机构专用”席位总净买入额', null=True, verbose_name='龙虎榜机构净买入额')),
                ('d_t_list_hot_money_net_buy', models.FloatField(blank=True, help_text='龙虎榜知名游资席位总净买入额', null=True, verbose_name='龙虎榜游资净买入额')),
                ('top10_shareholder_concentration_q', models.FloatField(blank=True, help_text='前十大流通股东持股比例之和', null=True, verbose_name='前十大股东持股集中度(季度)')),
                ('qfii_holdings_change_q', models.FloatField(blank=True, help_text='QFII持股数量的季度环比变化', null=True, verbose_name='QFII持股变动(季度)')),
                ('major_shareholder_pledge_ratio', models.FloatField(blank=True, help_text='主要股东累计质押股份占总股本的比例', null=True, verbose_name='大股东质押比例')),
                ('upcoming_unlock_ratio_3m', models.FloatField(blank=True, help_text='未来3个月即将解禁的股份占总股本的比例', null=True, verbose_name='未来3月解禁比例')),
                ('hot_theme_correlation_score', models.FloatField(blank=True, help_text='与当前市场最热题材的关联度评分(0-1)', null=True, verbose_name='题材关联度得分')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '高级筹码指标V4.0(全息版)',
                'verbose_name_plural': '高级筹码指标V4.0(全息版)',
                'db_table': 'stock_advanced_chip_metrics',
                'indexes': [models.Index(fields=['stock', 'trade_time'], name='stock_advan_stock_i_0ccee7_idx')],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
    ]
