# Generated by Django 5.0.1 on 2025-07-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0044_advancedchipmetrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedchipmetrics',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标(斐波那契版)', 'verbose_name_plural': '高级筹码指标(斐波那契版)'},
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics',
            name='stock_advan_stock_i_0ccee7_idx',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='d_t_list_hot_money_net_buy',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='d_t_list_institutional_net_buy',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='hot_theme_correlation_score',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='is_on_dragon_tiger_list',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='major_shareholder_pledge_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_20d',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='qfii_holdings_change_q',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='top10_shareholder_concentration_q',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='total_chip_volume',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='upcoming_unlock_ratio_3m',
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_cost_accel_21d',
            field=models.FloatField(blank=True, help_text='中期趋势的健康度变化', null=True, verbose_name='筹码峰成本21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='筹码峰成本13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_144d',
            field=models.FloatField(blank=True, null=True, verbose_name='筹码峰成本144日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='筹码峰成本21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_34d',
            field=models.FloatField(blank=True, null=True, verbose_name='筹码峰成本34日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='筹码峰成本55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_89d',
            field=models.FloatField(blank=True, null=True, verbose_name='筹码峰成本89日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_8d',
            field=models.FloatField(blank=True, null=True, verbose_name='筹码峰成本8日斜率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='prev_20d_close',
            field=models.FloatField(blank=True, null=True, verbose_name='20日前收盘价'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_accel_5d',
            field=models.FloatField(blank=True, help_text='短期趋势的动量变化', null=True, verbose_name='筹码峰成本5日加速度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='筹码峰成本5日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_chip_metrics', to='stock_models.stockinfo', verbose_name='股票'),
        ),
        migrations.AlterModelTable(
            name='advancedchipmetrics',
            table='stock_time_trade_advanced_chip_metrics',
        ),
    ]
