# Generated by Django 5.0.1 on 2025-09-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0044_industrylifecycle'),
    ]
    operations = [
        migrations.AddField(
            model_name='industrylifecycle',
            name='breadth_score',
            field=models.FloatField(null=True, verbose_name='内部广度分(0-1)'),
        ),
        migrations.AddField(
            model_name='industrylifecycle',
            name='leader_score',
            field=models.FloatField(null=True, verbose_name='龙头效应分(0-1)'),
        ),
    ]
