# Generated by Django 5.0.1 on 2025-07-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0045_alter_advancedchipmetrics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advancedchipmetrics',
            table='stock_advanced_chip_metrics',
        ),
    ]
