# Generated by Django 5.0.1 on 2025-07-13 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0046_alter_advancedchipmetrics_table'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockcyqchipsbj',
            name='stock_cyq_c_stock_i_f3dc0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockcyqchipscy',
            name='stock_cyq_c_stock_i_0075ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockcyqchipskc',
            name='stock_cyq_c_stock_i_ac0756_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockcyqperf',
            name='stock_cyq_p_stock_i_8b0ec4_idx',
        ),
    ]
