# Generated by Django 5.0.1 on 2025-09-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0047_alter_strategydailyscore_trade_action'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_lg_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-中单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_md_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-小单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='net_sh_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_lg_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-中单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_md_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-小单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='net_sh_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_lg_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-中单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_md_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-小单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='net_sh_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_lg_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-中单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_md_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-小单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='net_sh_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-大单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-大单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_lg_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-大单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-中单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-中单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_md_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-中单净流入(万元)5日累计之5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='共识-小单净流入(万元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_sum_13d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)13日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_sum_13d_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)13日累计之13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_sum_21d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)21日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_sum_21d_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)21日累计之21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_sum_55d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)55日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_sum_55d_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)55日累计之55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_sum_5d',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='共识-小单净流入(万元)5日累计'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='net_sh_amount_consensus_sum_5d_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='共识-小单净流入(万元)5日累计之5日斜率'),
        ),
    ]
