# Generated by Django 5.0.1 on 2025-07-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0047_remove_stockcyqchipsbj_stock_cyq_c_stock_i_f3dc0e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trendfollowstrategysignallog',
            name='unique_signal_log_entry',
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_strateg_aa7e64_idx',
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_entry_s_706b4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_is_long_462598_idx',
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='trend_follo_is_pull_bd65b2_idx',
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['stock', 'exit_signal_code', 'trade_time'], name='idx_stock_sell_time'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['entry_signal', 'stock'], name='idx_entry_signal_stock'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['trade_time', 'entry_score'], name='idx_trade_time_score'),
        ),
    ]
