# Generated by Django 5.0.1 on 2025-07-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0048_remove_trendfollowstrategysignallog_unique_signal_log_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='stable_platform_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='[趋势策略]识别出的稳固筹码平台价格', max_digits=10, null=True),
        ),
    ]
