# Generated by Django 5.0.1 on 2025-09-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0048_advancedfundflowmetrics_bj_net_lg_amount_consensus_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='active_buy_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='主动买盘压力比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_sum_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)13日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_sum_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)21日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_sum_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)55日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_sum_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)5日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_conviction_buy_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力锁仓买入比'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_conviction_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力信念比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_intensity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_panic_index',
            field=models.FloatField(blank=True, null=True, verbose_name='散户恐慌指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_concentration_index',
            field=models.FloatField(blank=True, null=True, verbose_name='交易集中度指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='active_buy_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='主动买盘压力比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_sum_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)13日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_sum_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)21日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_sum_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)55日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_sum_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)5日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_conviction_buy_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力锁仓买入比'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_conviction_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力信念比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_intensity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_panic_index',
            field=models.FloatField(blank=True, null=True, verbose_name='散户恐慌指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_concentration_index',
            field=models.FloatField(blank=True, null=True, verbose_name='交易集中度指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='active_buy_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='主动买盘压力比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_sum_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)13日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_sum_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)21日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_sum_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)55日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_sum_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)5日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_conviction_buy_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力锁仓买入比'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_conviction_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力信念比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_intensity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_panic_index',
            field=models.FloatField(blank=True, null=True, verbose_name='散户恐慌指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_concentration_index',
            field=models.FloatField(blank=True, null=True, verbose_name='交易集中度指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='active_buy_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='主动买盘压力比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_sum_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)13日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_sum_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)21日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_sum_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)55日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_sum_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)5日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_conviction_buy_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力锁仓买入比'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_conviction_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力信念比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_intensity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_panic_index',
            field=models.FloatField(blank=True, null=True, verbose_name='散户恐慌指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_concentration_index',
            field=models.FloatField(blank=True, null=True, verbose_name='交易集中度指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='active_buy_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='主动买盘压力比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_sum_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)13日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_sum_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)21日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_sum_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)55日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_sum_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='平均每笔成交金额(元)5日累计'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_conviction_buy_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力锁仓买入比'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_conviction_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力信念比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_intensity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流强度比率'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_panic_index',
            field=models.FloatField(blank=True, null=True, verbose_name='散户恐慌指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_concentration_index',
            field=models.FloatField(blank=True, null=True, verbose_name='交易集中度指数'),
        ),
    ]
