# Generated by Django 5.0.1 on 2025-09-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0049_alter_advancedfundflowmetrics_bj_active_buy_pressure_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='strategydailyscore',
            name='trade_action',
            field=models.CharField(choices=[('INITIAL_ENTRY', '首次建仓'), ('ADD_POSITION', '加仓'), ('REDUCE_POSITION', '减仓'), ('PROFIT_EXIT', '止盈清仓'), ('STOP_LOSS_EXIT', '止损清仓'), ('RISK_EXIT', '风险清仓'), ('TREND_BROKEN_EXIT', '趋势破位清仓'), ('STRATEGY_INVALIDATED_EXIT', '战略失效清仓'), ('PROPHET_ENTRY', '先知入场'), ('PROPHET_EXIT', '先知离场'), ('HOLD', '持仓观望'), ('AVOID', '规避'), ('PROCEED_WITH_CAUTION', '谨慎持仓'), ('FORCE_ATTACK', '强力进攻'), ('NO_SIGNAL', '无信号'), ('GAP_UP_SKIPPED', '高开跳过')], default='NO_SIGNAL', help_text='模拟层根据策略规则执行的交易动作 (例如: INITIAL_ENTRY, PROFIT_EXIT, REDUCE_POSITION)', max_length=50, verbose_name='模拟交易动作'),
        ),
    ]
