# Generated by Django 5.0.1 on 2025-07-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0049_trendfollowstrategysignallog_stable_platform_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='idx_stock_sell_time',
        ),
        migrations.RemoveIndex(
            model_name='trendfollowstrategysignallog',
            name='idx_entry_signal_stock',
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['stock', 'timeframe', 'exit_signal_code', 'trade_time'], name='idx_stock_tf_sell_time'),
        ),
        migrations.AddIndex(
            model_name='trendfollowstrategysignallog',
            index=models.Index(fields=['entry_signal', 'timeframe', 'stock'], name='idx_entry_tf_stock'),
        ),
    ]
