# Generated by Django 5.0.1 on 2025-10-08 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0050_alter_strategydailyscore_trade_action'),
    ]
    operations = [
        migrations.CreateModel(
            name='StockPriceLimit_BJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(verbose_name='交易日期')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='昨日收盘价')),
                ('up_limit', models.FloatField(verbose_name='涨停价')),
                ('down_limit', models.FloatField(verbose_name='跌停价')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_limits_bj', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '每日涨跌停价格(北交所)',
                'verbose_name_plural': '每日涨跌停价格(北交所)',
                'db_table': 'stock_price_limit_bj',
                'ordering': ['-trade_time'],
                'abstract': False,
                'unique_together': {('stock', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='StockPriceLimit_CY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(verbose_name='交易日期')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='昨日收盘价')),
                ('up_limit', models.FloatField(verbose_name='涨停价')),
                ('down_limit', models.FloatField(verbose_name='跌停价')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_limits_cy', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '每日涨跌停价格(创业板)',
                'verbose_name_plural': '每日涨跌停价格(创业板)',
                'db_table': 'stock_price_limit_cy',
                'ordering': ['-trade_time'],
                'abstract': False,
                'unique_together': {('stock', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='StockPriceLimit_KC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(verbose_name='交易日期')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='昨日收盘价')),
                ('up_limit', models.FloatField(verbose_name='涨停价')),
                ('down_limit', models.FloatField(verbose_name='跌停价')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_limits_kc', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '每日涨跌停价格(科创板)',
                'verbose_name_plural': '每日涨跌停价格(科创板)',
                'db_table': 'stock_price_limit_kc',
                'ordering': ['-trade_time'],
                'abstract': False,
                'unique_together': {('stock', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='StockPriceLimit_SH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(verbose_name='交易日期')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='昨日收盘价')),
                ('up_limit', models.FloatField(verbose_name='涨停价')),
                ('down_limit', models.FloatField(verbose_name='跌停价')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_limits_sh', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '每日涨跌停价格(沪市)',
                'verbose_name_plural': '每日涨跌停价格(沪市)',
                'db_table': 'stock_price_limit_sh',
                'ordering': ['-trade_time'],
                'abstract': False,
                'unique_together': {('stock', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='StockPriceLimit_SZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateField(verbose_name='交易日期')),
                ('pre_close', models.FloatField(blank=True, null=True, verbose_name='昨日收盘价')),
                ('up_limit', models.FloatField(verbose_name='涨停价')),
                ('down_limit', models.FloatField(verbose_name='跌停价')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_limits_sz', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '每日涨跌停价格(深市)',
                'verbose_name_plural': '每日涨跌停价格(深市)',
                'db_table': 'stock_price_limit_sz',
                'ordering': ['-trade_time'],
                'abstract': False,
                'unique_together': {('stock', 'trade_time')},
            },
        ),
    ]
