# Generated by Django 5.0.1 on 2025-07-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0050_remove_trendfollowstrategysignallog_idx_stock_sell_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='total_winner_rate',
            field=models.FloatField(blank=True, help_text='持仓成本低于当天收盘价的筹码总比例', null=True, verbose_name='总获利盘(%)'),
        ),
    ]
