# Generated by Django 5.0.1 on 2025-07-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0051_advancedchipmetrics_total_winner_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='is_risk_warning',
            field=models.BooleanField(default=False, help_text='是否为风险预警信号 (风险分>0但未触发卖出)'),
        ),
    ]
