# Generated by Django 5.0.1 on 2025-10-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0051_stockpricelimit_bj_stockpricelimit_cy_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='stockpricelimit_bj',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='stockpricelimit_cy',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='stockpricelimit_kc',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='stockpricelimit_sh',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
        migrations.AlterField(
            model_name='stockpricelimit_sz',
            name='trade_time',
            field=models.DateField(db_index=True, verbose_name='交易日期'),
        ),
    ]
