# Generated by Django 5.0.1 on 2025-07-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0052_trendfollowstrategysignallog_is_risk_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='main_force_buy_avg_price',
            field=models.FloatField(blank=True, help_text='当天大单+特大单买入的平均价格', null=True, verbose_name='主力买入均价'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='main_force_net_inflow_amount',
            field=models.FloatField(blank=True, help_text='主力净买入金额，正为净流入，负为净流出', null=True, verbose_name='主力净流入额(元)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='main_force_net_inflow_volume',
            field=models.BigIntegerField(blank=True, help_text='主力净买入股数，正为净流入，负为净流出', null=True, verbose_name='主力净流入量(股)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='main_force_sell_avg_price',
            field=models.FloatField(blank=True, help_text='当天大单+特大单卖出的平均价格', null=True, verbose_name='主力卖出均价'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='retail_buy_avg_price',
            field=models.FloatField(blank=True, help_text='当天小单+中单买入的平均价格', null=True, verbose_name='散户买入均价'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='retail_net_inflow_volume',
            field=models.BigIntegerField(blank=True, help_text='散户净买入股数，正为净流入，负为净流出', null=True, verbose_name='散户净流入量(股)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='retail_sell_avg_price',
            field=models.FloatField(blank=True, help_text='当天小单+中单卖出的平均价格', null=True, verbose_name='散户卖出均价'),
        ),
    ]
