# Generated by Django 5.0.1 on 2025-10-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0054_remove_advancedfundflowmetrics_bj_active_buy_pressure_sum_13d_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(同花顺-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ths_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-同花顺)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='divergence_ts_ths_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(同花顺-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ths_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-同花顺)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='divergence_ts_ths_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(同花顺-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ths_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-同花顺)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='divergence_ts_ths_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(同花顺-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ths_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-同花顺)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='divergence_ts_ths_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(同花顺-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ths_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(同花顺-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-东方财富)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_dc_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-东方财富)5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='分歧度(Tushare-同花顺)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='divergence_ts_ths_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='分歧度(Tushare-同花顺)5日斜率'),
        ),
    ]
