# Generated by Django 5.0.1 on 2025-07-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0054_fundflowdailydc_bj_fundflowdailydc_cy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedchipmetrics',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标(三源合一版)', 'verbose_name_plural': '高级筹码指标(三源合一版)'},
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='main_force_buy_avg_price',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='main_force_net_inflow_volume',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='main_force_sell_avg_price',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='pressure_above_volume',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='prev_20d_close',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='retail_buy_avg_price',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='retail_sell_avg_price',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='support_below_volume',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='turnover_volume_in_cost_range_70pct',
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='consensus_main_force_inflow',
            field=models.BooleanField(default=False, help_text='三大数据源(内部,同花顺,东财)是否均显示主力资金净流入。', verbose_name='共识性主力流入'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='consensus_main_force_outflow',
            field=models.BooleanField(default=False, help_text='三大数据源是否均显示主力资金净流出。', verbose_name='共识性主力流出'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='dc_main_force_net_amount',
            field=models.FloatField(blank=True, help_text='[外部参照] 来自东方财富的公开数据，反映市场共识。', null=True, verbose_name='东方财富主力净流入额(万元)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='fund_flow_divergence',
            field=models.BooleanField(default=False, help_text='三大数据源对主力资金流向的判断是否不一致，可能暗示主力在进行欺骗性操作。', verbose_name='资金流向分歧'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='ths_main_force_net_amount',
            field=models.FloatField(blank=True, help_text='[外部参照] 来自同花顺的公开数据，反映市场共识。', null=True, verbose_name='同花顺主力净流入额(万元)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='concentration_90pct',
            field=models.FloatField(blank=True, help_text='包含90%筹码的最小价格区间宽度 / 平均成本。值越小越集中。', null=True, verbose_name='90%筹码集中度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='concentration_90pct_slope_5d',
            field=models.FloatField(blank=True, help_text='负值表示筹码趋于集中，是积极信号；正值表示发散。', null=True, verbose_name='90%集中度5日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='is_multi_peak',
            field=models.BooleanField(default=False, help_text='当天是否存在多个显著的筹码峰，多峰形态通常意味着持仓成本分散。', verbose_name='是否多峰形态'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='main_force_net_inflow_amount',
            field=models.FloatField(blank=True, help_text='[内部评估] 基于交易所原始数据计算(大单+特大单)。', null=True, verbose_name='主力净流入额(元, 内部)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost',
            field=models.FloatField(blank=True, help_text='当天筹码分布最密集的价格，是市场持仓的核心成本区。', null=True, verbose_name='主筹码峰成本'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_accel_21d',
            field=models.FloatField(blank=True, help_text='中期趋势的健康度变化，正值表示趋势在加速。', null=True, verbose_name='筹码峰成本21日加速度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_accel_5d',
            field=models.FloatField(blank=True, help_text='短期趋势的动量变化，正值表示成本抬升在加速。', null=True, verbose_name='筹码峰成本5日加速度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_21d',
            field=models.FloatField(blank=True, help_text='中期趋势的核心观察指标。', null=True, verbose_name='筹码峰成本21日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_55d',
            field=models.FloatField(blank=True, help_text='长期趋势的核心观察指标。', null=True, verbose_name='筹码峰成本55日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_5d',
            field=models.FloatField(blank=True, help_text='正值表示主力成本在快速抬高。', null=True, verbose_name='筹码峰成本5日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_distance_ratio',
            field=models.FloatField(blank=True, help_text='主次峰成本价的距离 / 主峰成本价。距离越远，结构越不稳定。', null=True, verbose_name='主次峰距离比'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_percent',
            field=models.FloatField(blank=True, help_text='主筹码峰位置的筹码占总筹码的比例，反映了筹码的集中程度。', null=True, verbose_name='主筹码峰占比(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_stability',
            field=models.FloatField(blank=True, help_text='主筹码峰的突出程度(prominence) / 平均占比。值越大越稳定，代表主力控盘能力强。', null=True, verbose_name='筹码峰稳定性'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_strength_ratio',
            field=models.FloatField(blank=True, help_text='次峰突出度 / 主峰突出度。比率越小，主峰的统治力越强。', null=True, verbose_name='主次峰强度比'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_volume',
            field=models.BigIntegerField(blank=True, help_text='主筹码峰位置的绝对成交股数。', null=True, verbose_name='主筹码峰成交量(股)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='pressure_above',
            field=models.FloatField(blank=True, help_text='收盘价上方2%价格区间内的筹码占比，代表直接的短期抛压。', null=True, verbose_name='上方2%套牢盘(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='retail_net_inflow_volume',
            field=models.BigIntegerField(blank=True, help_text='[内部评估] 基于交易所原始数据计算(小单+中单)。', null=True, verbose_name='散户净流入量(股, 内部)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='secondary_peak_cost',
            field=models.FloatField(blank=True, help_text='如果存在，第二大筹码峰的成本价，可能是潜在的压力或支撑位。', null=True, verbose_name='次筹码峰成本'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='support_below',
            field=models.FloatField(blank=True, help_text='收盘价下方2%价格区间内的筹码占比，代表直接的短期支撑。', null=True, verbose_name='下方2%支撑盘(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='total_winner_rate',
            field=models.FloatField(blank=True, help_text='持仓成本低于当天收盘价的筹码总比例，反映市场整体情绪。', null=True, verbose_name='总获利盘(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='winner_rate_long_term',
            field=models.FloatField(blank=True, help_text='持仓成本低于20日前收盘价的筹码比例，代表坚定持有的资金。', null=True, verbose_name='长期锁定盘(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='winner_rate_short_term',
            field=models.FloatField(blank=True, help_text='持仓成本低于收盘价，但高于20日前收盘价的筹码比例，代表近期追涨资金的浮盈情况。', null=True, verbose_name='短期获利盘(%)'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics',
            index=models.Index(fields=['stock'], name='stock_advan_stock_i_2656f7_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics',
            index=models.Index(fields=['trade_time'], name='stock_advan_trade_t_9e5a21_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics',
            index=models.Index(fields=['consensus_main_force_inflow'], name='stock_advan_consens_6373cb_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics',
            index=models.Index(fields=['consensus_main_force_outflow'], name='stock_advan_consens_ff7f75_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics',
            index=models.Index(fields=['fund_flow_divergence'], name='stock_advan_fund_fl_e8aea4_idx'),
        ),
    ]
