# Generated by Django 5.0.1 on 2025-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0055_alter_advancedchipmetrics_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='pressure_above_volume',
            field=models.BigIntegerField(blank=True, help_text='收盘价上方2%价格区间内的绝对筹码股数。', null=True, verbose_name='上方套牢盘绝对量(股)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='prev_20d_close',
            field=models.FloatField(blank=True, help_text='用于计算短期获利盘的基准价格。', null=True, verbose_name='20日前收盘价'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='support_below_volume',
            field=models.BigIntegerField(blank=True, help_text='收盘价下方2%价格区间内的绝对筹码股数。', null=True, verbose_name='下方支撑盘绝对量(股)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='turnover_volume_in_cost_range_70pct',
            field=models.BigIntegerField(blank=True, help_text='当天成交量中，在70%核心成本区内完成的绝对股数，反映核心区换手意愿。', null=True, verbose_name='70%成本区换手量(股)'),
        ),
    ]
