# Generated by Django 5.0.1 on 2025-10-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0055_advancedfundflowmetrics_bj_divergence_ths_dc_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='avg_order_value_norm_price_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_flow_impact_ratio_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trade_granularity_impact_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='avg_order_value_norm_price_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_flow_impact_ratio_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trade_granularity_impact_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='avg_order_value_norm_price_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_flow_impact_ratio_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trade_granularity_impact_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='avg_order_value_norm_price_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_flow_impact_ratio_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trade_granularity_impact_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='avg_order_value_norm_price_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='价格归一化平均订单价值5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_flow_impact_ratio_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='主力资金流影响力5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trade_granularity_impact_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='交易颗粒度影响力5日斜率'),
        ),
    ]
