# Generated by Django 5.0.1 on 2025-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0056_advancedchipmetrics_pressure_above_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='chip_health_score',
            field=models.FloatField(blank=True, help_text='综合控盘度、利润质量、集中度等多个维度得出的最终评分，全面评估当前筹码结构的健康状况。', null=True, verbose_name='筹码健康分(0-100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='chip_zscore',
            field=models.FloatField(blank=True, help_text='收盘价在整个筹码分布中的标准分位置。衡量股价相对于整体持仓成本的偏离度。绝对值越大，偏离越远。', null=True, verbose_name='筹码Z-Score'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_absorption_intensity',
            field=models.FloatField(blank=True, help_text='在主筹码峰价格区间内的换手量 / 当日总换手量。值越高，代表主力在核心区吸筹/换手越坚决。', null=True, verbose_name='筹码峰吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='peak_control_ratio',
            field=models.FloatField(blank=True, help_text='主筹码峰的绝对股数 / 流通股本。衡量主力对核心阵地的绝对控制力。', null=True, verbose_name='筹码峰控盘比(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='price_to_peak_ratio',
            field=models.FloatField(blank=True, help_text='收盘价 / 主筹码峰成本。 >1 表示股价脱离成本区，<1 表示被压制。', null=True, verbose_name='股价/筹码峰成本比'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='winner_avg_cost',
            field=models.FloatField(blank=True, help_text='所有获利筹码的加权平均成本价。', null=True, verbose_name='获利盘平均成本'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='winner_profit_margin',
            field=models.FloatField(blank=True, help_text='(收盘价 - 获利盘均价) / 获利盘均价。衡量获利盘的平均利润厚度，值越高，持股心态越稳。', null=True, verbose_name='获利盘安全垫(%)'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics',
            index=models.Index(fields=['chip_health_score'], name='stock_advan_chip_he_0c3c43_idx'),
        ),
    ]
