# Generated by Django 5.0.1 on 2025-07-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0057_advancedchipmetrics_chip_health_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='fund_flow_data_source_count',
            field=models.IntegerField(blank=True, help_text='当天可用的资金流数据源总数(1-3)。', null=True, verbose_name='资金流有效源数量'),
        ),
    ]
