# Generated by Django 5.0.1 on 2025-07-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0058_advancedchipmetrics_fund_flow_data_source_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='chip_fault_strength',
            field=models.FloatField(blank=True, help_text='收盘价脱离主筹码峰的相对距离((收盘价-峰成本)/峰成本)，值越大，脱离越远。', null=True, verbose_name='筹码断层强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='chip_fault_vacuum_percent',
            field=models.FloatField(blank=True, help_text='主筹码峰与收盘价之间的筹码占比，值越小，代表上涨过程越轻松，抛压越小。', null=True, verbose_name='断层真空区筹码占比(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='is_chip_fault_formed',
            field=models.BooleanField(default=False, help_text='综合断层强度和真空度判断是否形成有效的筹码断层结构，是极强的看涨信号。', verbose_name='是否形成筹码断层'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics',
            index=models.Index(fields=['is_chip_fault_formed'], name='stock_advan_is_chip_360572_idx'),
        ),
    ]
