# Generated by Django 5.0.1 on 2025-07-28 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0059_advancedchipmetrics_chip_fault_strength_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMinuteData_1_BJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(db_index=True, verbose_name='交易时间')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('vol', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='成交金额')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='minute_data_1_bj', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': 'A股分钟行情',
                'verbose_name_plural': 'A股分钟行情',
                'db_table': 'stock_time_trade_minute_1_bj',
                'ordering': ['-trade_time'],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='StockMinuteData_1_CY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(db_index=True, verbose_name='交易时间')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('vol', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='成交金额')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='minute_data_1_cy', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': 'A股分钟行情',
                'verbose_name_plural': 'A股分钟行情',
                'db_table': 'stock_time_trade_minute_1_cy',
                'ordering': ['-trade_time'],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='StockMinuteData_1_KC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(db_index=True, verbose_name='交易时间')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('vol', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='成交金额')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='minute_data_1_kc', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': 'A股分钟行情',
                'verbose_name_plural': 'A股分钟行情',
                'db_table': 'stock_time_trade_minute_1_kc',
                'ordering': ['-trade_time'],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='StockMinuteData_1_SH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(db_index=True, verbose_name='交易时间')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('vol', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='成交金额')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='minute_data_1_sh', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': 'A股分钟行情',
                'verbose_name_plural': 'A股分钟行情',
                'db_table': 'stock_time_trade_minute_1_sh',
                'ordering': ['-trade_time'],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
        migrations.CreateModel(
            name='StockMinuteData_1_SZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(db_index=True, verbose_name='交易时间')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='开盘价')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='最高价')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='最低价')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='收盘价')),
                ('vol', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='成交金额')),
                ('stock', models.ForeignKey(db_column='stock_code', on_delete=django.db.models.deletion.CASCADE, related_name='minute_data_1_sz', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': 'A股分钟行情',
                'verbose_name_plural': 'A股分钟行情',
                'db_table': 'stock_time_trade_minute_1_sz',
                'ordering': ['-trade_time'],
                'unique_together': {('stock', 'trade_time')},
            },
        ),
    ]
