# Generated by Django 5.0.1 on 2025-07-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0060_stockminutedata_1_bj_stockminutedata_1_cy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='risk_score',
            field=models.FloatField(default=0.0, help_text='风险信号的综合得分'),
        ),
    ]
