# Generated by Django 5.0.1 on 2025-07-28 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0061_trendfollowstrategysignallog_risk_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStockTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('HOLDING', '持仓中'), ('SOLD', '已平仓')], db_index=True, default='HOLDING', max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=3, help_text='建仓价格 (来自建仓信号)', max_digits=10)),
                ('entry_date', models.DateTimeField(help_text='建仓日期 (来自建仓信号)')),
                ('entry_score', models.FloatField(default=0.0, help_text='建仓时的进攻分数')),
                ('latest_price', models.DecimalField(blank=True, decimal_places=3, help_text='最新收盘价', max_digits=10, null=True)),
                ('latest_date', models.DateTimeField(blank=True, help_text='最新信号日期', null=True)),
                ('holding_health_score', models.FloatField(default=0.0, help_text='最新的持仓健康分')),
                ('score_change_vs_entry', models.FloatField(default=0.0, help_text='最新分数相比建仓时的变化量')),
                ('profit_loss_pct', models.FloatField(default=0.0, help_text='当前持仓的浮动盈亏百分比')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=3, help_text='平仓价格', max_digits=10, null=True)),
                ('exit_date', models.DateTimeField(blank=True, help_text='平仓日期', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_log', models.ForeignKey(help_text='关联的建仓信号日志', on_delete=django.db.models.deletion.CASCADE, related_name='entry_tracker', to='stock_models.trendfollowstrategysignallog')),
                ('exit_log', models.ForeignKey(blank=True, help_text='关联的平仓信号日志', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_tracker', to='stock_models.trendfollowstrategysignallog')),
                ('latest_log', models.ForeignKey(blank=True, help_text='关联的最新信号日志 (每日更新)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_tracker', to='stock_models.trendfollowstrategysignallog')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_trackers', to='stock_models.stockinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '自选股持仓追踪器',
                'verbose_name_plural': '自选股持仓追踪器',
                'db_table': 'favorite_stock_tracker',
                'ordering': ['-entry_date'],
                'unique_together': {('user', 'stock', 'entry_log')},
            },
        ),
    ]
