# Generated by Django 5.0.1 on 2025-10-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0061_advancedstructuralmetrics_bj_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='auction_conviction_index',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价强度指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='auction_price_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价价格冲击'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='auction_volume_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价成交量占比'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='auction_conviction_index',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价强度指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='auction_price_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价价格冲击'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='auction_volume_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价成交量占比'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='auction_conviction_index',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价强度指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='auction_price_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价价格冲击'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='auction_volume_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价成交量占比'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='auction_conviction_index',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价强度指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='auction_price_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价价格冲击'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='auction_volume_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价成交量占比'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='auction_conviction_index',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价强度指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='auction_price_impact',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价价格冲击'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='auction_volume_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='集合竞价成交量占比'),
        ),
    ]
