# Generated by Django 5.0.1 on 2025-10-26 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0062_advancedstructuralmetrics_bj_auction_conviction_index_and_more'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='advancedchipmetrics_bj',
            name='long_term_chips_unlocked_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_cy',
            name='long_term_chips_unlocked_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_kc',
            name='long_term_chips_unlocked_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_sh',
            name='long_term_chips_unlocked_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_sz',
            name='long_term_chips_unlocked_ratio',
        ),
    ]
