# Generated by Django 5.0.1 on 2025-07-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0062_favoritestocktracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='holding_health_score',
            field=models.FloatField(blank=True, default=0.0, help_text='持仓健康分 (每日计算)', null=True),
        ),
    ]
