# Generated by Django 5.0.1 on 2025-08-01 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0063_trendfollowstrategysignallog_holding_health_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklevel5data',
            name='order_diff',
        ),
        migrations.RemoveField(
            model_name='stocklevel5data',
            name='order_ratio',
        ),
        migrations.CreateModel(
            name='StockTickData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价')),
                ('volume', models.IntegerField(verbose_name='成交量(股)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额(元)')),
                ('type', models.CharField(help_text='买盘/卖盘/中性', max_length=10, verbose_name='类型')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_data', to='stock_models.stockinfo')),
            ],
            options={
                'db_table': 'stock_tick_data',
                'ordering': ['-trade_time'],
                'unique_together': {('stock', 'trade_time', 'price', 'volume')},
            },
        ),
    ]
