# Generated by Django 5.0.1 on 2025-08-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0064_remove_stocklevel5data_order_diff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritestocktracker',
            name='health_change_summary',
            field=models.JSONField(blank=True, default=dict, help_text='结构化的攻防健康度变化摘要', null=True),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='health_change_summary',
            field=models.JSONField(blank=True, default=dict, help_text='当日的攻防健康度变化摘要', null=True),
        ),
        migrations.AddField(
            model_name='trendfollowstrategysignallog',
            name='risk_change_summary',
            field=models.JSONField(blank=True, default=dict, help_text='当日的风险变化摘要', null=True),
        ),
        migrations.AlterField(
            model_name='trendfollowstrategysignallog',
            name='holding_health_score',
            field=models.FloatField(blank=True, default=0.0, help_text='【已废弃】持仓健康分 (每日计算)', null=True),
        ),
    ]
