# Generated by Django 5.0.1 on 2025-08-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0065_favoritestocktracker_health_change_summary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedchipmetrics',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标(升维净化版)', 'verbose_name_plural': '高级筹码指标(升维净化版)'},
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics',
            name='stock_advan_consens_6373cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics',
            name='stock_advan_consens_ff7f75_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedchipmetrics',
            name='stock_advan_fund_fl_e8aea4_idx',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='consensus_main_force_inflow',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='consensus_main_force_outflow',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='dc_main_force_net_amount',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='fund_flow_data_source_count',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='fund_flow_divergence',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='main_force_net_inflow_amount',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='retail_net_inflow_volume',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics',
            name='ths_main_force_net_amount',
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='turnover_at_peak_ratio',
            field=models.FloatField(blank=True, help_text='当日成交量中，发生在主筹码峰价格区间的成交量占比。值越高，代表主力在核心阵地的交战/换手越激烈。', null=True, verbose_name='主峰成交占比(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='turnover_from_losers_ratio',
            field=models.FloatField(blank=True, help_text='当日成交量中，由套牢盘(成本高于收盘价)卖出所贡献的占比。值越高，代表恐慌/割肉盘越重。', null=True, verbose_name='套牢盘割肉占比(%)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics',
            name='turnover_from_winners_ratio',
            field=models.FloatField(blank=True, help_text='当日成交量中，由获利盘(成本低于收盘价)卖出所贡献的占比。值越高，代表短期抛售压力越大。', null=True, verbose_name='获利盘抛压占比(%)'),
        ),
    ]
