# Generated by Django 5.0.1 on 2025-11-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0066_remove_advancedchipmetrics_bj_chip_fault_traversal_conviction_and_more'),
    ]
    operations = [
        migrations.AddIndex(
            model_name='advancedchipmetrics_bj',
            index=models.Index(fields=['structural_resilience_index'], name='stock_advan_structu_40ea25_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_cy',
            index=models.Index(fields=['structural_resilience_index'], name='stock_advan_structu_95cf7d_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_kc',
            index=models.Index(fields=['structural_resilience_index'], name='stock_advan_structu_a6b44e_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_sh',
            index=models.Index(fields=['structural_resilience_index'], name='stock_advan_structu_5af9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_sz',
            index=models.Index(fields=['structural_resilience_index'], name='stock_advan_structu_0b249a_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_bj',
            index=models.Index(fields=['main_force_price_impact_ratio'], name='stock_advan_main_fo_9a6a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_bj',
            index=models.Index(fields=['mf_retail_battle_intensity'], name='stock_advan_mf_reta_5ed17e_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_cy',
            index=models.Index(fields=['main_force_price_impact_ratio'], name='stock_advan_main_fo_b08962_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_cy',
            index=models.Index(fields=['mf_retail_battle_intensity'], name='stock_advan_mf_reta_cb1e08_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_kc',
            index=models.Index(fields=['main_force_price_impact_ratio'], name='stock_advan_main_fo_b6de30_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_kc',
            index=models.Index(fields=['mf_retail_battle_intensity'], name='stock_advan_mf_reta_c0119b_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_sh',
            index=models.Index(fields=['main_force_price_impact_ratio'], name='stock_advan_main_fo_40402e_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_sh',
            index=models.Index(fields=['mf_retail_battle_intensity'], name='stock_advan_mf_reta_0e12cf_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_sz',
            index=models.Index(fields=['main_force_price_impact_ratio'], name='stock_advan_main_fo_005341_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_sz',
            index=models.Index(fields=['mf_retail_battle_intensity'], name='stock_advan_mf_reta_799585_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_bj',
            index=models.Index(fields=['intraday_energy_density'], name='stock_advan_intrada_539f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_bj',
            index=models.Index(fields=['divergence_conviction_score'], name='stock_advan_diverge_428a13_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_cy',
            index=models.Index(fields=['intraday_energy_density'], name='stock_advan_intrada_1f6f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_cy',
            index=models.Index(fields=['divergence_conviction_score'], name='stock_advan_diverge_582f42_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_kc',
            index=models.Index(fields=['intraday_energy_density'], name='stock_advan_intrada_286ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_kc',
            index=models.Index(fields=['divergence_conviction_score'], name='stock_advan_diverge_c7f96a_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_sh',
            index=models.Index(fields=['intraday_energy_density'], name='stock_advan_intrada_9d1fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_sh',
            index=models.Index(fields=['divergence_conviction_score'], name='stock_advan_diverge_ae664c_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_sz',
            index=models.Index(fields=['intraday_energy_density'], name='stock_advan_intrada_0388df_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedstructuralmetrics_sz',
            index=models.Index(fields=['divergence_conviction_score'], name='stock_advan_diverge_00d826_idx'),
        ),
    ]
