# Generated by Django 5.0.1 on 2025-08-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0066_alter_advancedchipmetrics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advancedchipmetrics',
            options={'ordering': ['-trade_time'], 'verbose_name': '高级筹码指标(精度升级版)', 'verbose_name_plural': '高级筹码指标(精度升级版)'},
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='chip_fault_strength',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='筹码断层强度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='chip_fault_vacuum_percent',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='断层真空区筹码占比(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='chip_health_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='筹码健康分(0-100)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='chip_zscore',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='股价在筹码分布中的标准分位置。', max_digits=12, null=True, verbose_name='筹码Z-Score'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='concentration_90pct',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='值越小越集中。', max_digits=12, null=True, verbose_name='90%筹码集中度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='concentration_90pct_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='负值表示筹码趋于集中。', max_digits=18, null=True, verbose_name='90%集中度5日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='is_chip_fault_formed',
            field=models.BooleanField(default=False, help_text='极强的看涨信号。', verbose_name='是否形成筹码断层'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='is_multi_peak',
            field=models.BooleanField(default=False, help_text='持仓成本是否分散。', verbose_name='是否多峰形态'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_absorption_intensity',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主峰区间换手量 / 总换手量。', max_digits=12, null=True, verbose_name='筹码峰吸筹强度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_control_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主筹码峰股数 / 流通股本。', max_digits=12, null=True, verbose_name='筹码峰控盘比(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='当天筹码分布最密集的价格，是市场持仓的核心成本区。', max_digits=12, null=True, verbose_name='主筹码峰成本'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_accel_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本21日加速度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_accel_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本5日加速度'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_13d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本13日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_144d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本144日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_21d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本21日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_34d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本34日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_55d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本55日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_5d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本5日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_89d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本89日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_cost_slope_8d',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='筹码峰成本8日斜率'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_distance_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='距离越远，结构越不稳定。', max_digits=12, null=True, verbose_name='主次峰距离比'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_percent',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主筹码峰位置的筹码占总筹码的比例。', max_digits=10, null=True, verbose_name='主筹码峰占比(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_stability',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='值越大越稳定，代表主力控盘能力强。', max_digits=12, null=True, verbose_name='筹码峰稳定性'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='peak_strength_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='比率越小，主峰的统治力越强。', max_digits=12, null=True, verbose_name='主次峰强度比'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='pressure_above',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='代表直接的短期抛压。', max_digits=10, null=True, verbose_name='上方2%套牢盘(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='pressure_above_volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='上方套牢盘绝对量(股)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='prev_20d_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='20日前收盘价'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='price_to_peak_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True, verbose_name='股价/筹码峰成本比'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='secondary_peak_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='潜在的压力或支撑位。', max_digits=12, null=True, verbose_name='次筹码峰成本'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='support_below',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='代表直接的短期支撑。', max_digits=10, null=True, verbose_name='下方2%支撑盘(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='support_below_volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='下方支撑盘绝对量(股)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='total_winner_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='反映市场整体情绪。', max_digits=10, null=True, verbose_name='总获利盘(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='turnover_at_peak_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='主峰区间的交战激烈程度。', max_digits=10, null=True, verbose_name='主峰成交占比(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='turnover_from_losers_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='恐慌/割肉盘轻重。', max_digits=10, null=True, verbose_name='套牢盘割肉占比(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='turnover_from_winners_ratio',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='短期抛售压力大小。', max_digits=10, null=True, verbose_name='获利盘抛压占比(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='turnover_volume_in_cost_range_70pct',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='70%成本区换手量(股)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='winner_avg_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='获利盘平均成本'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='winner_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='衡量获利盘的平均利润厚度。', max_digits=12, null=True, verbose_name='获利盘安全垫(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='winner_rate_long_term',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='代表坚定持有的资金。', max_digits=10, null=True, verbose_name='长期锁定盘(%)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics',
            name='winner_rate_short_term',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='代表近期追涨资金的浮盈情况。', max_digits=10, null=True, verbose_name='短期获利盘(%)'),
        ),
    ]
