# Generated by Django 5.0.1 on 2025-08-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0067_alter_advancedchipmetrics_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockanalysisresulttrendfollowing',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockanalysisresulttrendfollowing',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='stockscoreanalysis',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stockscoreanalysis',
            name='stock',
        ),
        migrations.AlterUniqueTogether(
            name='trendfollowstrategyreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trendfollowstrategyreport',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='trendfollowstrategystate',
            name='stock',
        ),
        migrations.DeleteModel(
            name='MonthlyTrendStrategyReport',
        ),
        migrations.DeleteModel(
            name='StockAnalysisResultTrendFollowing',
        ),
        migrations.DeleteModel(
            name='StockScoreAnalysis',
        ),
        migrations.DeleteModel(
            name='TrendFollowStrategyReport',
        ),
        migrations.DeleteModel(
            name='TrendFollowStrategyState',
        ),
    ]
