# Generated by Django 5.0.1 on 2025-11-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0068_remove_advancedchipmetrics_bj_capitulation_absorption_quality_and_more'),
    ]
    operations = [
        migrations.AddIndex(
            model_name='advancedchipmetrics_bj',
            index=models.Index(fields=['peak_separation_ratio'], name='stock_advan_peak_se_952e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_bj',
            index=models.Index(fields=['dominant_peak_solidity'], name='stock_advan_dominan_0a518c_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_cy',
            index=models.Index(fields=['peak_separation_ratio'], name='stock_advan_peak_se_173b08_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_cy',
            index=models.Index(fields=['dominant_peak_solidity'], name='stock_advan_dominan_9c94ef_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_kc',
            index=models.Index(fields=['peak_separation_ratio'], name='stock_advan_peak_se_f37350_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_kc',
            index=models.Index(fields=['dominant_peak_solidity'], name='stock_advan_dominan_57336e_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_sh',
            index=models.Index(fields=['peak_separation_ratio'], name='stock_advan_peak_se_5918ff_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_sh',
            index=models.Index(fields=['dominant_peak_solidity'], name='stock_advan_dominan_9d79ef_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_sz',
            index=models.Index(fields=['peak_separation_ratio'], name='stock_advan_peak_se_4ade7a_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedchipmetrics_sz',
            index=models.Index(fields=['dominant_peak_solidity'], name='stock_advan_dominan_6096b3_idx'),
        ),
    ]
