# Generated by Django 5.0.1 on 2025-11-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0069_advancedchipmetrics_bj_stock_advan_peak_se_952e3a_idx_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价意图信号'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='auction_pressure_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价压力比'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_fusion_indicator',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间融合指标'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='peak_separation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间分离强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价意图信号'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='auction_pressure_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价压力比'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_fusion_indicator',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间融合指标'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='peak_separation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间分离强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价意图信号'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='auction_pressure_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价压力比'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_fusion_indicator',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间融合指标'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='peak_separation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间分离强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价意图信号'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='auction_pressure_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价压力比'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_fusion_indicator',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间融合指标'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='peak_separation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间分离强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价意图信号'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='auction_pressure_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='虚拟竞价压力比'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_fusion_indicator',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间融合指标'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='peak_separation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='峰间分离强度'),
        ),
    ]
