# Generated by Django 5.0.1 on 2025-08-03 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0069_playbook_signalplaybookdetail_tradingsignal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- 代码修改开始 ---
        # [修改原因] 修复 FieldDoesNotExist 错误，调整迁移操作的执行顺序。
        
        # 步骤1: 先添加所有新字段
        migrations.AddField(
            model_name='favoritestocktracker',
            name='entry_signal',
            field=models.ForeignKey(blank=True, help_text='关联的建仓交易信号', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_tracker', to='stock_models.tradingsignal'),
        ),
        migrations.AddField(
            model_name='favoritestocktracker',
            name='exit_signal',
            field=models.ForeignKey(blank=True, help_text='关联的平仓交易信号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_tracker', to='stock_models.tradingsignal'),
        ),
        migrations.AddField(
            model_name='favoritestocktracker',
            name='latest_signal',
            field=models.ForeignKey(blank=True, help_text='关联的最新信号日志 (每日更新)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_tracker', to='stock_models.tradingsignal'),
        ),

        # 步骤2: 在新字段添加后，再修改唯一约束
        migrations.AlterUniqueTogether(
            name='favoritestocktracker',
            unique_together={('user', 'stock', 'entry_signal')},
        ),
        
        # 步骤3: 修改其他字段
        migrations.AlterField(
            model_name='favoritestocktracker',
            name='entry_date',
            field=models.DateTimeField(blank=True, help_text='建仓日期', null=True),
        ),
        migrations.AlterField(
            model_name='favoritestocktracker',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='建仓价格', max_digits=10, null=True),
        ),

        # 步骤4: 最后移除所有旧字段
        migrations.RemoveField(
            model_name='favoritestocktracker',
            name='entry_log',
        ),
        migrations.RemoveField(
            model_name='favoritestocktracker',
            name='entry_score',
        ),
        migrations.RemoveField(
            model_name='favoritestocktracker',
            name='exit_log',
        ),
        migrations.RemoveField(
            model_name='favoritestocktracker',
            name='holding_health_score',
        ),
        migrations.RemoveField(
            model_name='favoritestocktracker',
            name='latest_log',
        ),
        migrations.RemoveField(
            model_name='favoritestocktracker',
            name='profit_loss_pct',
        ),
        migrations.RemoveField(
            model_name='favoritestocktracker',
            name='score_change_vs_entry',
        ),
        # --- 代码修改结束 ---
    ]
