# Generated by Django 5.0.1 on 2025-08-04 01:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0070_alter_positiontracker_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='positiontracker',
            table='strategy_position_tracker',
        ),
        migrations.AlterModelOptions(
            name='positiontracker',
            options={'ordering': ['-updated_at'], 'verbose_name': '策略持仓追踪器', 'verbose_name_plural': '策略持仓追踪器'},
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='记录创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='entry_date',
            field=models.DateTimeField(blank=True, help_text='建仓或初次观察时的日期', null=True),
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='entry_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='建仓或初次观察时的价格', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='entry_signal',
            field=models.ForeignKey(blank=True, help_text="关联的建仓交易信号 (对于'观察中'状态可为空)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_positions', to='stock_models.tradingsignal'),
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='exit_date',
            field=models.DateTimeField(blank=True, help_text='平仓日期', null=True),
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='平仓价格', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='exit_signal',
            field=models.ForeignKey(blank=True, help_text='关联的平仓交易信号', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_positions', to='stock_models.tradingsignal'),
        ),
        migrations.AddField(
            model_name='positiontracker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='记录最后更新时间'),
        ),
        migrations.AlterField(
            model_name='positiontracker',
            name='status',
            field=models.CharField(choices=[('WATCHING', '观察中'), ('HOLDING', '持仓中'), ('SOLD', '已平仓')], db_index=True, default='WATCHING', help_text='当前追踪状态', max_length=10),
        ),
        migrations.AlterField(
            model_name='positiontracker',
            name='stock',
            field=models.ForeignKey(help_text='关联的股票', on_delete=django.db.models.deletion.CASCADE, related_name='position_trackers', to='stock_models.stockinfo'),
        ),
        migrations.AlterField(
            model_name='positiontracker',
            name='user',
            field=models.ForeignKey(help_text='关联的用户', on_delete=django.db.models.deletion.CASCADE, related_name='position_trackers', to=settings.AUTH_USER_MODEL),
        ),

    ]
