# Generated by Django 5.0.1 on 2025-11-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0070_advancedchipmetrics_bj_auction_intent_signal_and_more'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='advancedchipmetrics_bj',
            name='auction_battle_signal',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_bj',
            name='auction_pressure_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_cy',
            name='auction_battle_signal',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_cy',
            name='auction_pressure_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_kc',
            name='auction_battle_signal',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_kc',
            name='auction_pressure_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_sh',
            name='auction_battle_signal',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_sh',
            name='auction_pressure_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_sz',
            name='auction_battle_signal',
        ),
        migrations.RemoveField(
            model_name='advancedchipmetrics_sz',
            name='auction_pressure_ratio',
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='auction_closing_position',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价收盘位置(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='auction_closing_position',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价收盘位置(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='auction_closing_position',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价收盘位置(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='auction_closing_position',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价收盘位置(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='auction_closing_position',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价收盘位置(-100~100)'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics_bj',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价意图信号'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics_cy',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价意图信号'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics_kc',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价意图信号'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics_sh',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价意图信号'),
        ),
        migrations.AlterField(
            model_name='advancedchipmetrics_sz',
            name='auction_intent_signal',
            field=models.FloatField(blank=True, null=True, verbose_name='竞价意图信号'),
        ),
    ]
