# Generated by Django 5.0.1 on 2025-11-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0071_remove_advancedchipmetrics_bj_auction_battle_signal_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='dip_absorption_power',
            field=models.FloatField(blank=True, null=True, verbose_name='逢低吸筹力度'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='dip_absorption_power',
            field=models.FloatField(blank=True, null=True, verbose_name='逢低吸筹力度'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='dip_absorption_power',
            field=models.FloatField(blank=True, null=True, verbose_name='逢低吸筹力度'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='dip_absorption_power',
            field=models.FloatField(blank=True, null=True, verbose_name='逢低吸筹力度'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='dip_absorption_power',
            field=models.FloatField(blank=True, null=True, verbose_name='逢低吸筹力度'),
        ),
    ]
