# Generated by Django 5.0.1 on 2025-11-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0072_alter_advancedfundflowmetrics_bj_dip_absorption_power_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='closing_momentum_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘动能指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='trend_quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势质量分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='volume_structure_skew',
            field=models.FloatField(blank=True, null=True, verbose_name='成交结构偏度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='closing_momentum_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘动能指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='trend_quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势质量分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='volume_structure_skew',
            field=models.FloatField(blank=True, null=True, verbose_name='成交结构偏度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='closing_momentum_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘动能指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='trend_quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势质量分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='volume_structure_skew',
            field=models.FloatField(blank=True, null=True, verbose_name='成交结构偏度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='closing_momentum_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘动能指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='trend_quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势质量分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='volume_structure_skew',
            field=models.FloatField(blank=True, null=True, verbose_name='成交结构偏度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='closing_momentum_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘动能指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='trend_quality_score',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势质量分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='volume_structure_skew',
            field=models.FloatField(blank=True, null=True, verbose_name='成交结构偏度'),
        ),
        migrations.AlterField(
            model_name='advancedstructuralmetrics_bj',
            name='auction_impact_score',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘缺口强度'),
        ),
        migrations.AlterField(
            model_name='advancedstructuralmetrics_cy',
            name='auction_impact_score',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘缺口强度'),
        ),
        migrations.AlterField(
            model_name='advancedstructuralmetrics_kc',
            name='auction_impact_score',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘缺口强度'),
        ),
        migrations.AlterField(
            model_name='advancedstructuralmetrics_sh',
            name='auction_impact_score',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘缺口强度'),
        ),
        migrations.AlterField(
            model_name='advancedstructuralmetrics_sz',
            name='auction_impact_score',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘缺口强度'),
        ),
    ]
