# Generated by Django 5.0.1 on 2025-11-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0073_advancedstructuralmetrics_bj_closing_momentum_index_and_more'),
    ]
    operations = [
        migrations.CreateModel(
            name='StockTickData_BJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价')),
                ('volume', models.IntegerField(verbose_name='成交量(手)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额(元)')),
                ('type', models.CharField(help_text='买盘/卖盘/中性', max_length=10, verbose_name='类型')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_data_bj', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '逐笔交易数据-北京',
                'verbose_name_plural': '逐笔交易数据-北京',
                'db_table': 'stock_tick_data_bj',
                'ordering': ['-trade_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTickData_CY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价')),
                ('volume', models.IntegerField(verbose_name='成交量(手)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额(元)')),
                ('type', models.CharField(help_text='买盘/卖盘/中性', max_length=10, verbose_name='类型')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_data_cy', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '逐笔交易数据-创业板',
                'verbose_name_plural': '逐笔交易数据-创业板',
                'db_table': 'stock_tick_data_cy',
                'ordering': ['-trade_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTickData_KC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价')),
                ('volume', models.IntegerField(verbose_name='成交量(手)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额(元)')),
                ('type', models.CharField(help_text='买盘/卖盘/中性', max_length=10, verbose_name='类型')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_data_kc', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '逐笔交易数据-科创板',
                'verbose_name_plural': '逐笔交易数据-科创板',
                'db_table': 'stock_tick_data_kc',
                'ordering': ['-trade_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTickData_SH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价')),
                ('volume', models.IntegerField(verbose_name='成交量(手)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额(元)')),
                ('type', models.CharField(help_text='买盘/卖盘/中性', max_length=10, verbose_name='类型')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_data_sh', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '逐笔交易数据-上海',
                'verbose_name_plural': '逐笔交易数据-上海',
                'db_table': 'stock_tick_data_sh',
                'ordering': ['-trade_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockTickData_SZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_time', models.DateTimeField(verbose_name='交易时间')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价')),
                ('volume', models.IntegerField(verbose_name='成交量(手)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='成交额(元)')),
                ('type', models.CharField(help_text='买盘/卖盘/中性', max_length=10, verbose_name='类型')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tick_data_sz', to='stock_models.stockinfo', verbose_name='股票')),
            ],
            options={
                'verbose_name': '逐笔交易数据-深圳',
                'verbose_name_plural': '逐笔交易数据-深圳',
                'db_table': 'stock_tick_data_sz',
                'ordering': ['-trade_time'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StockTickData',
        ),
        migrations.AddIndex(
            model_name='stocktickdata_bj',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_tick__stock_i_47cc6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktickdata_bj',
            unique_together={('stock', 'trade_time', 'price', 'volume')},
        ),
        migrations.AddIndex(
            model_name='stocktickdata_cy',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_tick__stock_i_c7b7f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktickdata_cy',
            unique_together={('stock', 'trade_time', 'price', 'volume')},
        ),
        migrations.AddIndex(
            model_name='stocktickdata_kc',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_tick__stock_i_13ee23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktickdata_kc',
            unique_together={('stock', 'trade_time', 'price', 'volume')},
        ),
        migrations.AddIndex(
            model_name='stocktickdata_sh',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_tick__stock_i_e10b5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktickdata_sh',
            unique_together={('stock', 'trade_time', 'price', 'volume')},
        ),
        migrations.AddIndex(
            model_name='stocktickdata_sz',
            index=models.Index(fields=['stock', 'trade_time'], name='stock_tick__stock_i_75053e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktickdata_sz',
            unique_together={('stock', 'trade_time', 'price', 'volume')},
        ),
    ]
