# Generated by Django 5.0.1 on 2025-11-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0074_stocktickdata_bj_stocktickdata_cy_stocktickdata_kc_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='price_volume_entropy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格成交量熵'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='price_volume_entropy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格成交量熵'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='price_volume_entropy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格成交量熵'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='price_volume_entropy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格成交量熵'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='price_volume_entropy',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='价格成交量熵'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='hidden_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='隐蔽吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='主力订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='microstructure_efficiency_index',
            field=models.FloatField(blank=True, null=True, verbose_name='微观结构效率指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='retail_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='散户订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='hidden_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='隐蔽吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='主力订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='microstructure_efficiency_index',
            field=models.FloatField(blank=True, null=True, verbose_name='微观结构效率指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='retail_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='散户订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='hidden_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='隐蔽吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='主力订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='microstructure_efficiency_index',
            field=models.FloatField(blank=True, null=True, verbose_name='微观结构效率指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='retail_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='散户订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='hidden_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='隐蔽吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='主力订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='microstructure_efficiency_index',
            field=models.FloatField(blank=True, null=True, verbose_name='微观结构效率指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='retail_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='散户订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='hidden_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='隐蔽吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='主力订单流失衡'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='microstructure_efficiency_index',
            field=models.FloatField(blank=True, null=True, verbose_name='微观结构效率指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='retail_ofi',
            field=models.FloatField(blank=True, null=True, verbose_name='散户订单流失衡'),
        ),
    ]
