# Generated by Django 5.0.1 on 2025-11-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0075_advancedchipmetrics_bj_price_volume_entropy_and_more'),
    ]
    operations = [
        migrations.AlterField(
            model_name='stocktickdata_bj',
            name='type',
            field=models.CharField(help_text="买盘'B'/卖盘'S'/中性'M'", max_length=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='stocktickdata_cy',
            name='type',
            field=models.CharField(help_text="买盘'B'/卖盘'S'/中性'M'", max_length=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='stocktickdata_kc',
            name='type',
            field=models.CharField(help_text="买盘'B'/卖盘'S'/中性'M'", max_length=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='stocktickdata_sh',
            name='type',
            field=models.CharField(help_text="买盘'B'/卖盘'S'/中性'M'", max_length=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='stocktickdata_sz',
            name='type',
            field=models.CharField(help_text="买盘'B'/卖盘'S'/中性'M'", max_length=1, verbose_name='类型'),
        ),
    ]
