# Generated by Django 5.0.1 on 2025-11-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0079_remove_advancedchipmetrics_bj_stock_advan_structu_40ea25_idx_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='buy_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='买方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='order_flow_imbalance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='订单流失衡分数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='sell_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='vpin_score',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN得分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='vwap_mean_reversion_corr',
            field=models.FloatField(blank=True, null=True, verbose_name='VWAP均值回归相关性'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='buy_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='买方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='order_flow_imbalance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='订单流失衡分数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='sell_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='vpin_score',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN得分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='vwap_mean_reversion_corr',
            field=models.FloatField(blank=True, null=True, verbose_name='VWAP均值回归相关性'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='buy_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='买方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='order_flow_imbalance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='订单流失衡分数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='sell_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='vpin_score',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN得分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='vwap_mean_reversion_corr',
            field=models.FloatField(blank=True, null=True, verbose_name='VWAP均值回归相关性'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='buy_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='买方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='order_flow_imbalance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='订单流失衡分数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='sell_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='vpin_score',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN得分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='vwap_mean_reversion_corr',
            field=models.FloatField(blank=True, null=True, verbose_name='VWAP均值回归相关性'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='buy_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='买方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='order_flow_imbalance_score',
            field=models.FloatField(blank=True, null=True, verbose_name='订单流失衡分数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='sell_sweep_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方扫单强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='vpin_score',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN得分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='vwap_mean_reversion_corr',
            field=models.FloatField(blank=True, null=True, verbose_name='VWAP均值回归相关性'),
        ),
    ]
