# Generated by Django 5.0.1 on 2025-11-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0081_trendlineevent_bj_trendlineevent_cy_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='platformfeature_bj',
            name='character_score',
            field=models.FloatField(blank=True, help_text='综合筹码、资金、结构证据的量化评分', null=True, verbose_name='平台性质分(-100~100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_bj',
            name='platform_character',
            field=models.CharField(blank=True, choices=[('ACCUMULATION', '主力吸筹'), ('DISTRIBUTION', '主力派发'), ('CONSOLIDATION', '中性整理'), ('SHAKEOUT', '震仓洗盘')], max_length=20, null=True, verbose_name='平台性质'),
        ),
        migrations.AddField(
            model_name='platformfeature_cy',
            name='character_score',
            field=models.FloatField(blank=True, help_text='综合筹码、资金、结构证据的量化评分', null=True, verbose_name='平台性质分(-100~100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_cy',
            name='platform_character',
            field=models.CharField(blank=True, choices=[('ACCUMULATION', '主力吸筹'), ('DISTRIBUTION', '主力派发'), ('CONSOLIDATION', '中性整理'), ('SHAKEOUT', '震仓洗盘')], max_length=20, null=True, verbose_name='平台性质'),
        ),
        migrations.AddField(
            model_name='platformfeature_kc',
            name='character_score',
            field=models.FloatField(blank=True, help_text='综合筹码、资金、结构证据的量化评分', null=True, verbose_name='平台性质分(-100~100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_kc',
            name='platform_character',
            field=models.CharField(blank=True, choices=[('ACCUMULATION', '主力吸筹'), ('DISTRIBUTION', '主力派发'), ('CONSOLIDATION', '中性整理'), ('SHAKEOUT', '震仓洗盘')], max_length=20, null=True, verbose_name='平台性质'),
        ),
        migrations.AddField(
            model_name='platformfeature_sh',
            name='character_score',
            field=models.FloatField(blank=True, help_text='综合筹码、资金、结构证据的量化评分', null=True, verbose_name='平台性质分(-100~100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_sh',
            name='platform_character',
            field=models.CharField(blank=True, choices=[('ACCUMULATION', '主力吸筹'), ('DISTRIBUTION', '主力派发'), ('CONSOLIDATION', '中性整理'), ('SHAKEOUT', '震仓洗盘')], max_length=20, null=True, verbose_name='平台性质'),
        ),
        migrations.AddField(
            model_name='platformfeature_sz',
            name='character_score',
            field=models.FloatField(blank=True, help_text='综合筹码、资金、结构证据的量化评分', null=True, verbose_name='平台性质分(-100~100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_sz',
            name='platform_character',
            field=models.CharField(blank=True, choices=[('ACCUMULATION', '主力吸筹'), ('DISTRIBUTION', '主力派发'), ('CONSOLIDATION', '中性整理'), ('SHAKEOUT', '震仓洗盘')], max_length=20, null=True, verbose_name='平台性质'),
        ),
    ]
