# Generated by Django 5.0.1 on 2025-11-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0082_platformfeature_bj_character_score_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='floating_chip_cleansing_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='浮筹清洗效率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='mf_cost_zone_defense_intent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='主力成本区攻防意图(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='floating_chip_cleansing_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='浮筹清洗效率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='mf_cost_zone_defense_intent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='主力成本区攻防意图(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='floating_chip_cleansing_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='浮筹清洗效率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='mf_cost_zone_defense_intent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='主力成本区攻防意图(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='floating_chip_cleansing_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='浮筹清洗效率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='mf_cost_zone_defense_intent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='主力成本区攻防意图(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='floating_chip_cleansing_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='浮筹清洗效率'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='mf_cost_zone_defense_intent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='主力成本区攻防意图(-100~100)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='buy_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='买方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='order_book_liquidity_supply',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口流动性供给(买/卖比)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='sell_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='buy_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='买方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='order_book_liquidity_supply',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口流动性供给(买/卖比)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='sell_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='buy_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='买方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='order_book_liquidity_supply',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口流动性供给(买/卖比)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='sell_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='buy_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='买方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='order_book_liquidity_supply',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口流动性供给(买/卖比)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='sell_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='buy_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='买方报价消耗率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='order_book_liquidity_supply',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口流动性供给(买/卖比)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='sell_quote_exhaustion_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='卖方报价消耗率(%)'),
        ),
    ]
