# Generated by Django 5.0.1 on 2025-11-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0083_advancedchipmetrics_bj_floating_chip_cleansing_efficiency_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='liquidity_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口深度斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='market_impact_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='市场冲击成本(%)'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='liquidity_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口深度斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='market_impact_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='市场冲击成本(%)'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='liquidity_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口深度斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='market_impact_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='市场冲击成本(%)'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='liquidity_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口深度斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='market_impact_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='市场冲击成本(%)'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='liquidity_slope',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口深度斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='market_impact_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='市场冲击成本(%)'),
        ),
    ]
