# Generated by Django 5.0.1 on 2025-11-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0084_advancedstructuralmetrics_bj_liquidity_slope_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='liquidity_authenticity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='流动性真实性评分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='liquidity_authenticity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='流动性真实性评分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='liquidity_authenticity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='流动性真实性评分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='liquidity_authenticity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='流动性真实性评分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='liquidity_authenticity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='流动性真实性评分'),
        ),
    ]
