# Generated by Django 5.0.1 on 2025-11-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0085_advancedstructuralmetrics_bj_liquidity_authenticity_score_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='platformfeature_bj',
            name='platform_archetype',
            field=models.CharField(blank=True, help_text='识别出此平台的原型名称', max_length=50, null=True, verbose_name='平台原型'),
        ),
        migrations.AddField(
            model_name='platformfeature_cy',
            name='platform_archetype',
            field=models.CharField(blank=True, help_text='识别出此平台的原型名称', max_length=50, null=True, verbose_name='平台原型'),
        ),
        migrations.AddField(
            model_name='platformfeature_kc',
            name='platform_archetype',
            field=models.CharField(blank=True, help_text='识别出此平台的原型名称', max_length=50, null=True, verbose_name='平台原型'),
        ),
        migrations.AddField(
            model_name='platformfeature_sh',
            name='platform_archetype',
            field=models.CharField(blank=True, help_text='识别出此平台的原型名称', max_length=50, null=True, verbose_name='平台原型'),
        ),
        migrations.AddField(
            model_name='platformfeature_sz',
            name='platform_archetype',
            field=models.CharField(blank=True, help_text='识别出此平台的原型名称', max_length=50, null=True, verbose_name='平台原型'),
        ),
    ]
