# Generated by Django 5.0.1 on 2025-11-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0086_platformfeature_bj_platform_archetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformfeature_bj',
            name='breakout_readiness_score',
            field=models.FloatField(blank=True, help_text='平台结束时，衡量其即将突破可能性的综合评分', null=True, verbose_name='突破准备度分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_cy',
            name='breakout_readiness_score',
            field=models.FloatField(blank=True, help_text='平台结束时，衡量其即将突破可能性的综合评分', null=True, verbose_name='突破准备度分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_kc',
            name='breakout_readiness_score',
            field=models.FloatField(blank=True, help_text='平台结束时，衡量其即将突破可能性的综合评分', null=True, verbose_name='突破准备度分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_sh',
            name='breakout_readiness_score',
            field=models.FloatField(blank=True, help_text='平台结束时，衡量其即将突破可能性的综合评分', null=True, verbose_name='突破准备度分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_sz',
            name='breakout_readiness_score',
            field=models.FloatField(blank=True, help_text='平台结束时，衡量其即将突破可能性的综合评分', null=True, verbose_name='突破准备度分(0-100)'),
        ),
    ]
