# Generated by Django 5.0.1 on 2025-11-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0087_platformfeature_bj_breakout_readiness_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformfeature_bj',
            name='goodness_of_fit_score',
            field=models.FloatField(blank=True, help_text='平台与最佳匹配原型之间的相似度得分', null=True, verbose_name='拟合优度分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_cy',
            name='goodness_of_fit_score',
            field=models.FloatField(blank=True, help_text='平台与最佳匹配原型之间的相似度得分', null=True, verbose_name='拟合优度分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_kc',
            name='goodness_of_fit_score',
            field=models.FloatField(blank=True, help_text='平台与最佳匹配原型之间的相似度得分', null=True, verbose_name='拟合优度分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_sh',
            name='goodness_of_fit_score',
            field=models.FloatField(blank=True, help_text='平台与最佳匹配原型之间的相似度得分', null=True, verbose_name='拟合优度分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_sz',
            name='goodness_of_fit_score',
            field=models.FloatField(blank=True, help_text='平台与最佳匹配原型之间的相似度得分', null=True, verbose_name='拟合优度分(0-100)'),
        ),
    ]
