# Generated by Django 5.0.1 on 2025-11-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0088_platformfeature_bj_goodness_of_fit_score_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='platformfeature_bj',
            name='platform_conviction_score',
            field=models.FloatField(blank=True, help_text='评估平台结构质量和主力控盘信念的综合得分', null=True, verbose_name='平台信念分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_cy',
            name='platform_conviction_score',
            field=models.FloatField(blank=True, help_text='评估平台结构质量和主力控盘信念的综合得分', null=True, verbose_name='平台信念分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_kc',
            name='platform_conviction_score',
            field=models.FloatField(blank=True, help_text='评估平台结构质量和主力控盘信念的综合得分', null=True, verbose_name='平台信念分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_sh',
            name='platform_conviction_score',
            field=models.FloatField(blank=True, help_text='评估平台结构质量和主力控盘信念的综合得分', null=True, verbose_name='平台信念分(0-100)'),
        ),
        migrations.AddField(
            model_name='platformfeature_sz',
            name='platform_conviction_score',
            field=models.FloatField(blank=True, help_text='评估平台结构质量和主力控盘信念的综合得分', null=True, verbose_name='平台信念分(0-100)'),
        ),
    ]
