# Generated by Django 5.0.1 on 2025-11-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0089_platformfeature_bj_platform_conviction_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multitimeframetrendline_bj',
            name='trend_conviction_score',
            field=models.FloatField(blank=True, help_text='评估趋势内在质量和主力信念的综合得分', null=True, verbose_name='趋势信念分(0-100)'),
        ),
        migrations.AddField(
            model_name='multitimeframetrendline_cy',
            name='trend_conviction_score',
            field=models.FloatField(blank=True, help_text='评估趋势内在质量和主力信念的综合得分', null=True, verbose_name='趋势信念分(0-100)'),
        ),
        migrations.AddField(
            model_name='multitimeframetrendline_kc',
            name='trend_conviction_score',
            field=models.FloatField(blank=True, help_text='评估趋势内在质量和主力信念的综合得分', null=True, verbose_name='趋势信念分(0-100)'),
        ),
        migrations.AddField(
            model_name='multitimeframetrendline_sh',
            name='trend_conviction_score',
            field=models.FloatField(blank=True, help_text='评估趋势内在质量和主力信念的综合得分', null=True, verbose_name='趋势信念分(0-100)'),
        ),
        migrations.AddField(
            model_name='multitimeframetrendline_sz',
            name='trend_conviction_score',
            field=models.FloatField(blank=True, help_text='评估趋势内在质量和主力信念的综合得分', null=True, verbose_name='趋势信念分(0-100)'),
        ),
    ]
