# Generated by Django 5.0.1 on 2025-11-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0090_multitimeframetrendline_bj_trend_conviction_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendlineevent_bj',
            name='event_type',
            field=models.CharField(choices=[('INFLECTION_ACCEL', '趋势加速'), ('INFLECTION_DECEL', '趋势减速'), ('INFLECTION_REVERSAL', '趋势反转'), ('CROSS_GOLDEN_DECISIVE', '决定性金叉'), ('CROSS_GOLDEN_TENTATIVE', '试探性金叉'), ('CROSS_DEATH_DECISIVE', '决定性死叉'), ('CROSS_DEATH_TENTATIVE', '试探性死叉'), ('RESONANCE_BULLISH_STRONG', '强烈多头共振'), ('RESONANCE_BEARISH_STRONG', '强烈空头共振'), ('DIVERGENCE_BEARISH_TOP', '顶部结构背离'), ('DIVERGENCE_BULLISH_BOTTOM', '底部结构背离'), ('COMPRESSION_SQUEEZE', '通道能量压缩'), ('FLAG_FORMED_D', '日线旗形确立'), ('FLAG_FORMED_W', '周线旗形确立')], max_length=50, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='trendlineevent_cy',
            name='event_type',
            field=models.CharField(choices=[('INFLECTION_ACCEL', '趋势加速'), ('INFLECTION_DECEL', '趋势减速'), ('INFLECTION_REVERSAL', '趋势反转'), ('CROSS_GOLDEN_DECISIVE', '决定性金叉'), ('CROSS_GOLDEN_TENTATIVE', '试探性金叉'), ('CROSS_DEATH_DECISIVE', '决定性死叉'), ('CROSS_DEATH_TENTATIVE', '试探性死叉'), ('RESONANCE_BULLISH_STRONG', '强烈多头共振'), ('RESONANCE_BEARISH_STRONG', '强烈空头共振'), ('DIVERGENCE_BEARISH_TOP', '顶部结构背离'), ('DIVERGENCE_BULLISH_BOTTOM', '底部结构背离'), ('COMPRESSION_SQUEEZE', '通道能量压缩'), ('FLAG_FORMED_D', '日线旗形确立'), ('FLAG_FORMED_W', '周线旗形确立')], max_length=50, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='trendlineevent_kc',
            name='event_type',
            field=models.CharField(choices=[('INFLECTION_ACCEL', '趋势加速'), ('INFLECTION_DECEL', '趋势减速'), ('INFLECTION_REVERSAL', '趋势反转'), ('CROSS_GOLDEN_DECISIVE', '决定性金叉'), ('CROSS_GOLDEN_TENTATIVE', '试探性金叉'), ('CROSS_DEATH_DECISIVE', '决定性死叉'), ('CROSS_DEATH_TENTATIVE', '试探性死叉'), ('RESONANCE_BULLISH_STRONG', '强烈多头共振'), ('RESONANCE_BEARISH_STRONG', '强烈空头共振'), ('DIVERGENCE_BEARISH_TOP', '顶部结构背离'), ('DIVERGENCE_BULLISH_BOTTOM', '底部结构背离'), ('COMPRESSION_SQUEEZE', '通道能量压缩'), ('FLAG_FORMED_D', '日线旗形确立'), ('FLAG_FORMED_W', '周线旗形确立')], max_length=50, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='trendlineevent_sh',
            name='event_type',
            field=models.CharField(choices=[('INFLECTION_ACCEL', '趋势加速'), ('INFLECTION_DECEL', '趋势减速'), ('INFLECTION_REVERSAL', '趋势反转'), ('CROSS_GOLDEN_DECISIVE', '决定性金叉'), ('CROSS_GOLDEN_TENTATIVE', '试探性金叉'), ('CROSS_DEATH_DECISIVE', '决定性死叉'), ('CROSS_DEATH_TENTATIVE', '试探性死叉'), ('RESONANCE_BULLISH_STRONG', '强烈多头共振'), ('RESONANCE_BEARISH_STRONG', '强烈空头共振'), ('DIVERGENCE_BEARISH_TOP', '顶部结构背离'), ('DIVERGENCE_BULLISH_BOTTOM', '底部结构背离'), ('COMPRESSION_SQUEEZE', '通道能量压缩'), ('FLAG_FORMED_D', '日线旗形确立'), ('FLAG_FORMED_W', '周线旗形确立')], max_length=50, verbose_name='事件类型'),
        ),
        migrations.AlterField(
            model_name='trendlineevent_sz',
            name='event_type',
            field=models.CharField(choices=[('INFLECTION_ACCEL', '趋势加速'), ('INFLECTION_DECEL', '趋势减速'), ('INFLECTION_REVERSAL', '趋势反转'), ('CROSS_GOLDEN_DECISIVE', '决定性金叉'), ('CROSS_GOLDEN_TENTATIVE', '试探性金叉'), ('CROSS_DEATH_DECISIVE', '决定性死叉'), ('CROSS_DEATH_TENTATIVE', '试探性死叉'), ('RESONANCE_BULLISH_STRONG', '强烈多头共振'), ('RESONANCE_BEARISH_STRONG', '强烈空头共振'), ('DIVERGENCE_BEARISH_TOP', '顶部结构背离'), ('DIVERGENCE_BULLISH_BOTTOM', '底部结构背离'), ('COMPRESSION_SQUEEZE', '通道能量压缩'), ('FLAG_FORMED_D', '日线旗形确立'), ('FLAG_FORMED_W', '周线旗形确立')], max_length=50, verbose_name='事件类型'),
        ),
    ]
