# Generated by Django 5.0.1 on 2025-11-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0092_remove_advancedfundflowmetrics_bj_inferred_active_order_size_accel_13d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_bj',
            name='asymmetric_volume_thrust',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_bj',
            name='inferred_active_order_size',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_cy',
            name='asymmetric_volume_thrust',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_cy',
            name='inferred_active_order_size',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_kc',
            name='asymmetric_volume_thrust',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_kc',
            name='inferred_active_order_size',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sh',
            name='asymmetric_volume_thrust',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sh',
            name='inferred_active_order_size',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sz',
            name='asymmetric_volume_thrust',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sz',
            name='inferred_active_order_size',
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='micro_price_impact_asymmetry',
            field=models.FloatField(blank=True, null=True, verbose_name='微观价格冲击不对称性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='observed_large_order_size_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='观测大单平均规模(元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='order_book_clearing_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口清扫率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='micro_price_impact_asymmetry',
            field=models.FloatField(blank=True, null=True, verbose_name='微观价格冲击不对称性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='observed_large_order_size_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='观测大单平均规模(元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='order_book_clearing_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口清扫率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='micro_price_impact_asymmetry',
            field=models.FloatField(blank=True, null=True, verbose_name='微观价格冲击不对称性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='observed_large_order_size_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='观测大单平均规模(元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='order_book_clearing_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口清扫率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='micro_price_impact_asymmetry',
            field=models.FloatField(blank=True, null=True, verbose_name='微观价格冲击不对称性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='observed_large_order_size_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='观测大单平均规模(元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='order_book_clearing_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口清扫率(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='micro_price_impact_asymmetry',
            field=models.FloatField(blank=True, null=True, verbose_name='微观价格冲击不对称性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='observed_large_order_size_avg',
            field=models.FloatField(blank=True, null=True, verbose_name='观测大单平均规模(元)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='order_book_clearing_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口清扫率(%)'),
        ),
    ]
