# Generated by Django 5.0.1 on 2025-11-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0093_remove_advancedfundflowmetrics_bj_asymmetric_volume_thrust_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedchipmetrics_bj',
            name='suppressive_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='打压吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_cy',
            name='suppressive_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='打压吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_kc',
            name='suppressive_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='打压吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sh',
            name='suppressive_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='打压吸筹强度'),
        ),
        migrations.AddField(
            model_name='advancedchipmetrics_sz',
            name='suppressive_accumulation_intensity',
            field=models.FloatField(blank=True, null=True, verbose_name='打压吸筹强度'),
        ),
    ]
