# Generated by Django 5.0.1 on 2025-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0094_advancedchipmetrics_bj_suppressive_accumulation_intensity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='imbalance_effectiveness',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口失衡有效性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='imbalance_effectiveness',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口失衡有效性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='imbalance_effectiveness',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口失衡有效性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='imbalance_effectiveness',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口失衡有效性'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='imbalance_effectiveness',
            field=models.FloatField(blank=True, null=True, verbose_name='盘口失衡有效性'),
        ),
    ]
