# Generated by Django 5.0.1 on 2025-11-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0095_advancedfundflowmetrics_bj_imbalance_effectiveness_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_posture_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力姿态指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_posture_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力姿态指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_posture_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力姿态指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_posture_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力姿态指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_posture_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力姿态指数'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_activity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力参与度(%)'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_activity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力参与度(%)'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_activity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力参与度(%)'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_activity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力参与度(%)'),
        ),
        migrations.AlterField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_activity_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='主力参与度(%)'),
        ),
    ]
