# Generated by Django 5.0.1 on 2025-12-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0096_advancedfundflowmetrics_bj_main_force_posture_index_and_more'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_bj',
            name='closing_price_deviation_score',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_cy',
            name='closing_price_deviation_score',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_kc',
            name='closing_price_deviation_score',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sh',
            name='closing_price_deviation_score',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sz',
            name='closing_price_deviation_score',
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='closing_strength_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘强度指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='closing_strength_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘强度指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='closing_strength_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘强度指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='closing_strength_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘强度指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='closing_strength_index',
            field=models.FloatField(blank=True, null=True, verbose_name='收盘强度指数'),
        ),
    ]
