# Generated by Django 5.0.1 on 2025-12-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0097_remove_advancedfundflowmetrics_bj_closing_price_deviation_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_bj',
            name='trend_conviction_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_cy',
            name='trend_conviction_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_kc',
            name='trend_conviction_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sh',
            name='trend_conviction_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sz',
            name='trend_conviction_ratio',
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='trend_alignment_index',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势同向指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='trend_alignment_index',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势同向指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='trend_alignment_index',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势同向指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='trend_alignment_index',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势同向指数'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='trend_alignment_index',
            field=models.FloatField(blank=True, null=True, verbose_name='趋势同向指数'),
        ),
    ]
