# Generated by Django 5.0.1 on 2025-12-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0098_remove_advancedfundflowmetrics_bj_trend_conviction_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_bj',
            name='microstructure_efficiency_index',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_cy',
            name='microstructure_efficiency_index',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_kc',
            name='microstructure_efficiency_index',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sh',
            name='microstructure_efficiency_index',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sz',
            name='microstructure_efficiency_index',
        ),
    ]
