# Generated by Django 5.0.1 on 2025-12-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0099_remove_advancedfundflowmetrics_bj_ofi_price_impact_factor_and_more'),
    ]
    operations = [
        migrations.RemoveIndex(
            model_name='advancedfundflowmetrics_bj',
            name='stock_advan_main_fo_9a6a8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedfundflowmetrics_cy',
            name='stock_advan_main_fo_b08962_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedfundflowmetrics_kc',
            name='stock_advan_main_fo_b6de30_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedfundflowmetrics_sh',
            name='stock_advan_main_fo_40402e_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedfundflowmetrics_sz',
            name='stock_advan_main_fo_005341_idx',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_price_impact_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_price_impact_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_price_impact_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_price_impact_ratio',
        ),
        migrations.RemoveField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_price_impact_ratio',
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_bj',
            name='main_force_slippage_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力滑点指数(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_cy',
            name='main_force_slippage_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力滑点指数(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_kc',
            name='main_force_slippage_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力滑点指数(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sh',
            name='main_force_slippage_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力滑点指数(%)'),
        ),
        migrations.AddField(
            model_name='advancedfundflowmetrics_sz',
            name='main_force_slippage_index',
            field=models.FloatField(blank=True, null=True, verbose_name='主力滑点指数(%)'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_bj',
            index=models.Index(fields=['main_force_slippage_index'], name='stock_advan_main_fo_43a8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_cy',
            index=models.Index(fields=['main_force_slippage_index'], name='stock_advan_main_fo_c4d893_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_kc',
            index=models.Index(fields=['main_force_slippage_index'], name='stock_advan_main_fo_9f43bc_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_sh',
            index=models.Index(fields=['main_force_slippage_index'], name='stock_advan_main_fo_472561_idx'),
        ),
        migrations.AddIndex(
            model_name='advancedfundflowmetrics_sz',
            index=models.Index(fields=['main_force_slippage_index'], name='stock_advan_main_fo_01e6e9_idx'),
        ),
    ]
