# Generated by Django 5.0.1 on 2025-12-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0100_remove_advancedfundflowmetrics_bj_stock_advan_main_fo_9a6a8a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='absorption_strength_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='吸筹强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='sweep_intensity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='扫单强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_purity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='推力纯度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='vpin_roc3',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN3日变化率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='absorption_strength_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='吸筹强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='sweep_intensity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='扫单强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_purity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='推力纯度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='vpin_roc3',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN3日变化率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='absorption_strength_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='吸筹强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='sweep_intensity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='扫单强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_purity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='推力纯度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='vpin_roc3',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN3日变化率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='absorption_strength_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='吸筹强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='sweep_intensity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='扫单强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_purity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='推力纯度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='vpin_roc3',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN3日变化率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='absorption_strength_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='吸筹强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='sweep_intensity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='扫单强度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_purity_ma5',
            field=models.FloatField(blank=True, null=True, verbose_name='推力纯度5日均线'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='vpin_roc3',
            field=models.FloatField(blank=True, null=True, verbose_name='VPIN3日变化率'),
        ),
    ]
