# Generated by Django 5.0.1 on 2025-12-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0101_advancedstructuralmetrics_bj_absorption_strength_ma5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='upward_thrust_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='upward_thrust_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='upward_thrust_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='upward_thrust_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='upward_thrust_efficacy',
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='upward_distribution_efficacy',
            field=models.FloatField(blank=True, null=True, verbose_name='上行派发效能'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='upward_distribution_efficacy',
            field=models.FloatField(blank=True, null=True, verbose_name='上行派发效能'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='upward_distribution_efficacy',
            field=models.FloatField(blank=True, null=True, verbose_name='上行派发效能'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='upward_distribution_efficacy',
            field=models.FloatField(blank=True, null=True, verbose_name='上行派发效能'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='upward_distribution_efficacy',
            field=models.FloatField(blank=True, null=True, verbose_name='上行派发效能'),
        ),
    ]
