# Generated by Django 5.0.1 on 2025-12-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0102_remove_advancedstructuralmetrics_bj_upward_thrust_efficacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='rebound_momentum',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='rebound_momentum',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='rebound_momentum',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='rebound_momentum',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='rebound_momentum',
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='dynamic_reversal_strength',
            field=models.FloatField(blank=True, null=True, verbose_name='动态反转强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='dynamic_reversal_strength',
            field=models.FloatField(blank=True, null=True, verbose_name='动态反转强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='dynamic_reversal_strength',
            field=models.FloatField(blank=True, null=True, verbose_name='动态反转强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='dynamic_reversal_strength',
            field=models.FloatField(blank=True, null=True, verbose_name='动态反转强度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='dynamic_reversal_strength',
            field=models.FloatField(blank=True, null=True, verbose_name='动态反转强度'),
        ),
    ]
