# Generated by Django 5.0.1 on 2025-12-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0103_remove_advancedstructuralmetrics_bj_rebound_momentum_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='reversal_conviction_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转信念比率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='reversal_conviction_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转信念比率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='reversal_conviction_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转信念比率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='reversal_conviction_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转信念比率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='reversal_conviction_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转信念比率'),
        ),
    ]
