# Generated by Django 5.0.1 on 2025-12-01 06:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0104_advancedstructuralmetrics_bj_reversal_conviction_rate_and_more'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='downward_absorption_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='upward_distribution_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='downward_absorption_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='upward_distribution_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='downward_absorption_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='upward_distribution_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='downward_absorption_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='upward_distribution_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='downward_absorption_efficacy',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='upward_distribution_efficacy',
        ),
    ]
