# Generated by Django 5.0.1 on 2025-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0105_remove_advancedstructuralmetrics_bj_downward_absorption_efficacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='reversal_recovery_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转收复率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='reversal_recovery_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转收复率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='reversal_recovery_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转收复率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='reversal_recovery_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转收复率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='reversal_recovery_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='反转收复率'),
        ),
    ]
