# Generated by Django 5.0.1 on 2025-12-01 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0106_advancedstructuralmetrics_bj_reversal_recovery_rate_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='stocktickdata_bj',
            name='price_change',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='价格变动'),
        ),
        migrations.AddField(
            model_name='stocktickdata_cy',
            name='price_change',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='价格变动'),
        ),
        migrations.AddField(
            model_name='stocktickdata_kc',
            name='price_change',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='价格变动'),
        ),
        migrations.AddField(
            model_name='stocktickdata_sh',
            name='price_change',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='价格变动'),
        ),
        migrations.AddField(
            model_name='stocktickdata_sz',
            name='price_change',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='价格变动'),
        ),
    ]
