# Generated by Django 5.0.1 on 2025-12-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0107_stocktickdata_bj_price_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='breakthrough_conviction_score',
            field=models.FloatField(blank=True, null=True, verbose_name='突破信念分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='thrust_efficiency_score_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='breakthrough_conviction_score',
            field=models.FloatField(blank=True, null=True, verbose_name='突破信念分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='thrust_efficiency_score_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='breakthrough_conviction_score',
            field=models.FloatField(blank=True, null=True, verbose_name='突破信念分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='thrust_efficiency_score_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='breakthrough_conviction_score',
            field=models.FloatField(blank=True, null=True, verbose_name='突破信念分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='thrust_efficiency_score_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='breakthrough_conviction_score',
            field=models.FloatField(blank=True, null=True, verbose_name='突破信念分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_accel_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_accel_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_accel_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_accel_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_accel_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日加速度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_slope_13d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分13日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_slope_1d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分1日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_slope_21d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分21日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_slope_55d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分55日斜率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='thrust_efficiency_score_slope_5d',
            field=models.FloatField(blank=True, null=True, verbose_name='推力效能分5日斜率'),
        ),
    ]
