# Generated by Django 5.0.1 on 2025-12-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0108_advancedstructuralmetrics_bj_breakthrough_conviction_score_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='defense_solidity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='防守稳固度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='defense_solidity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='防守稳固度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='defense_solidity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='防守稳固度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='defense_solidity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='防守稳固度'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='defense_solidity_score',
            field=models.FloatField(blank=True, null=True, verbose_name='防守稳固度'),
        ),
    ]
