# Generated by Django 5.0.1 on 2025-12-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stock_models', '0109_advancedstructuralmetrics_bj_defense_solidity_score_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='equilibrium_compression_index',
            field=models.FloatField(blank=True, null=True, verbose_name='均衡压缩指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='equilibrium_compression_index',
            field=models.FloatField(blank=True, null=True, verbose_name='均衡压缩指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='equilibrium_compression_index',
            field=models.FloatField(blank=True, null=True, verbose_name='均衡压缩指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='equilibrium_compression_index',
            field=models.FloatField(blank=True, null=True, verbose_name='均衡压缩指数'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='equilibrium_compression_index',
            field=models.FloatField(blank=True, null=True, verbose_name='均衡压缩指数'),
        ),
    ]
