# Generated by Django 5.0.1 on 2025-12-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0110_advancedstructuralmetrics_bj_equilibrium_compression_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='vpoc_consensus_strength',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='vpoc_deviation_magnitude',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='vpoc_consensus_strength',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='vpoc_deviation_magnitude',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='vpoc_consensus_strength',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='vpoc_deviation_magnitude',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='vpoc_consensus_strength',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='vpoc_deviation_magnitude',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='vpoc_consensus_strength',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='vpoc_deviation_magnitude',
        ),
    ]
