# Generated by Django 5.0.1 on 2025-12-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0111_remove_advancedstructuralmetrics_bj_vpoc_consensus_strength_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='advancedstructuralmetrics_bj',
            name='stock_advan_diverge_428a13_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedstructuralmetrics_cy',
            name='stock_advan_diverge_582f42_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedstructuralmetrics_kc',
            name='stock_advan_diverge_c7f96a_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedstructuralmetrics_sh',
            name='stock_advan_diverge_ae664c_idx',
        ),
        migrations.RemoveIndex(
            model_name='advancedstructuralmetrics_sz',
            name='stock_advan_diverge_00d826_idx',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='divergence_conviction_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='net_vpa_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='divergence_conviction_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='net_vpa_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='divergence_conviction_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='net_vpa_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='divergence_conviction_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='net_vpa_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='divergence_conviction_score',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='net_vpa_score',
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='price_thrust_divergence',
            field=models.FloatField(blank=True, null=True, verbose_name='价格动能背离'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='price_thrust_divergence',
            field=models.FloatField(blank=True, null=True, verbose_name='价格动能背离'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='price_thrust_divergence',
            field=models.FloatField(blank=True, null=True, verbose_name='价格动能背离'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='price_thrust_divergence',
            field=models.FloatField(blank=True, null=True, verbose_name='价格动能背离'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='price_thrust_divergence',
            field=models.FloatField(blank=True, null=True, verbose_name='价格动能背离'),
        ),
    ]
