# Generated by Django 5.0.1 on 2025-12-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0112_remove_advancedstructuralmetrics_bj_stock_advan_diverge_428a13_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='midday_consolidation_level',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='opening_volume_impulse',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_bj',
            name='tail_volume_acceleration',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='midday_consolidation_level',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='opening_volume_impulse',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_cy',
            name='tail_volume_acceleration',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='midday_consolidation_level',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='opening_volume_impulse',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_kc',
            name='tail_volume_acceleration',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='midday_consolidation_level',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='opening_volume_impulse',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sh',
            name='tail_volume_acceleration',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='midday_consolidation_level',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='opening_volume_impulse',
        ),
        migrations.RemoveField(
            model_name='advancedstructuralmetrics_sz',
            name='tail_volume_acceleration',
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='midday_narrow_range_gravity',
            field=models.FloatField(blank=True, null=True, verbose_name='盘中窄幅引力'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='opening_impulse_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘脉冲效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_bj',
            name='tail_acceleration_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='尾盘加速效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='midday_narrow_range_gravity',
            field=models.FloatField(blank=True, null=True, verbose_name='盘中窄幅引力'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='opening_impulse_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘脉冲效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_cy',
            name='tail_acceleration_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='尾盘加速效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='midday_narrow_range_gravity',
            field=models.FloatField(blank=True, null=True, verbose_name='盘中窄幅引力'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='opening_impulse_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘脉冲效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_kc',
            name='tail_acceleration_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='尾盘加速效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='midday_narrow_range_gravity',
            field=models.FloatField(blank=True, null=True, verbose_name='盘中窄幅引力'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='opening_impulse_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘脉冲效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sh',
            name='tail_acceleration_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='尾盘加速效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='midday_narrow_range_gravity',
            field=models.FloatField(blank=True, null=True, verbose_name='盘中窄幅引力'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='opening_impulse_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='开盘脉冲效率'),
        ),
        migrations.AddField(
            model_name='advancedstructuralmetrics_sz',
            name='tail_acceleration_efficiency',
            field=models.FloatField(blank=True, null=True, verbose_name='尾盘加速效率'),
        ),
    ]
